# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/synthesis/dimensional_synthesis/dimension_widget.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from core.QtModules import *


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(564, 682)
        icon = QIcon()
        icon.addPixmap(QPixmap(":/icons/dimensional_synthesis.png"), QIcon.Normal, QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout_4 = QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.main_splitter = QSplitter(Form)
        self.main_splitter.setOrientation(Qt.Vertical)
        self.main_splitter.setObjectName("main_splitter")
        self.options_tab = QTabWidget(self.main_splitter)
        self.options_tab.setObjectName("options_tab")
        self.structure = QWidget()
        self.structure.setObjectName("structure")
        self.verticalLayout_7 = QVBoxLayout(self.structure)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.up_splitter = QSplitter(self.structure)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_splitter.sizePolicy().hasHeightForWidth())
        self.up_splitter.setSizePolicy(sizePolicy)
        self.up_splitter.setOrientation(Qt.Horizontal)
        self.up_splitter.setObjectName("up_splitter")
        self.layoutWidget = QWidget(self.up_splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.load_profile = QPushButton(self.layoutWidget)
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(":/icons/collections.png"), QIcon.Normal, QIcon.Off)
        self.load_profile.setIcon(icon1)
        self.load_profile.setObjectName("load_profile")
        self.horizontalLayout_7.addWidget(self.load_profile)
        self.save_profile = QPushButton(self.layoutWidget)
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(":/icons/save_file.png"), QIcon.Normal, QIcon.Off)
        self.save_profile.setIcon(icon2)
        self.save_profile.setObjectName("save_profile")
        self.horizontalLayout_7.addWidget(self.save_profile)
        self.profile_name = QLineEdit(self.layoutWidget)
        self.profile_name.setReadOnly(True)
        self.profile_name.setObjectName("profile_name")
        self.horizontalLayout_7.addWidget(self.profile_name)
        self.clear_button = QPushButton(self.layoutWidget)
        icon3 = QIcon()
        icon3.addPixmap(QPixmap(":/icons/clean.png"), QIcon.Normal, QIcon.Off)
        self.clear_button.setIcon(icon3)
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout_7.addWidget(self.clear_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_17 = QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.expression_string = QLineEdit(self.layoutWidget)
        self.expression_string.setReadOnly(True)
        self.expression_string.setObjectName("expression_string")
        self.horizontalLayout_17.addWidget(self.expression_string)
        self.expr_copy = QPushButton(self.layoutWidget)
        icon4 = QIcon()
        icon4.addPixmap(QPixmap(":/icons/copy.png"), QIcon.Normal, QIcon.Off)
        self.expr_copy.setIcon(icon4)
        self.expr_copy.setObjectName("expr_copy")
        self.horizontalLayout_17.addWidget(self.expr_copy)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.parameter_list = QTableWidget(self.layoutWidget)
        self.parameter_list.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.parameter_list.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.parameter_list.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.parameter_list.setObjectName("parameter_list")
        self.parameter_list.setColumnCount(5)
        self.parameter_list.setRowCount(0)
        item = QTableWidgetItem()
        self.parameter_list.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.parameter_list.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.parameter_list.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.parameter_list.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.parameter_list.setHorizontalHeaderItem(4, item)
        self.verticalLayout_6.addWidget(self.parameter_list)
        self.preview_box = QGroupBox(self.up_splitter)
        self.preview_box.setObjectName("preview_box")
        self.preview_layout = QVBoxLayout(self.preview_box)
        self.preview_layout.setObjectName("preview_layout")
        self.show_solutions = QCheckBox(self.preview_box)
        self.show_solutions.setChecked(True)
        self.show_solutions.setObjectName("show_solutions")
        self.preview_layout.addWidget(self.show_solutions)
        self.verticalLayout_7.addWidget(self.up_splitter)
        icon5 = QIcon()
        icon5.addPixmap(QPixmap(":/icons/structure.png"), QIcon.Normal, QIcon.Off)
        self.options_tab.addTab(self.structure, icon5, "")
        self.target_path = QWidget()
        self.target_path.setObjectName("target_path")
        self.verticalLayout_5 = QVBoxLayout(self.target_path)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.down_splitter = QSplitter(self.target_path)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.down_splitter.sizePolicy().hasHeightForWidth())
        self.down_splitter.setSizePolicy(sizePolicy)
        self.down_splitter.setOrientation(Qt.Horizontal)
        self.down_splitter.setObjectName("down_splitter")
        self.target_points = QListWidget(self.down_splitter)
        self.target_points.setObjectName("target_points")
        self.layoutWidget1 = QWidget(self.down_splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.path_clear = QPushButton(self.layoutWidget1)
        self.path_clear.setIcon(icon3)
        self.path_clear.setAutoDefault(False)
        self.path_clear.setObjectName("path_clear")
        self.horizontalLayout_2.addWidget(self.path_clear)
        self.line = QFrame(self.layoutWidget1)
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.path_copy = QPushButton(self.layoutWidget1)
        self.path_copy.setIcon(icon4)
        self.path_copy.setObjectName("path_copy")
        self.horizontalLayout_2.addWidget(self.path_copy)
        self.path_paste = QPushButton(self.layoutWidget1)
        icon6 = QIcon()
        icon6.addPixmap(QPixmap(":/icons/paste.png"), QIcon.Normal, QIcon.Off)
        self.path_paste.setIcon(icon6)
        self.path_paste.setObjectName("path_paste")
        self.horizontalLayout_2.addWidget(self.path_paste)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pointNum = QLabel(self.layoutWidget1)
        self.pointNum.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.pointNum.setObjectName("pointNum")
        self.horizontalLayout_2.addWidget(self.pointNum)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_8 = QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.path_list = QListWidget(self.layoutWidget1)
        self.path_list.setObjectName("path_list")
        self.verticalLayout_8.addWidget(self.path_list)
        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.point_up = QPushButton(self.layoutWidget1)
        icon7 = QIcon()
        icon7.addPixmap(QPixmap(":/icons/arrow_up.png"), QIcon.Normal, QIcon.Off)
        self.point_up.setIcon(icon7)
        self.point_up.setObjectName("point_up")
        self.horizontalLayout_8.addWidget(self.point_up)
        self.point_down = QPushButton(self.layoutWidget1)
        icon8 = QIcon()
        icon8.addPixmap(QPixmap(":/icons/arrow_down.png"), QIcon.Normal, QIcon.Off)
        self.point_down.setIcon(icon8)
        self.point_down.setObjectName("point_down")
        self.horizontalLayout_8.addWidget(self.point_down)
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.point_delete = QPushButton(self.layoutWidget1)
        icon9 = QIcon()
        icon9.addPixmap(QPixmap(":/icons/delete.png"), QIcon.Normal, QIcon.Off)
        self.point_delete.setIcon(icon9)
        self.point_delete.setObjectName("point_delete")
        self.horizontalLayout_8.addWidget(self.point_delete)
        self.close_path = QPushButton(self.layoutWidget1)
        icon10 = QIcon()
        icon10.addPixmap(QPixmap(":/icons/free_move_off.png"), QIcon.Normal, QIcon.Off)
        self.close_path.setIcon(icon10)
        self.close_path.setObjectName("close_path")
        self.horizontalLayout_8.addWidget(self.close_path)
        self.edit_target_point_button = QPushButton(self.layoutWidget1)
        icon11 = QIcon()
        icon11.addPixmap(QPixmap(":/icons/translate.png"), QIcon.Normal, QIcon.Off)
        self.edit_target_point_button.setIcon(icon11)
        self.edit_target_point_button.setCheckable(True)
        self.edit_target_point_button.setChecked(True)
        self.edit_target_point_button.setObjectName("edit_target_point_button")
        self.horizontalLayout_8.addWidget(self.edit_target_point_button)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.path_adjust_button = QPushButton(self.layoutWidget1)
        icon12 = QIcon()
        icon12.addPixmap(QPixmap(":/icons/formula.png"), QIcon.Normal, QIcon.Off)
        self.path_adjust_button.setIcon(icon12)
        self.path_adjust_button.setObjectName("path_adjust_button")
        self.verticalLayout_3.addWidget(self.path_adjust_button)
        self.import_xlsx_button = QPushButton(self.layoutWidget1)
        self.import_xlsx_button.setText("")
        icon13 = QIcon()
        icon13.addPixmap(QPixmap(":/icons/excel_2013.png"), QIcon.Normal, QIcon.Off)
        self.import_xlsx_button.setIcon(icon13)
        self.import_xlsx_button.setIconSize(QSize(20, 20))
        self.import_xlsx_button.setObjectName("import_xlsx_button")
        self.verticalLayout_3.addWidget(self.import_xlsx_button)
        self.import_csv_button = QPushButton(self.layoutWidget1)
        self.import_csv_button.setText("")
        icon14 = QIcon()
        icon14.addPixmap(QPixmap(":/icons/csv.png"), QIcon.Normal, QIcon.Off)
        self.import_csv_button.setIcon(icon14)
        self.import_csv_button.setIconSize(QSize(20, 20))
        self.import_csv_button.setObjectName("import_csv_button")
        self.verticalLayout_3.addWidget(self.import_csv_button)
        spacerItem2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.down_splitter)
        self.label_2 = QLabel(self.target_path)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.options_tab.addTab(self.target_path, icon, "")
        self.algorithm = QWidget()
        self.algorithm.setObjectName("algorithm")
        self.verticalLayout = QVBoxLayout(self.algorithm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.type0 = QRadioButton(self.algorithm)
        self.type0.setChecked(False)
        self.type0.setObjectName("type0")
        self.verticalLayout.addWidget(self.type0)
        self.type1 = QRadioButton(self.algorithm)
        self.type1.setObjectName("type1")
        self.verticalLayout.addWidget(self.type1)
        self.type2 = QRadioButton(self.algorithm)
        self.type2.setChecked(True)
        self.type2.setObjectName("type2")
        self.verticalLayout.addWidget(self.type2)
        self.advance_button = QPushButton(self.algorithm)
        icon15 = QIcon()
        icon15.addPixmap(QPixmap(":/icons/properties.png"), QIcon.Normal, QIcon.Off)
        self.advance_button.setIcon(icon15)
        self.advance_button.setObjectName("advance_button")
        self.verticalLayout.addWidget(self.advance_button)
        spacerItem3 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QLabel(self.algorithm)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        spacerItem4 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.timeShow = QLabel(self.algorithm)
        self.timeShow.setObjectName("timeShow")
        self.horizontalLayout.addWidget(self.timeShow)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.synthesis_button = QPushButton(self.algorithm)
        self.synthesis_button.setEnabled(False)
        self.synthesis_button.setMinimumSize(QSize(120, 0))
        icon16 = QIcon()
        icon16.addPixmap(QPixmap(":/icons/play.png"), QIcon.Normal, QIcon.Off)
        self.synthesis_button.setIcon(icon16)
        self.synthesis_button.setAutoDefault(True)
        self.synthesis_button.setObjectName("synthesis_button")
        self.verticalLayout.addWidget(self.synthesis_button)
        icon17 = QIcon()
        icon17.addPixmap(QPixmap(":/icons/synthesis.png"), QIcon.Normal, QIcon.Off)
        self.options_tab.addTab(self.algorithm, icon17, "")
        self.verticalGroupBox = QGroupBox(self.main_splitter)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.horizontalLayout_6 = QHBoxLayout(self.verticalGroupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_13 = QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.result_list = QListWidget(self.verticalGroupBox)
        self.result_list.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.result_list.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.result_list.setObjectName("result_list")
        self.verticalLayout_13.addWidget(self.result_list)
        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.result_load_settings = QPushButton(self.verticalGroupBox)
        self.result_load_settings.setEnabled(False)
        icon18 = QIcon()
        icon18.addPixmap(QPixmap(":/icons/data_update.png"), QIcon.Normal, QIcon.Off)
        self.result_load_settings.setIcon(icon18)
        self.result_load_settings.setObjectName("result_load_settings")
        self.horizontalLayout_10.addWidget(self.result_load_settings)
        self.result_clipboard = QPushButton(self.verticalGroupBox)
        self.result_clipboard.setEnabled(False)
        self.result_clipboard.setIcon(icon4)
        self.result_clipboard.setObjectName("result_clipboard")
        self.horizontalLayout_10.addWidget(self.result_clipboard)
        spacerItem5 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.delete_button = QPushButton(self.verticalGroupBox)
        self.delete_button.setEnabled(False)
        self.delete_button.setIcon(icon9)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout_10.addWidget(self.delete_button)
        self.merge_button = QPushButton(self.verticalGroupBox)
        self.merge_button.setEnabled(False)
        icon19 = QIcon()
        icon19.addPixmap(QPixmap(":/icons/merge.png"), QIcon.Normal, QIcon.Off)
        self.merge_button.setIcon(icon19)
        self.merge_button.setObjectName("merge_button")
        self.horizontalLayout_10.addWidget(self.merge_button)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6.addLayout(self.verticalLayout_13)
        self.verticalLayout_4.addWidget(self.main_splitter)

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        self.load_profile.setStatusTip(_translate("Form", "Load profile from triangular iteration database."))
        self.save_profile.setStatusTip(_translate("Form", "Save the structure profile back to the database."))
        self.clear_button.setStatusTip(_translate("Form", "Clear the current profile and settings."))
        self.parameter_list.setStatusTip(_translate("Form", "All the joints of grounded link will show here."))
        item = self.parameter_list.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.parameter_list.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Role"))
        item = self.parameter_list.horizontalHeaderItem(2)
        item.setText(_translate("Form", "p0"))
        item = self.parameter_list.horizontalHeaderItem(3)
        item.setText(_translate("Form", "p1"))
        item = self.parameter_list.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Range"))
        self.preview_box.setTitle(_translate("Form", "Preview"))
        self.show_solutions.setText(_translate("Form", "Show solutions"))
        self.options_tab.setTabText(self.options_tab.indexOf(self.structure), _translate("Form", "Structure"))
        self.path_clear.setStatusTip(_translate("Form", "Clear all points."))
        self.path_copy.setStatusTip(_translate("Form", "Copy the path data as a string."))
        self.path_paste.setStatusTip(_translate("Form", "Past path data from string format."))
        self.pointNum.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aa00;\">0</span></p></body></html>"))
        self.point_up.setStatusTip(_translate("Form", "Move the point up."))
        self.point_down.setStatusTip(_translate("Form", "Move the point down."))
        self.point_delete.setStatusTip(_translate("Form", "Remove the point."))
        self.close_path.setStatusTip(_translate("Form", "Close the path."))
        self.edit_target_point_button.setStatusTip(_translate("Form", "User can edit target point immediately."))
        self.path_adjust_button.setStatusTip(_translate("Form", "Adjust the target path."))
        self.import_xlsx_button.setToolTip(_translate("Form", "Microsoft Excel"))
        self.import_xlsx_button.setStatusTip(_translate("Form", "Import path from Microsoft Excel format."))
        self.import_csv_button.setToolTip(_translate("Form", "CSV"))
        self.import_csv_button.setStatusTip(_translate("Form", "Import path from CSV format."))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ff0000;\">※ Use &quot;Alt + left button&quot; or &quot;context menu of canvas&quot; to add the path points.</span></p></body></html>"))
        self.options_tab.setTabText(self.options_tab.indexOf(self.target_path), _translate("Form", "Target path"))
        self.type0.setText(_translate("Form", "Real-coded Genetic Algorithm"))
        self.type1.setText(_translate("Form", "Firefly Algorithm"))
        self.type2.setText(_translate("Form", "Differential Evolution"))
        self.advance_button.setStatusTip(_translate("Form", "More algorithm settings."))
        self.advance_button.setText(_translate("Form", "Advance ..."))
        self.label_7.setText(_translate("Form", "Time spent:"))
        self.timeShow.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">[N/A]</span></p></body></html>"))
        self.synthesis_button.setStatusTip(_translate("Form", "Start dimesional synthesis."))
        self.synthesis_button.setText(_translate("Form", "Synthesis"))
        self.options_tab.setTabText(self.options_tab.indexOf(self.algorithm), _translate("Form", "Algorithm"))
        self.verticalGroupBox.setTitle(_translate("Form", "Results"))
        self.result_load_settings.setStatusTip(_translate("Form", "Load the setting of this result."))
        self.delete_button.setStatusTip(_translate("Form", "Delete this result."))
        self.merge_button.setStatusTip(_translate("Form", "Merge this result to canvas."))


import icons_rc
import preview_rc
