# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ahshoe/桌面/Pyslvs-PyQt5/core/synthesis/DimensionalSynthesis/series.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(340, 309)
        Dialog.setMinimumSize(QtCore.QSize(340, 309))
        Dialog.setMaximumSize(QtCore.QSize(340, 309))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/DimensionalSynthesis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(True)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.formula = QtWidgets.QComboBox(Dialog)
        self.formula.setObjectName("formula")
        self.formula.addItem("")
        self.formula.addItem("")
        self.formula.addItem("")
        self.formula.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.formula)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.coefficientValue = QtWidgets.QDoubleSpinBox(Dialog)
        self.coefficientValue.setMinimum(-10000.0)
        self.coefficientValue.setMaximum(10000.0)
        self.coefficientValue.setProperty("value", 1.0)
        self.coefficientValue.setObjectName("coefficientValue")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.coefficientValue)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.constant = QtWidgets.QDoubleSpinBox(Dialog)
        self.constant.setMinimum(-10000.0)
        self.constant.setMaximum(10000.0)
        self.constant.setObjectName("constant")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.constant)
        self.reverseX = QtWidgets.QCheckBox(Dialog)
        self.reverseX.setObjectName("reverseX")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.reverseX)
        self.verticalLayout_4.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.startNum = QtWidgets.QDoubleSpinBox(Dialog)
        self.startNum.setDecimals(1)
        self.startNum.setObjectName("startNum")
        self.verticalLayout.addWidget(self.startNum)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.diffNum = QtWidgets.QDoubleSpinBox(Dialog)
        self.diffNum.setDecimals(1)
        self.diffNum.setMinimum(0.1)
        self.diffNum.setProperty("value", 1.0)
        self.diffNum.setObjectName("diffNum")
        self.verticalLayout_2.addWidget(self.diffNum)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.endNum = QtWidgets.QDoubleSpinBox(Dialog)
        self.endNum.setDecimals(1)
        self.endNum.setMaximum(1000.0)
        self.endNum.setProperty("value", 10.0)
        self.endNum.setObjectName("endNum")
        self.verticalLayout_3.addWidget(self.endNum)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.generateButton = QtWidgets.QPushButton(Dialog)
        self.generateButton.setObjectName("generateButton")
        self.horizontalLayout_2.addWidget(self.generateButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.generateButton.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Formula ..."))
        self.formula.setItemText(0, _translate("Dialog", "f(x) = kx+c"))
        self.formula.setItemText(1, _translate("Dialog", "f(x) = kx²+c"))
        self.formula.setItemText(2, _translate("Dialog", "f(x) = kcos(xπ/180)+c"))
        self.formula.setItemText(3, _translate("Dialog", "f(x) = ksin(xπ/180)+c"))
        self.label_4.setText(_translate("Dialog", "Formula: "))
        self.label_6.setText(_translate("Dialog", "k value: "))
        self.label_7.setText(_translate("Dialog", "c value: "))
        self.reverseX.setText(_translate("Dialog", "Reverse x and y"))
        self.label_5.setText(_translate("Dialog", "x value range:"))
        self.label.setText(_translate("Dialog", "Start:"))
        self.label_2.setText(_translate("Dialog", "difference:"))
        self.label_3.setText(_translate("Dialog", "End:"))
        self.generateButton.setText(_translate("Dialog", "Generate"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

