# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ahshoe\Desktop\Pyslvs-PyQt5\core\synthesis\DimensionalSynthesis\DimensionalSynthesis_dialog\options.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(471, 553)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/DimensionalSynthesis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settings_tab = QtWidgets.QTabWidget(Dialog)
        self.settings_tab.setObjectName("settings_tab")
        self.planarlinkage_tab = QtWidgets.QWidget()
        self.planarlinkage_tab.setObjectName("planarlinkage_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.planarlinkage_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.maxGen_option = QtWidgets.QRadioButton(self.planarlinkage_tab)
        self.maxGen_option.setChecked(True)
        self.maxGen_option.setObjectName("maxGen_option")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.maxGen_option)
        self.maxGen = QtWidgets.QSpinBox(self.planarlinkage_tab)
        self.maxGen.setMinimum(0)
        self.maxGen.setMaximum(5000)
        self.maxGen.setSingleStep(100)
        self.maxGen.setProperty("value", 1000)
        self.maxGen.setObjectName("maxGen")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.maxGen)
        self.minFit_option = QtWidgets.QRadioButton(self.planarlinkage_tab)
        self.minFit_option.setObjectName("minFit_option")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.minFit_option)
        self.minFit = QtWidgets.QDoubleSpinBox(self.planarlinkage_tab)
        self.minFit.setEnabled(False)
        self.minFit.setMaximum(2000.0)
        self.minFit.setProperty("value", 25.0)
        self.minFit.setObjectName("minFit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.minFit)
        self.report_label = QtWidgets.QLabel(self.planarlinkage_tab)
        self.report_label.setObjectName("report_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.report_label)
        self.report = QtWidgets.QSpinBox(self.planarlinkage_tab)
        self.report.setProperty("value", 10)
        self.report.setObjectName("report")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.report)
        self.maxTime_option = QtWidgets.QRadioButton(self.planarlinkage_tab)
        self.maxTime_option.setObjectName("maxTime_option")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.maxTime_option)
        self.maxTime = QtWidgets.QWidget(self.planarlinkage_tab)
        self.maxTime.setEnabled(False)
        self.maxTime.setObjectName("maxTime")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.maxTime)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.maxTime_h = QtWidgets.QSpinBox(self.maxTime)
        self.maxTime_h.setMaximum(24)
        self.maxTime_h.setObjectName("maxTime_h")
        self.horizontalLayout_2.addWidget(self.maxTime_h)
        self.label_2 = QtWidgets.QLabel(self.maxTime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.maxTime_m = QtWidgets.QSpinBox(self.maxTime)
        self.maxTime_m.setMaximum(59)
        self.maxTime_m.setProperty("value", 15)
        self.maxTime_m.setObjectName("maxTime_m")
        self.horizontalLayout_2.addWidget(self.maxTime_m)
        self.label_3 = QtWidgets.QLabel(self.maxTime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.maxTime_s = QtWidgets.QSpinBox(self.maxTime)
        self.maxTime_s.setMaximum(59)
        self.maxTime_s.setSingleStep(10)
        self.maxTime_s.setObjectName("maxTime_s")
        self.horizontalLayout_2.addWidget(self.maxTime_s)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.maxTime)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.PLTable = QtWidgets.QTableWidget(self.planarlinkage_tab)
        self.PLTable.setObjectName("PLTable")
        self.PLTable.setColumnCount(2)
        self.PLTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.PLTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.PLTable.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.PLTable)
        self.settings_tab.addTab(self.planarlinkage_tab, "")
        self.algorithm_tab = QtWidgets.QWidget()
        self.algorithm_tab.setObjectName("algorithm_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.algorithm_tab)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.algorithm_tab)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.popSize = QtWidgets.QSpinBox(self.algorithm_tab)
        self.popSize.setMinimum(10)
        self.popSize.setMaximum(10000)
        self.popSize.setSingleStep(10)
        self.popSize.setObjectName("popSize")
        self.horizontalLayout_3.addWidget(self.popSize)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.APTable = QtWidgets.QTableWidget(self.algorithm_tab)
        self.APTable.setObjectName("APTable")
        self.APTable.setColumnCount(2)
        self.APTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.APTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.APTable.setHorizontalHeaderItem(1, item)
        self.APTable.horizontalHeader().setDefaultSectionSize(150)
        self.APTable.horizontalHeader().setMinimumSectionSize(150)
        self.verticalLayout_3.addWidget(self.APTable)
        self.settings_tab.addTab(self.algorithm_tab, "")
        self.verticalLayout.addWidget(self.settings_tab)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.setDefault = QtWidgets.QPushButton(Dialog)
        self.setDefault.setObjectName("setDefault")
        self.horizontalLayout.addWidget(self.setDefault)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.maxGen_option.toggled['bool'].connect(self.maxGen.setEnabled)
        self.minFit_option.toggled['bool'].connect(self.minFit.setEnabled)
        self.maxTime_option.toggled['bool'].connect(self.maxTime.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Options"))
        self.maxGen_option.setToolTip(_translate("Dialog", "<html><head/><body><p>This parameter determines the generations of evolution.</p><p>If the value set to 0, algorithm will stop only when you clicked the interrupt button.</p></body></html>"))
        self.maxGen_option.setText(_translate("Dialog", "Max generation: (?)"))
        self.minFit_option.setToolTip(_translate("Dialog", "<html><head/><body><p>This parameter determines the last fitness of evolution.</p><p>If the value set to 0, algorithm will stop only when you clicked the interrupt button.</p></body></html>"))
        self.minFit_option.setText(_translate("Dialog", "Minimum fitness value: (?)"))
        self.report_label.setToolTip(_translate("Dialog", "<html><head/><body><p>If the value set to 0, algorithm will report in every 10 generations.</p></body></html>"))
        self.report_label.setText(_translate("Dialog", "Report in every: (?)"))
        self.maxTime_option.setToolTip(_translate("Dialog", "<html><head/><body><p>This parameter determines the times of evolution.</p><p>If the value set to 0, algorithm will stop only when you clicked the interrupt button.</p></body></html>"))
        self.maxTime_option.setText(_translate("Dialog", "Max time: (?)"))
        self.label_2.setText(_translate("Dialog", ":"))
        self.label_3.setText(_translate("Dialog", ":"))
        item = self.PLTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter"))
        item = self.PLTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value"))
        self.settings_tab.setTabText(self.settings_tab.indexOf(self.planarlinkage_tab), _translate("Dialog", "Planar Linkage"))
        self.label.setToolTip(_translate("Dialog", "<html><head/><body><p>The greater the number will make possibilities more available, but will result in longer selection times.</p></body></html>"))
        self.label.setText(_translate("Dialog", "The first generation of the population: (?)"))
        item = self.APTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Parameter"))
        item = self.APTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Value"))
        self.settings_tab.setTabText(self.settings_tab.indexOf(self.algorithm_tab), _translate("Dialog", "Algorithm"))
        self.setDefault.setText(_translate("Dialog", "Reset to Default"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

