# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ahshoe/桌面/Pyslvs-PyQt5/core/main.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(989, 863)
        MainWindow.setMouseTracking(True)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/main_big.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MainSplitter = QtWidgets.QSplitter(self.centralWidget)
        self.MainSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.MainSplitter.setObjectName("MainSplitter")
        self.LaftSplitter = QtWidgets.QSplitter(self.MainSplitter)
        self.LaftSplitter.setMinimumSize(QtCore.QSize(450, 0))
        self.LaftSplitter.setOrientation(QtCore.Qt.Vertical)
        self.LaftSplitter.setObjectName("LaftSplitter")
        self.curveArea = QtWidgets.QWidget(self.LaftSplitter)
        self.curveArea.setObjectName("curveArea")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.curveArea)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.Panel = QtWidgets.QTabWidget(self.curveArea)
        self.Panel.setTabPosition(QtWidgets.QTabWidget.West)
        self.Panel.setObjectName("Panel")
        self.mechanism_tab = QtWidgets.QWidget()
        self.mechanism_tab.setObjectName("mechanism_tab")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.mechanism_tab)
        self.verticalLayout_27.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.MechanismPanelSplitter = QtWidgets.QSplitter(self.mechanism_tab)
        self.MechanismPanelSplitter.setOrientation(QtCore.Qt.Vertical)
        self.MechanismPanelSplitter.setObjectName("MechanismPanelSplitter")
        self.EntitiesTabWidget = QtWidgets.QWidget(self.MechanismPanelSplitter)
        self.EntitiesTabWidget.setObjectName("EntitiesTabWidget")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.EntitiesTabWidget)
        self.verticalLayout_29.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.EntitiesTab = QtWidgets.QTabWidget(self.EntitiesTabWidget)
        self.EntitiesTab.setObjectName("EntitiesTab")
        self.PointsTab = QtWidgets.QWidget()
        self.PointsTab.setObjectName("PointsTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.PointsTab)
        self.verticalLayout_9.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Entities_Point_Widget = QtWidgets.QWidget(self.PointsTab)
        self.Entities_Point_Widget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.Entities_Point_Widget.setObjectName("Entities_Point_Widget")
        self.Entities_Point_Layout = QtWidgets.QVBoxLayout(self.Entities_Point_Widget)
        self.Entities_Point_Layout.setContentsMargins(0, 0, 0, 0)
        self.Entities_Point_Layout.setObjectName("Entities_Point_Layout")
        self.verticalLayout_9.addWidget(self.Entities_Point_Widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/bearing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EntitiesTab.addTab(self.PointsTab, icon1, "")
        self.LinksTab = QtWidgets.QWidget()
        self.LinksTab.setObjectName("LinksTab")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.LinksTab)
        self.verticalLayout_19.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.Entities_Link_Widget = QtWidgets.QWidget(self.LinksTab)
        self.Entities_Link_Widget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.Entities_Link_Widget.setObjectName("Entities_Link_Widget")
        self.Entities_Link_Layout = QtWidgets.QVBoxLayout(self.Entities_Link_Widget)
        self.Entities_Link_Layout.setContentsMargins(0, 0, 0, 0)
        self.Entities_Link_Layout.setObjectName("Entities_Link_Layout")
        self.verticalLayout_19.addWidget(self.Entities_Link_Widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EntitiesTab.addTab(self.LinksTab, icon2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Expression_Widget = QtWidgets.QWidget(self.tab)
        self.Expression_Widget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.Expression_Widget.setObjectName("Expression_Widget")
        self.Expression_Layout = QtWidgets.QVBoxLayout(self.Expression_Widget)
        self.Expression_Layout.setContentsMargins(0, 0, 0, 0)
        self.Expression_Layout.setObjectName("Expression_Layout")
        self.verticalLayout_8.addWidget(self.Expression_Widget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/collection-triangular-iteration.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EntitiesTab.addTab(self.tab, icon3, "")
        self.verticalLayout_29.addWidget(self.EntitiesTab)
        self.MechanismsTabWidget = QtWidgets.QWidget(self.MechanismPanelSplitter)
        self.MechanismsTabWidget.setObjectName("MechanismsTabWidget")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.MechanismsTabWidget)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.MechanismPanelSplitterLine = QtWidgets.QFrame(self.MechanismsTabWidget)
        self.MechanismPanelSplitterLine.setLineWidth(3)
        self.MechanismPanelSplitterLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.MechanismPanelSplitterLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MechanismPanelSplitterLine.setObjectName("MechanismPanelSplitterLine")
        self.verticalLayout_21.addWidget(self.MechanismPanelSplitterLine)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.mechanism_storage_name_tag_text = QtWidgets.QLabel(self.MechanismsTabWidget)
        self.mechanism_storage_name_tag_text.setObjectName("mechanism_storage_name_tag_text")
        self.horizontalLayout_11.addWidget(self.mechanism_storage_name_tag_text)
        self.mechanism_storage_name_tag = QtWidgets.QLineEdit(self.MechanismsTabWidget)
        self.mechanism_storage_name_tag.setObjectName("mechanism_storage_name_tag")
        self.horizontalLayout_11.addWidget(self.mechanism_storage_name_tag)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.mechanism_storage = QtWidgets.QListWidget(self.MechanismsTabWidget)
        self.mechanism_storage.setObjectName("mechanism_storage")
        self.verticalLayout_4.addWidget(self.mechanism_storage)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.mechanism_storage_add = QtWidgets.QPushButton(self.MechanismsTabWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mechanism_storage_add.setIcon(icon4)
        self.mechanism_storage_add.setObjectName("mechanism_storage_add")
        self.verticalLayout_20.addWidget(self.mechanism_storage_add)
        self.mechanism_storage_restore = QtWidgets.QPushButton(self.MechanismsTabWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/dataupdate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mechanism_storage_restore.setIcon(icon5)
        self.mechanism_storage_restore.setObjectName("mechanism_storage_restore")
        self.verticalLayout_20.addWidget(self.mechanism_storage_restore)
        self.line_4 = QtWidgets.QFrame(self.MechanismsTabWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_20.addWidget(self.line_4)
        self.mechanism_storage_copy = QtWidgets.QPushButton(self.MechanismsTabWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mechanism_storage_copy.setIcon(icon6)
        self.mechanism_storage_copy.setObjectName("mechanism_storage_copy")
        self.verticalLayout_20.addWidget(self.mechanism_storage_copy)
        self.mechanism_storage_paste = QtWidgets.QPushButton(self.MechanismsTabWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mechanism_storage_paste.setIcon(icon7)
        self.mechanism_storage_paste.setObjectName("mechanism_storage_paste")
        self.verticalLayout_20.addWidget(self.mechanism_storage_paste)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem)
        self.mechanism_storage_delete = QtWidgets.QPushButton(self.MechanismsTabWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mechanism_storage_delete.setIcon(icon8)
        self.mechanism_storage_delete.setObjectName("mechanism_storage_delete")
        self.verticalLayout_20.addWidget(self.mechanism_storage_delete)
        self.horizontalLayout_9.addLayout(self.verticalLayout_20)
        self.verticalLayout_21.addLayout(self.horizontalLayout_9)
        self.verticalLayout_27.addWidget(self.MechanismPanelSplitter)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/mechanism.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Panel.addTab(self.mechanism_tab, icon9, "")
        self.inputs_tab = QtWidgets.QWidget()
        self.inputs_tab.setObjectName("inputs_tab")
        self.inputs_tab_layout = QtWidgets.QVBoxLayout(self.inputs_tab)
        self.inputs_tab_layout.setObjectName("inputs_tab_layout")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/motor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Panel.addTab(self.inputs_tab, icon10, "")
        self.synthesis_tab = QtWidgets.QWidget()
        self.synthesis_tab.setObjectName("synthesis_tab")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.synthesis_tab)
        self.verticalLayout_14.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.synthesis_splitter = QtWidgets.QSplitter(self.synthesis_tab)
        self.synthesis_splitter.setOrientation(QtCore.Qt.Vertical)
        self.synthesis_splitter.setObjectName("synthesis_splitter")
        self.SynthesisTab = QtWidgets.QTabWidget(self.synthesis_splitter)
        self.SynthesisTab.setObjectName("SynthesisTab")
        self.verticalLayout_14.addWidget(self.synthesis_splitter)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/synthesis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Panel.addTab(self.synthesis_tab, icon11, "")
        self.history_tab = QtWidgets.QWidget()
        self.history_tab.setObjectName("history_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.history_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.UndoRedoLayout = QtWidgets.QVBoxLayout()
        self.UndoRedoLayout.setObjectName("UndoRedoLayout")
        self.label_8 = QtWidgets.QLabel(self.history_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.UndoRedoLayout.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.UndoRedoLayout)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Panel.addTab(self.history_tab, icon12, "")
        self.version_control_tab = QtWidgets.QWidget()
        self.version_control_tab.setObjectName("version_control_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.version_control_tab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SCMLayout = QtWidgets.QVBoxLayout()
        self.SCMLayout.setObjectName("SCMLayout")
        self.verticalLayout_5.addLayout(self.SCMLayout)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/git.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Panel.addTab(self.version_control_tab, icon13, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.settings_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.settings_scrollarea = QtWidgets.QScrollArea(self.settings_tab)
        self.settings_scrollarea.setWidgetResizable(True)
        self.settings_scrollarea.setObjectName("settings_scrollarea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 413, 823))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.settings_ui_groupbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.settings_ui_groupbox.setObjectName("settings_ui_groupbox")
        self.formLayout = QtWidgets.QFormLayout(self.settings_ui_groupbox)
        self.formLayout.setObjectName("formLayout")
        self.linewidth_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.linewidth_label.setObjectName("linewidth_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.linewidth_label)
        self.linewidth_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.linewidth_option.setMinimum(1)
        self.linewidth_option.setMaximum(10)
        self.linewidth_option.setDisplayIntegerBase(10)
        self.linewidth_option.setObjectName("linewidth_option")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.linewidth_option)
        self.fontsize_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.fontsize_label.setObjectName("fontsize_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fontsize_label)
        self.fontsize_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.fontsize_option.setMinimum(1)
        self.fontsize_option.setMaximum(30)
        self.fontsize_option.setSingleStep(5)
        self.fontsize_option.setObjectName("fontsize_option")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fontsize_option)
        self.pathwidth_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.pathwidth_label.setObjectName("pathwidth_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pathwidth_label)
        self.pathwidth_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.pathwidth_option.setMinimum(1)
        self.pathwidth_option.setMaximum(5)
        self.pathwidth_option.setObjectName("pathwidth_option")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pathwidth_option)
        self.scalefactor_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.scalefactor_label.setObjectName("scalefactor_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.scalefactor_label)
        self.scalefactor_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.scalefactor_option.setMinimum(5)
        self.scalefactor_option.setMaximum(100)
        self.scalefactor_option.setSingleStep(5)
        self.scalefactor_option.setObjectName("scalefactor_option")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.scalefactor_option)
        self.selectionradius_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.selectionradius_label.setObjectName("selectionradius_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.selectionradius_label)
        self.selectionradius_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.selectionradius_option.setMinimum(3)
        self.selectionradius_option.setMaximum(10)
        self.selectionradius_option.setObjectName("selectionradius_option")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.selectionradius_option)
        self.linkagetransparency_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.linkagetransparency_label.setObjectName("linkagetransparency_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.linkagetransparency_label)
        self.linktrans_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.linktrans_option.setMaximum(80)
        self.linktrans_option.setSingleStep(10)
        self.linktrans_option.setObjectName("linktrans_option")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.linktrans_option)
        self.marginfactor_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.marginfactor_label.setObjectName("marginfactor_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.marginfactor_label)
        self.marginfactor_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.marginfactor_option.setMaximum(30)
        self.marginfactor_option.setSingleStep(5)
        self.marginfactor_option.setObjectName("marginfactor_option")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.marginfactor_option)
        self.jointsize_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.jointsize_label.setObjectName("jointsize_label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.jointsize_label)
        self.jointsize_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.jointsize_option.setMinimum(1)
        self.jointsize_option.setMaximum(100)
        self.jointsize_option.setObjectName("jointsize_option")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.jointsize_option)
        self.snap_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.snap_label.setObjectName("snap_label")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.snap_label)
        self.snap_option = QtWidgets.QDoubleSpinBox(self.settings_ui_groupbox)
        self.snap_option.setMaximum(50.0)
        self.snap_option.setSingleStep(0.5)
        self.snap_option.setObjectName("snap_option")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.snap_option)
        self.zoomby_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.zoomby_label.setObjectName("zoomby_label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.zoomby_label)
        self.zoomby_option = QtWidgets.QComboBox(self.settings_ui_groupbox)
        self.zoomby_option.setObjectName("zoomby_option")
        self.zoomby_option.addItem("")
        self.zoomby_option.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.zoomby_option)
        self.verticalLayout_3.addWidget(self.settings_ui_groupbox)
        self.settings_history_groupbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.settings_history_groupbox.setObjectName("settings_history_groupbox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.settings_history_groupbox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.UndoLimit_label = QtWidgets.QLabel(self.settings_history_groupbox)
        self.UndoLimit_label.setObjectName("UndoLimit_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.UndoLimit_label)
        self.undolimit_option = QtWidgets.QSpinBox(self.settings_history_groupbox)
        self.undolimit_option.setMinimum(5)
        self.undolimit_option.setObjectName("undolimit_option")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.undolimit_option)
        self.verticalLayout_3.addWidget(self.settings_history_groupbox)
        self.settings_kernels_groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.settings_kernels_groupBox.setObjectName("settings_kernels_groupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.settings_kernels_groupBox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.planarsolver_label = QtWidgets.QLabel(self.settings_kernels_groupBox)
        self.planarsolver_label.setObjectName("planarsolver_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.planarsolver_label)
        self.planarsolver_option = QtWidgets.QComboBox(self.settings_kernels_groupBox)
        self.planarsolver_option.setObjectName("planarsolver_option")
        self.planarsolver_option.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.planarsolver_option)
        self.verticalLayout_3.addWidget(self.settings_kernels_groupBox)
        self.settings_misc_groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.settings_misc_groupBox.setObjectName("settings_misc_groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.settings_misc_groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.titlefullpath_option = QtWidgets.QCheckBox(self.settings_misc_groupBox)
        self.titlefullpath_option.setObjectName("titlefullpath_option")
        self.verticalLayout_7.addWidget(self.titlefullpath_option)
        self.consoleerror_option = QtWidgets.QCheckBox(self.settings_misc_groupBox)
        self.consoleerror_option.setObjectName("consoleerror_option")
        self.verticalLayout_7.addWidget(self.consoleerror_option)
        self.verticalLayout_3.addWidget(self.settings_misc_groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 619, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dontsave_option = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.dontsave_option.setObjectName("dontsave_option")
        self.horizontalLayout.addWidget(self.dontsave_option)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.settings_scrollarea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.settings_scrollarea)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.settings_reset = QtWidgets.QPushButton(self.settings_tab)
        self.settings_reset.setObjectName("settings_reset")
        self.horizontalLayout_10.addWidget(self.settings_reset)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.version_label = QtWidgets.QLabel(self.settings_tab)
        self.version_label.setText("")
        self.version_label.setObjectName("version_label")
        self.horizontalLayout_10.addWidget(self.version_label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Panel.addTab(self.settings_tab, icon14, "")
        self.verticalLayout_31.addWidget(self.Panel)
        self.RightSplitter = QtWidgets.QSplitter(self.MainSplitter)
        self.RightSplitter.setOrientation(QtCore.Qt.Vertical)
        self.RightSplitter.setObjectName("RightSplitter")
        self.histogramArea = QtWidgets.QWidget(self.RightSplitter)
        self.histogramArea.setObjectName("histogramArea")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.histogramArea)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line = QtWidgets.QFrame(self.histogramArea)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.canvasSplitter = QtWidgets.QSplitter(self.histogramArea)
        self.canvasSplitter.setOrientation(QtCore.Qt.Vertical)
        self.canvasSplitter.setHandleWidth(3)
        self.canvasSplitter.setObjectName("canvasSplitter")
        self.BrowserWidget = QtWidgets.QWidget(self.canvasSplitter)
        self.BrowserWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.BrowserWidget.setObjectName("BrowserWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.BrowserWidget)
        self.horizontalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ZoomBar = QtWidgets.QSlider(self.BrowserWidget)
        self.ZoomBar.setMinimum(10)
        self.ZoomBar.setMaximum(2000)
        self.ZoomBar.setSingleStep(50)
        self.ZoomBar.setPageStep(50)
        self.ZoomBar.setProperty("value", 200)
        self.ZoomBar.setSliderPosition(200)
        self.ZoomBar.setOrientation(QtCore.Qt.Horizontal)
        self.ZoomBar.setInvertedControls(False)
        self.ZoomBar.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.ZoomBar.setTickInterval(100)
        self.ZoomBar.setObjectName("ZoomBar")
        self.horizontalLayout_7.addWidget(self.ZoomBar)
        self.zoom_button = QtWidgets.QPushButton(self.BrowserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom_button.sizePolicy().hasHeightForWidth())
        self.zoom_button.setSizePolicy(sizePolicy)
        self.zoom_button.setObjectName("zoom_button")
        self.horizontalLayout_7.addWidget(self.zoom_button)
        self.ResetCanvas = QtWidgets.QPushButton(self.BrowserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResetCanvas.sizePolicy().hasHeightForWidth())
        self.ResetCanvas.setSizePolicy(sizePolicy)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/BrowseAim.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ResetCanvas.setIcon(icon15)
        self.ResetCanvas.setIconSize(QtCore.QSize(32, 32))
        self.ResetCanvas.setObjectName("ResetCanvas")
        self.horizontalLayout_7.addWidget(self.ResetCanvas)
        self.freemode_button = QtWidgets.QPushButton(self.BrowserWidget)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/freemove_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.freemode_button.setIcon(icon16)
        self.freemode_button.setIconSize(QtCore.QSize(32, 32))
        self.freemode_button.setObjectName("freemode_button")
        self.horizontalLayout_7.addWidget(self.freemode_button)
        self.line_3 = QtWidgets.QFrame(self.BrowserWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_7.addWidget(self.line_3)
        self.DOFLable = QtWidgets.QLabel(self.BrowserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DOFLable.sizePolicy().hasHeightForWidth())
        self.DOFLable.setSizePolicy(sizePolicy)
        self.DOFLable.setObjectName("DOFLable")
        self.horizontalLayout_7.addWidget(self.DOFLable)
        self.DOFview = QtWidgets.QLabel(self.BrowserWidget)
        self.DOFview.setText("")
        self.DOFview.setObjectName("DOFview")
        self.horizontalLayout_7.addWidget(self.DOFview)
        self.ConflictGuide = QtWidgets.QLabel(self.BrowserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConflictGuide.sizePolicy().hasHeightForWidth())
        self.ConflictGuide.setSizePolicy(sizePolicy)
        self.ConflictGuide.setTextFormat(QtCore.Qt.RichText)
        self.ConflictGuide.setObjectName("ConflictGuide")
        self.horizontalLayout_7.addWidget(self.ConflictGuide)
        self.ConsoleWidget = QtWidgets.QWidget(self.canvasSplitter)
        self.ConsoleWidget.setObjectName("ConsoleWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.ConsoleWidget)
        self.verticalLayout_11.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.line_6 = QtWidgets.QFrame(self.ConsoleWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_11.addWidget(self.line_6)
        self.widget = QtWidgets.QWidget(self.ConsoleWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.disconnectConsoleButton = QtWidgets.QPushButton(self.widget)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/disconnect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.disconnectConsoleButton.setIcon(icon17)
        self.disconnectConsoleButton.setObjectName("disconnectConsoleButton")
        self.horizontalLayout_5.addWidget(self.disconnectConsoleButton)
        self.connectConsoleButton = QtWidgets.QPushButton(self.widget)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectConsoleButton.setIcon(icon18)
        self.connectConsoleButton.setObjectName("connectConsoleButton")
        self.horizontalLayout_5.addWidget(self.connectConsoleButton)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.clearConsole = QtWidgets.QPushButton(self.widget)
        self.clearConsole.setObjectName("clearConsole")
        self.horizontalLayout_5.addWidget(self.clearConsole)
        self.closeConsoleButton = QtWidgets.QPushButton(self.widget)
        self.closeConsoleButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.closeConsoleButton.setObjectName("closeConsoleButton")
        self.horizontalLayout_5.addWidget(self.closeConsoleButton)
        self.verticalLayout_11.addWidget(self.widget)
        self.consoleWidgetBrowser = QtWidgets.QTextBrowser(self.ConsoleWidget)
        self.consoleWidgetBrowser.setObjectName("consoleWidgetBrowser")
        self.verticalLayout_11.addWidget(self.consoleWidgetBrowser)
        self.horizontalLayout_2.addWidget(self.canvasSplitter)
        self.verticalLayout_2.addWidget(self.MainSplitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 989, 30))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setStatusTip("")
        self.menuFile.setObjectName("menuFile")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuImport = QtWidgets.QMenu(self.menuFile)
        self.menuImport.setObjectName("menuImport")
        self.menu_Mechanism = QtWidgets.QMenu(self.menuBar)
        self.menu_Mechanism.setObjectName("menu_Mechanism")
        self.menu_Options = QtWidgets.QMenu(self.menuBar)
        self.menu_Options.setObjectName("menu_Options")
        self.menu_Help = QtWidgets.QMenu(self.menuBar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_Edit = QtWidgets.QMenu(self.menuBar)
        self.menu_Edit.setObjectName("menu_Edit")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_New_Workbook = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/newfile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_New_Workbook.setIcon(icon19)
        self.action_New_Workbook.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_New_Workbook.setObjectName("action_New_Workbook")
        self.action_New_Point = QtWidgets.QAction(MainWindow)
        self.action_New_Point.setIcon(icon1)
        self.action_New_Point.setObjectName("action_New_Point")
        self.action_New_Link = QtWidgets.QAction(MainWindow)
        self.action_New_Link.setIcon(icon2)
        self.action_New_Link.setObjectName("action_New_Link")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setCheckable(False)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon20)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Get_Help = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/kmol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Get_Help.setIcon(icon21)
        self.action_Get_Help.setObjectName("action_Get_Help")
        self.action_github_repository = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_github_repository.setIcon(icon22)
        self.action_github_repository.setObjectName("action_github_repository")
        self.action_About_Pyslvs = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icons/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_About_Pyslvs.setIcon(icon23)
        self.action_About_Pyslvs.setObjectName("action_About_Pyslvs")
        self.action_Full_Screen = QtWidgets.QAction(MainWindow)
        self.action_Full_Screen.setCheckable(True)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/icons/fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Full_Screen.setIcon(icon24)
        self.action_Full_Screen.setObjectName("action_Full_Screen")
        self.action_Output_to_Picture = QtWidgets.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/icons/picture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Output_to_Picture.setIcon(icon25)
        self.action_Output_to_Picture.setObjectName("action_Output_to_Picture")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setIcon(icon13)
        self.action_Save.setPriority(QtWidgets.QAction.HighPriority)
        self.action_Save.setObjectName("action_Save")
        self.action_See_Python_Scripts = QtWidgets.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/icons/script.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_See_Python_Scripts.setIcon(icon26)
        self.action_See_Python_Scripts.setObjectName("action_See_Python_Scripts")
        self.action_Delete_Point = QtWidgets.QAction(MainWindow)
        self.action_Delete_Point.setObjectName("action_Delete_Point")
        self.action_Delete_Link = QtWidgets.QAction(MainWindow)
        self.action_Delete_Link.setObjectName("action_Delete_Link")
        self.action_Edit_Point = QtWidgets.QAction(MainWindow)
        self.action_Edit_Point.setObjectName("action_Edit_Point")
        self.action_Edit_Link = QtWidgets.QAction(MainWindow)
        self.action_Edit_Link.setObjectName("action_Edit_Link")
        self.action_Display_Dimensions = QtWidgets.QAction(MainWindow)
        self.action_Display_Dimensions.setCheckable(True)
        self.action_Display_Dimensions.setObjectName("action_Display_Dimensions")
        self.action_Display_Point_Mark = QtWidgets.QAction(MainWindow)
        self.action_Display_Point_Mark.setCheckable(True)
        self.action_Display_Point_Mark.setChecked(True)
        self.action_Display_Point_Mark.setObjectName("action_Display_Point_Mark")
        self.action_Output_to_DXF = QtWidgets.QAction(MainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/icons/dxf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Output_to_DXF.setIcon(icon27)
        self.action_Output_to_DXF.setObjectName("action_Output_to_DXF")
        self.action_Save_as = QtWidgets.QAction(MainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/icons/savefile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save_as.setIcon(icon28)
        self.action_Save_as.setObjectName("action_Save_as")
        self.action_Output_to_Solvespace = QtWidgets.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/icons/Solvespace.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Output_to_Solvespace.setIcon(icon29)
        self.action_Output_to_Solvespace.setObjectName("action_Output_to_Solvespace")
        self.SolvespaceMenuTitle = QtWidgets.QAction(MainWindow)
        self.SolvespaceMenuTitle.setEnabled(False)
        self.SolvespaceMenuTitle.setObjectName("SolvespaceMenuTitle")
        self.DXFMenuTitle = QtWidgets.QAction(MainWindow)
        self.DXFMenuTitle.setEnabled(False)
        self.DXFMenuTitle.setObjectName("DXFMenuTitle")
        self.OtherFormatMenuTitle = QtWidgets.QAction(MainWindow)
        self.OtherFormatMenuTitle.setEnabled(False)
        self.OtherFormatMenuTitle.setObjectName("OtherFormatMenuTitle")
        self.action_Import_Workbook = QtWidgets.QAction(MainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/icons/loadfile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Import_Workbook.setIcon(icon30)
        self.action_Import_Workbook.setObjectName("action_Import_Workbook")
        self.action_About_Qt = QtWidgets.QAction(MainWindow)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/icons/Logo_Qt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_About_Qt.setIcon(icon31)
        self.action_About_Qt.setObjectName("action_About_Qt")
        self.action_Load_File = QtWidgets.QAction(MainWindow)
        self.action_Load_File.setIcon(icon30)
        self.action_Load_File.setObjectName("action_Load_File")
        self.action_Zoom_to_fit = QtWidgets.QAction(MainWindow)
        self.action_Zoom_to_fit.setIcon(icon15)
        self.action_Zoom_to_fit.setObjectName("action_Zoom_to_fit")
        self.action_Path_style = QtWidgets.QAction(MainWindow)
        self.action_Path_style.setCheckable(True)
        self.action_Path_style.setChecked(True)
        self.action_Path_style.setObjectName("action_Path_style")
        self.action_Pyslvs_com = QtWidgets.QAction(MainWindow)
        self.action_Pyslvs_com.setIcon(icon)
        self.action_Pyslvs_com.setObjectName("action_Pyslvs_com")
        self.action_Show_console = QtWidgets.QAction(MainWindow)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/icons/konsole.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Show_console.setIcon(icon32)
        self.action_Show_console.setObjectName("action_Show_console")
        self.action_Output_to_PMKS = QtWidgets.QAction(MainWindow)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/icons/PMKSLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Output_to_PMKS.setIcon(icon33)
        self.action_Output_to_PMKS.setObjectName("action_Output_to_PMKS")
        self.action_Import_PMKS_server = QtWidgets.QAction(MainWindow)
        self.action_Import_PMKS_server.setIcon(icon33)
        self.action_Import_PMKS_server.setObjectName("action_Import_PMKS_server")
        self.action_Example = QtWidgets.QAction(MainWindow)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/icons/example.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Example.setIcon(icon34)
        self.action_Example.setObjectName("action_Example")
        self.action_See_Expression = QtWidgets.QAction(MainWindow)
        self.action_See_Expression.setIcon(icon26)
        self.action_See_Expression.setObjectName("action_See_Expression")
        self.action_Save_branch = QtWidgets.QAction(MainWindow)
        self.action_Save_branch.setIcon(icon13)
        self.action_Save_branch.setObjectName("action_Save_branch")
        self.action_Stash = QtWidgets.QAction(MainWindow)
        self.action_Stash.setIcon(icon8)
        self.action_Stash.setObjectName("action_Stash")
        self.action_Import_Example = QtWidgets.QAction(MainWindow)
        self.action_Import_Example.setIcon(icon34)
        self.action_Import_Example.setObjectName("action_Import_Example")
        self.action_Output_to_Picture_clipboard = QtWidgets.QAction(MainWindow)
        self.action_Output_to_Picture_clipboard.setIcon(icon25)
        self.action_Output_to_Picture_clipboard.setObjectName("action_Output_to_Picture_clipboard")
        self.action_Check_update = QtWidgets.QAction(MainWindow)
        self.action_Check_update.setObjectName("action_Check_update")
        self.menuExport.addAction(self.SolvespaceMenuTitle)
        self.menuExport.addAction(self.action_Output_to_Solvespace)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.DXFMenuTitle)
        self.menuExport.addAction(self.action_Output_to_DXF)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.OtherFormatMenuTitle)
        self.menuExport.addAction(self.action_Output_to_Picture)
        self.menuExport.addAction(self.action_Output_to_Picture_clipboard)
        self.menuExport.addAction(self.action_Output_to_PMKS)
        self.menuImport.addAction(self.action_Import_PMKS_server)
        self.menuImport.addAction(self.action_Import_Example)
        self.menuImport.addAction(self.action_Import_Workbook)
        self.menuFile.addAction(self.action_New_Workbook)
        self.menuFile.addAction(self.action_Load_File)
        self.menuFile.addAction(self.action_Example)
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_Save_branch)
        self.menuFile.addAction(self.action_Save_as)
        self.menuFile.addAction(self.action_Stash)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Full_Screen)
        self.menuFile.addAction(self.action_Exit)
        self.menu_Mechanism.addAction(self.action_New_Point)
        self.menu_Mechanism.addAction(self.action_New_Link)
        self.menu_Mechanism.addSeparator()
        self.menu_Mechanism.addAction(self.action_Edit_Point)
        self.menu_Mechanism.addAction(self.action_Edit_Link)
        self.menu_Mechanism.addSeparator()
        self.menu_Mechanism.addAction(self.action_Delete_Point)
        self.menu_Mechanism.addAction(self.action_Delete_Link)
        self.menu_Options.addAction(self.action_Show_console)
        self.menu_Options.addSeparator()
        self.menu_Options.addAction(self.action_Zoom_to_fit)
        self.menu_Options.addAction(self.action_Display_Point_Mark)
        self.menu_Options.addAction(self.action_Display_Dimensions)
        self.menu_Options.addAction(self.action_Path_style)
        self.menu_Options.addSeparator()
        self.menu_Options.addAction(self.action_See_Expression)
        self.menu_Options.addAction(self.action_See_Python_Scripts)
        self.menu_Help.addAction(self.action_Pyslvs_com)
        self.menu_Help.addAction(self.action_github_repository)
        self.menu_Help.addAction(self.action_Get_Help)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_Check_update)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_About_Qt)
        self.menu_Help.addAction(self.action_About_Pyslvs)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menu_Edit.menuAction())
        self.menuBar.addAction(self.menu_Mechanism.menuAction())
        self.menuBar.addAction(self.menu_Options.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.SynthesisTab.setCurrentIndex(-1)
        self.action_Exit.triggered.connect(MainWindow.close)
        self.action_Show_console.triggered.connect(self.ConsoleWidget.show)
        self.closeConsoleButton.clicked.connect(self.ConsoleWidget.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pyslvs - Untitled"))
        self.EntitiesTab.setTabText(self.EntitiesTab.indexOf(self.PointsTab), _translate("MainWindow", "Points"))
        self.EntitiesTab.setTabText(self.EntitiesTab.indexOf(self.LinksTab), _translate("MainWindow", "Links"))
        self.EntitiesTab.setTabText(self.EntitiesTab.indexOf(self.tab), _translate("MainWindow", "Formulas"))
        self.mechanism_storage_name_tag_text.setText(_translate("MainWindow", "Mechanism name:"))
        self.mechanism_storage_name_tag.setPlaceholderText(_translate("MainWindow", "Prototype_0"))
        self.mechanism_storage.setStatusTip(_translate("MainWindow", "All expressions of this workbook. They will be saving with database."))
        self.mechanism_storage_add.setStatusTip(_translate("MainWindow", "Capture the current expression then save to the list."))
        self.mechanism_storage_add.setText(_translate("MainWindow", "Add"))
        self.mechanism_storage_restore.setStatusTip(_translate("MainWindow", "Restore the selected expression."))
        self.mechanism_storage_restore.setText(_translate("MainWindow", "Restore"))
        self.mechanism_storage_copy.setStatusTip(_translate("MainWindow", "Copy the specified mechanism expression as string format."))
        self.mechanism_storage_copy.setText(_translate("MainWindow", "Copy"))
        self.mechanism_storage_paste.setStatusTip(_translate("MainWindow", "Append a new expression to list by string format."))
        self.mechanism_storage_paste.setText(_translate("MainWindow", "Paste"))
        self.mechanism_storage_delete.setStatusTip(_translate("MainWindow", "Delete the specified mechanism."))
        self.mechanism_storage_delete.setText(_translate("MainWindow", "Delete"))
        self.Panel.setTabText(self.Panel.indexOf(self.mechanism_tab), _translate("MainWindow", "Mechanism"))
        self.Panel.setTabText(self.Panel.indexOf(self.inputs_tab), _translate("MainWindow", "Inputs"))
        self.Panel.setTabText(self.Panel.indexOf(self.synthesis_tab), _translate("MainWindow", "Synthesis"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>This action list will build your mechanism from data base.</p><p>If you want to view the workbook history, please switch to the version control tab.</p><p>You can backtracking commands by clicking them below.</p></body></html>"))
        self.Panel.setTabText(self.Panel.indexOf(self.history_tab), _translate("MainWindow", "History"))
        self.Panel.setTabText(self.Panel.indexOf(self.version_control_tab), _translate("MainWindow", "Version Control"))
        self.settings_ui_groupbox.setTitle(_translate("MainWindow", "Main canvas"))
        self.linewidth_label.setText(_translate("MainWindow", "Line width"))
        self.fontsize_label.setText(_translate("MainWindow", "Font size"))
        self.pathwidth_label.setText(_translate("MainWindow", "Path width"))
        self.scalefactor_label.setText(_translate("MainWindow", "Scale factor"))
        self.selectionradius_label.setText(_translate("MainWindow", "Selection radius"))
        self.linkagetransparency_label.setText(_translate("MainWindow", "Linkage transparency"))
        self.linktrans_option.setSuffix(_translate("MainWindow", " %"))
        self.marginfactor_label.setText(_translate("MainWindow", "Margin of \"zoom to fit\""))
        self.marginfactor_option.setSuffix(_translate("MainWindow", "%"))
        self.jointsize_label.setText(_translate("MainWindow", "Joint annotation size (diameter)"))
        self.snap_label.setText(_translate("MainWindow", "Snap the mouse when dragging"))
        self.zoomby_label.setText(_translate("MainWindow", "Center zooming by"))
        self.zoomby_option.setItemText(0, _translate("MainWindow", "Cursor"))
        self.zoomby_option.setItemText(1, _translate("MainWindow", "Cavas center"))
        self.settings_history_groupbox.setTitle(_translate("MainWindow", "History"))
        self.UndoLimit_label.setText(_translate("MainWindow", "Undo limit"))
        self.undolimit_option.setSuffix(_translate("MainWindow", " times"))
        self.settings_kernels_groupBox.setTitle(_translate("MainWindow", "Kernels"))
        self.planarsolver_label.setText(_translate("MainWindow", "Planar solving:"))
        self.planarsolver_option.setItemText(0, _translate("MainWindow", "Python-Solvespace"))
        self.settings_misc_groupBox.setTitle(_translate("MainWindow", "Misc"))
        self.titlefullpath_option.setText(_translate("MainWindow", "Show full file path on window title."))
        self.consoleerror_option.setText(_translate("MainWindow", "Show the Solvespace error in the console."))
        self.dontsave_option.setText(_translate("MainWindow", "Do not save Pyslvs option."))
        self.settings_reset.setText(_translate("MainWindow", "Restore Defaults"))
        self.Panel.setTabText(self.Panel.indexOf(self.settings_tab), _translate("MainWindow", "Settings"))
        self.ZoomBar.setStatusTip(_translate("MainWindow", "Adjust the slider to change demo size."))
        self.zoom_button.setText(_translate("MainWindow", "200%"))
        self.ResetCanvas.setStatusTip(_translate("MainWindow", "Zoom to fit."))
        self.freemode_button.setStatusTip(_translate("MainWindow", "This mode allows all point coordinates to be edited by drag and drop."))
        self.DOFLable.setToolTip(_translate("MainWindow", "Degree of Freedom"))
        self.DOFLable.setText(_translate("MainWindow", "DOF:"))
        self.ConflictGuide.setStatusTip(_translate("MainWindow", "Show Conflict Guide tool tips."))
        self.ConflictGuide.setText(_translate("MainWindow", "<html><head/><body><p><img width=\'30\' src=\":/icons/ConflictGuide.png\"/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img width=\'30\' src=\":/icons/konsole.png\"/></p></body></html>"))
        self.disconnectConsoleButton.setStatusTip(_translate("MainWindow", "Disconnect from GUI console."))
        self.connectConsoleButton.setStatusTip(_translate("MainWindow", "Connect to GUI console."))
        self.clearConsole.setStatusTip(_translate("MainWindow", "Clear GUI console."))
        self.clearConsole.setText(_translate("MainWindow", "Clear"))
        self.closeConsoleButton.setText(_translate("MainWindow", "X"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuExport.setStatusTip(_translate("MainWindow", "Export to other format."))
        self.menuExport.setTitle(_translate("MainWindow", "E&xport"))
        self.menuImport.setTitle(_translate("MainWindow", "&Import"))
        self.menu_Mechanism.setTitle(_translate("MainWindow", "&Mechanism"))
        self.menu_Options.setTitle(_translate("MainWindow", "&Options"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.action_New_Workbook.setText(_translate("MainWindow", "&New Workbook"))
        self.action_New_Workbook.setStatusTip(_translate("MainWindow", "Reset to a new wrokbook."))
        self.action_New_Workbook.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_New_Point.setText(_translate("MainWindow", "New &Point"))
        self.action_New_Point.setStatusTip(_translate("MainWindow", "Add a new point representative of a node on a machine."))
        self.action_New_Point.setShortcut(_translate("MainWindow", "P"))
        self.action_New_Link.setText(_translate("MainWindow", "New &Linkage"))
        self.action_New_Link.setStatusTip(_translate("MainWindow", "Add  a link between two points."))
        self.action_New_Link.setShortcut(_translate("MainWindow", "L"))
        self.action_Exit.setText(_translate("MainWindow", "&Quit"))
        self.action_Exit.setStatusTip(_translate("MainWindow", "Exit Pyslvs."))
        self.action_Get_Help.setText(_translate("MainWindow", "&MDE.tw"))
        self.action_Get_Help.setStatusTip(_translate("MainWindow", "Goto Kmolab learn about more."))
        self.action_github_repository.setText(_translate("MainWindow", "Git&hub repository"))
        self.action_github_repository.setStatusTip(_translate("MainWindow", "Goto Github storage of Pyslvs."))
        self.action_About_Pyslvs.setText(_translate("MainWindow", "&About Pyslvs"))
        self.action_About_Pyslvs.setStatusTip(_translate("MainWindow", "Version and introduction of Pyslvs."))
        self.action_About_Pyslvs.setShortcut(_translate("MainWindow", "F1"))
        self.action_Full_Screen.setText(_translate("MainWindow", "Full screen"))
        self.action_Full_Screen.setStatusTip(_translate("MainWindow", "Let the window truns to full screen."))
        self.action_Full_Screen.setShortcut(_translate("MainWindow", "Shift+F1"))
        self.action_Output_to_Picture.setText(_translate("MainWindow", "&Image"))
        self.action_Output_to_Picture.setStatusTip(_translate("MainWindow", "Capture and output to image format."))
        self.action_Output_to_Picture.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.action_Save.setText(_translate("MainWindow", "Commit and &Save"))
        self.action_Save.setToolTip(_translate("MainWindow", "Save"))
        self.action_Save.setStatusTip(_translate("MainWindow", "Save the workbook."))
        self.action_Save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_See_Python_Scripts.setText(_translate("MainWindow", "Python &script"))
        self.action_See_Python_Scripts.setStatusTip(_translate("MainWindow", "Generate a Python scripts from the workbook."))
        self.action_Delete_Point.setText(_translate("MainWindow", "Delet the Point"))
        self.action_Delete_Point.setStatusTip(_translate("MainWindow", "Delete an existing point."))
        self.action_Delete_Link.setText(_translate("MainWindow", "Delet the linkage"))
        self.action_Delete_Link.setStatusTip(_translate("MainWindow", "Delete an existing linkage."))
        self.action_Edit_Point.setText(_translate("MainWindow", "Edit the point"))
        self.action_Edit_Point.setStatusTip(_translate("MainWindow", "Edit an existing point."))
        self.action_Edit_Link.setText(_translate("MainWindow", "Edit the linkage"))
        self.action_Edit_Link.setStatusTip(_translate("MainWindow", "Edit an existing linkage."))
        self.action_Display_Dimensions.setText(_translate("MainWindow", "Display &dimensions"))
        self.action_Display_Dimensions.setStatusTip(_translate("MainWindow", "Display dimensions in the canvas."))
        self.action_Display_Dimensions.setShortcut(_translate("MainWindow", "F11"))
        self.action_Display_Point_Mark.setText(_translate("MainWindow", "Display point &mark"))
        self.action_Display_Point_Mark.setStatusTip(_translate("MainWindow", "Display point mark in canvas."))
        self.action_Display_Point_Mark.setShortcut(_translate("MainWindow", "F10"))
        self.action_Output_to_DXF.setText(_translate("MainWindow", "2D sketch"))
        self.action_Output_to_DXF.setStatusTip(_translate("MainWindow", "Output to Drawing Exchange sketch."))
        self.action_Save_as.setText(_translate("MainWindow", "Save &as..."))
        self.action_Save_as.setStatusTip(_translate("MainWindow", "Save to another workbook."))
        self.action_Save_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.action_Output_to_Solvespace.setText(_translate("MainWindow", "&2D sketch"))
        self.action_Output_to_Solvespace.setStatusTip(_translate("MainWindow", "Output to Solvespace 2D sketch."))
        self.SolvespaceMenuTitle.setText(_translate("MainWindow", "Solvespace"))
        self.DXFMenuTitle.setText(_translate("MainWindow", "DXF"))
        self.OtherFormatMenuTitle.setText(_translate("MainWindow", "Other Format"))
        self.action_Import_Workbook.setText(_translate("MainWindow", "From workbook"))
        self.action_Import_Workbook.setStatusTip(_translate("MainWindow", "Import from workbook."))
        self.action_About_Qt.setText(_translate("MainWindow", "About Qt"))
        self.action_About_Qt.setStatusTip(_translate("MainWindow", "Show Qt about."))
        self.action_Load_File.setText(_translate("MainWindow", "L&oad File"))
        self.action_Load_File.setStatusTip(_translate("MainWindow", "Load Workbook from *.pyslvs database or *.slvs file."))
        self.action_Load_File.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_Zoom_to_fit.setText(_translate("MainWindow", "Zoom to fit"))
        self.action_Zoom_to_fit.setStatusTip(_translate("MainWindow", "Zoom in as mechanism size."))
        self.action_Zoom_to_fit.setShortcut(_translate("MainWindow", "Space"))
        self.action_Path_style.setText(_translate("MainWindow", "Show in solid path style"))
        self.action_Path_style.setStatusTip(_translate("MainWindow", "Show path in solid line style, otherwise will be isolated dots."))
        self.action_Pyslvs_com.setText(_translate("MainWindow", "&Pyslvs.com"))
        self.action_Pyslvs_com.setStatusTip(_translate("MainWindow", "Goto Pyslvs home page."))
        self.action_Show_console.setText(_translate("MainWindow", "Show GUI console"))
        self.action_Show_console.setStatusTip(_translate("MainWindow", "Open a widget to show console output."))
        self.action_Show_console.setShortcut(_translate("MainWindow", "F12"))
        self.action_Output_to_PMKS.setText(_translate("MainWindow", "&PMKS"))
        self.action_Output_to_PMKS.setStatusTip(_translate("MainWindow", "Pass your mechanism to PMKS server by generate a URL."))
        self.action_Import_PMKS_server.setText(_translate("MainWindow", "From PMKS server"))
        self.action_Import_PMKS_server.setStatusTip(_translate("MainWindow", "Import from PMKS URL."))
        self.action_Example.setText(_translate("MainWindow", "Example..."))
        self.action_Example.setStatusTip(_translate("MainWindow", "Load a example."))
        self.action_Example.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.action_See_Expression.setText(_translate("MainWindow", "Get expression"))
        self.action_See_Expression.setStatusTip(_translate("MainWindow", "Get the Pyslvs expression."))
        self.action_Save_branch.setText(_translate("MainWindow", "Save to new branch"))
        self.action_Save_branch.setStatusTip(_translate("MainWindow", "Creat a new branch then save the commit to this branch."))
        self.action_Stash.setText(_translate("MainWindow", "Stash"))
        self.action_Stash.setStatusTip(_translate("MainWindow", "Abandon all changes of this time, and return to the latest commit."))
        self.action_Import_Example.setText(_translate("MainWindow", "From example"))
        self.action_Import_Example.setStatusTip(_translate("MainWindow", "Import from example"))
        self.action_Output_to_Picture_clipboard.setText(_translate("MainWindow", "Image to clipboard"))
        self.action_Output_to_Picture_clipboard.setStatusTip(_translate("MainWindow", "Capture and output to clipboard."))
        self.action_Check_update.setText(_translate("MainWindow", "Check for updates"))
        self.action_Check_update.setStatusTip(_translate("MainWindow", "Check the lastest version of Pyslvs from Github."))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

