# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ahshoe/Desktop/Pyslvs-PyQt5/core/main.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1014, 780)
        MainWindow.setMinimumSize(QtCore.QSize(1014, 780))
        MainWindow.setMouseTracking(True)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/main_big.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.MainSplitter = QtWidgets.QSplitter(self.centralWidget)
        self.MainSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.MainSplitter.setHandleWidth(3)
        self.MainSplitter.setObjectName("MainSplitter")
        self.LaftSplitter = QtWidgets.QSplitter(self.MainSplitter)
        self.LaftSplitter.setMinimumSize(QtCore.QSize(450, 0))
        self.LaftSplitter.setOrientation(QtCore.Qt.Vertical)
        self.LaftSplitter.setObjectName("LaftSplitter")
        self.curveArea = QtWidgets.QWidget(self.LaftSplitter)
        self.curveArea.setObjectName("curveArea")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.curveArea)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.ToolPanel = QtWidgets.QTabWidget(self.curveArea)
        self.ToolPanel.setTabPosition(QtWidgets.QTabWidget.West)
        self.ToolPanel.setObjectName("ToolPanel")
        self.mechanism_tab = QtWidgets.QWidget()
        self.mechanism_tab.setObjectName("mechanism_tab")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.mechanism_tab)
        self.verticalLayout_27.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.ToolPanelSplitter = QtWidgets.QSplitter(self.mechanism_tab)
        self.ToolPanelSplitter.setOrientation(QtCore.Qt.Vertical)
        self.ToolPanelSplitter.setObjectName("ToolPanelSplitter")
        self.PointTabWidget = QtWidgets.QWidget(self.ToolPanelSplitter)
        self.PointTabWidget.setObjectName("PointTabWidget")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.PointTabWidget)
        self.verticalLayout_29.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.PointTab = QtWidgets.QTabWidget(self.PointTabWidget)
        self.PointTab.setObjectName("PointTab")
        self.PointsTab = QtWidgets.QWidget()
        self.PointsTab.setObjectName("PointsTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.PointsTab)
        self.verticalLayout_9.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.Entiteis_Point_Widget = QtWidgets.QWidget(self.PointsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Entiteis_Point_Widget.sizePolicy().hasHeightForWidth())
        self.Entiteis_Point_Widget.setSizePolicy(sizePolicy)
        self.Entiteis_Point_Widget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.Entiteis_Point_Widget.setObjectName("Entiteis_Point_Widget")
        self.Entiteis_Point_Layout = QtWidgets.QVBoxLayout(self.Entiteis_Point_Widget)
        self.Entiteis_Point_Layout.setContentsMargins(0, 0, 0, 0)
        self.Entiteis_Point_Layout.setObjectName("Entiteis_Point_Layout")
        self.verticalLayout_9.addWidget(self.Entiteis_Point_Widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/bearing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PointTab.addTab(self.PointsTab, icon1, "")
        self.verticalLayout_29.addWidget(self.PointTab)
        self.OptionTabWidget = QtWidgets.QWidget(self.ToolPanelSplitter)
        self.OptionTabWidget.setObjectName("OptionTabWidget")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.OptionTabWidget)
        self.verticalLayout_30.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.line_5 = QtWidgets.QFrame(self.OptionTabWidget)
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_30.addWidget(self.line_5)
        self.Entites_tab = QtWidgets.QTabWidget(self.OptionTabWidget)
        self.Entites_tab.setObjectName("Entites_tab")
        self.LinkTab = QtWidgets.QWidget()
        self.LinkTab.setObjectName("LinkTab")
        self.LinkTabLayout = QtWidgets.QVBoxLayout(self.LinkTab)
        self.LinkTabLayout.setContentsMargins(6, 6, 6, 6)
        self.LinkTabLayout.setObjectName("LinkTabLayout")
        self.Entiteis_Link_Widget = QtWidgets.QWidget(self.LinkTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Entiteis_Link_Widget.sizePolicy().hasHeightForWidth())
        self.Entiteis_Link_Widget.setSizePolicy(sizePolicy)
        self.Entiteis_Link_Widget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.Entiteis_Link_Widget.setObjectName("Entiteis_Link_Widget")
        self.Entiteis_Link_Layout = QtWidgets.QVBoxLayout(self.Entiteis_Link_Widget)
        self.Entiteis_Link_Layout.setContentsMargins(0, 0, 0, 0)
        self.Entiteis_Link_Layout.setObjectName("Entiteis_Link_Layout")
        self.LinkTabLayout.addWidget(self.Entiteis_Link_Widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Entites_tab.addTab(self.LinkTab, icon2, "")
        self.verticalLayout_30.addWidget(self.Entites_tab)
        self.verticalLayout_27.addWidget(self.ToolPanelSplitter)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/mechanism.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ToolPanel.addTab(self.mechanism_tab, icon3, "")
        self.tools_tab = QtWidgets.QWidget()
        self.tools_tab.setObjectName("tools_tab")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tools_tab)
        self.verticalLayout_14.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.tools_splitter = QtWidgets.QSplitter(self.tools_tab)
        self.tools_splitter.setOrientation(QtCore.Qt.Vertical)
        self.tools_splitter.setObjectName("tools_splitter")
        self.widget_2 = QtWidgets.QWidget(self.tools_splitter)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_20.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_23.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.Drive_shaft = QtWidgets.QPushButton(self.groupBox_3)
        self.Drive_shaft.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/motor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Drive_shaft.setIcon(icon4)
        self.Drive_shaft.setIconSize(QtCore.QSize(40, 40))
        self.Drive_shaft.setCheckable(True)
        self.Drive_shaft.setObjectName("Drive_shaft")
        self.gridLayout.addWidget(self.Drive_shaft, 1, 0, 1, 1)
        self.verticalLayout_23.addLayout(self.gridLayout)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.DimensionalSynthesisGroupBox = QtWidgets.QGroupBox(self.widget_2)
        self.DimensionalSynthesisGroupBox.setObjectName("DimensionalSynthesisGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.DimensionalSynthesisGroupBox)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.PathSolving = QtWidgets.QPushButton(self.DimensionalSynthesisGroupBox)
        self.PathSolving.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/PathSolving.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PathSolving.setIcon(icon5)
        self.PathSolving.setIconSize(QtCore.QSize(40, 40))
        self.PathSolving.setCheckable(True)
        self.PathSolving.setObjectName("PathSolving")
        self.horizontalLayout_6.addWidget(self.PathSolving)
        self.TriangleSolver = QtWidgets.QPushButton(self.DimensionalSynthesisGroupBox)
        self.TriangleSolver.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/TS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TriangleSolver.setIcon(icon6)
        self.TriangleSolver.setIconSize(QtCore.QSize(40, 40))
        self.TriangleSolver.setCheckable(True)
        self.TriangleSolver.setObjectName("TriangleSolver")
        self.horizontalLayout_6.addWidget(self.TriangleSolver)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addWidget(self.DimensionalSynthesisGroupBox, 0, 1, 1, 1)
        self.verticalLayout_28.addLayout(self.gridLayout_3)
        self.verticalLayout_20.addLayout(self.verticalLayout_28)
        spacerItem = QtWidgets.QSpacerItem(0, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem)
        self.line_4 = QtWidgets.QFrame(self.widget_2)
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_20.addWidget(self.line_4)
        self.panelWidget = QtWidgets.QTabWidget(self.tools_splitter)
        self.panelWidget.setMovable(True)
        self.panelWidget.setObjectName("panelWidget")
        self.verticalLayout_14.addWidget(self.tools_splitter)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/panel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ToolPanel.addTab(self.tools_tab, icon7, "")
        self.history_tab = QtWidgets.QWidget()
        self.history_tab.setObjectName("history_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.history_tab)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.History_tab = QtWidgets.QTabWidget(self.history_tab)
        self.History_tab.setObjectName("History_tab")
        self.undo_and_redo_tab = QtWidgets.QWidget()
        self.undo_and_redo_tab.setObjectName("undo_and_redo_tab")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.undo_and_redo_tab)
        self.verticalLayout_17.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.UndoRedoLayout = QtWidgets.QVBoxLayout()
        self.UndoRedoLayout.setObjectName("UndoRedoLayout")
        self.label_8 = QtWidgets.QLabel(self.undo_and_redo_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.UndoRedoLayout.addWidget(self.label_8)
        self.verticalLayout_17.addLayout(self.UndoRedoLayout)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.History_tab.addTab(self.undo_and_redo_tab, icon8, "")
        self.version_control_tab = QtWidgets.QWidget()
        self.version_control_tab.setObjectName("version_control_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.version_control_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.version_control_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setWordWrap(True)
        self.label_9.setOpenExternalLinks(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        spacerItem1 = QtWidgets.QSpacerItem(20, 650, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/git.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.History_tab.addTab(self.version_control_tab, icon9, "")
        self.verticalLayout.addWidget(self.History_tab)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ToolPanel.addTab(self.history_tab, icon10, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.settings_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.CanvasSettingsGroupBox = QtWidgets.QGroupBox(self.settings_tab)
        self.CanvasSettingsGroupBox.setObjectName("CanvasSettingsGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.CanvasSettingsGroupBox)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.CanvasSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.LineWidth = QtWidgets.QSpinBox(self.CanvasSettingsGroupBox)
        self.LineWidth.setMinimum(1)
        self.LineWidth.setMaximum(10)
        self.LineWidth.setProperty("value", 3)
        self.LineWidth.setDisplayIntegerBase(10)
        self.LineWidth.setObjectName("LineWidth")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineWidth)
        self.label_7 = QtWidgets.QLabel(self.CanvasSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.Font_size = QtWidgets.QSpinBox(self.CanvasSettingsGroupBox)
        self.Font_size.setMinimum(1)
        self.Font_size.setMaximum(30)
        self.Font_size.setSingleStep(5)
        self.Font_size.setProperty("value", 10)
        self.Font_size.setObjectName("Font_size")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Font_size)
        self.label_5 = QtWidgets.QLabel(self.CanvasSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.PathWidth = QtWidgets.QSpinBox(self.CanvasSettingsGroupBox)
        self.PathWidth.setMinimum(1)
        self.PathWidth.setMaximum(5)
        self.PathWidth.setProperty("value", 3)
        self.PathWidth.setObjectName("PathWidth")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PathWidth)
        self.label_6 = QtWidgets.QLabel(self.CanvasSettingsGroupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.rotateAngle = QtWidgets.QDoubleSpinBox(self.CanvasSettingsGroupBox)
        self.rotateAngle.setMaximum(360.0)
        self.rotateAngle.setSingleStep(10.0)
        self.rotateAngle.setObjectName("rotateAngle")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rotateAngle)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout_6.addWidget(self.CanvasSettingsGroupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 619, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ToolPanel.addTab(self.settings_tab, icon11, "")
        self.verticalLayout_31.addWidget(self.ToolPanel)
        self.RightSplitter = QtWidgets.QSplitter(self.MainSplitter)
        self.RightSplitter.setOrientation(QtCore.Qt.Vertical)
        self.RightSplitter.setObjectName("RightSplitter")
        self.histogramArea = QtWidgets.QWidget(self.RightSplitter)
        self.histogramArea.setObjectName("histogramArea")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.histogramArea)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line = QtWidgets.QFrame(self.histogramArea)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.canvasSplitter = QtWidgets.QSplitter(self.histogramArea)
        self.canvasSplitter.setOrientation(QtCore.Qt.Vertical)
        self.canvasSplitter.setHandleWidth(3)
        self.canvasSplitter.setObjectName("canvasSplitter")
        self.BrowserWidget = QtWidgets.QWidget(self.canvasSplitter)
        self.BrowserWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.BrowserWidget.setObjectName("BrowserWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.BrowserWidget)
        self.horizontalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ZoomBar = QtWidgets.QSlider(self.BrowserWidget)
        self.ZoomBar.setMinimum(10)
        self.ZoomBar.setMaximum(1000)
        self.ZoomBar.setSingleStep(50)
        self.ZoomBar.setPageStep(50)
        self.ZoomBar.setProperty("value", 200)
        self.ZoomBar.setSliderPosition(200)
        self.ZoomBar.setOrientation(QtCore.Qt.Horizontal)
        self.ZoomBar.setInvertedControls(False)
        self.ZoomBar.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.ZoomBar.setTickInterval(100)
        self.ZoomBar.setObjectName("ZoomBar")
        self.horizontalLayout_7.addWidget(self.ZoomBar)
        self.ZoomText = QtWidgets.QLabel(self.BrowserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZoomText.sizePolicy().hasHeightForWidth())
        self.ZoomText.setSizePolicy(sizePolicy)
        self.ZoomText.setObjectName("ZoomText")
        self.horizontalLayout_7.addWidget(self.ZoomText)
        self.ResetCanvas = QtWidgets.QPushButton(self.BrowserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResetCanvas.sizePolicy().hasHeightForWidth())
        self.ResetCanvas.setSizePolicy(sizePolicy)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/BrowseAim.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ResetCanvas.setIcon(icon12)
        self.ResetCanvas.setIconSize(QtCore.QSize(32, 32))
        self.ResetCanvas.setObjectName("ResetCanvas")
        self.horizontalLayout_7.addWidget(self.ResetCanvas)
        self.CanvasCapture = QtWidgets.QPushButton(self.BrowserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CanvasCapture.sizePolicy().hasHeightForWidth())
        self.CanvasCapture.setSizePolicy(sizePolicy)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/capture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CanvasCapture.setIcon(icon13)
        self.CanvasCapture.setIconSize(QtCore.QSize(32, 32))
        self.CanvasCapture.setObjectName("CanvasCapture")
        self.horizontalLayout_7.addWidget(self.CanvasCapture)
        self.line_3 = QtWidgets.QFrame(self.BrowserWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_7.addWidget(self.line_3)
        self.DOFLable = QtWidgets.QLabel(self.BrowserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DOFLable.sizePolicy().hasHeightForWidth())
        self.DOFLable.setSizePolicy(sizePolicy)
        self.DOFLable.setObjectName("DOFLable")
        self.horizontalLayout_7.addWidget(self.DOFLable)
        self.DOFview = QtWidgets.QLabel(self.BrowserWidget)
        self.DOFview.setText("")
        self.DOFview.setObjectName("DOFview")
        self.horizontalLayout_7.addWidget(self.DOFview)
        self.ConflictGuide = QtWidgets.QLabel(self.BrowserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConflictGuide.sizePolicy().hasHeightForWidth())
        self.ConflictGuide.setSizePolicy(sizePolicy)
        self.ConflictGuide.setTextFormat(QtCore.Qt.RichText)
        self.ConflictGuide.setObjectName("ConflictGuide")
        self.horizontalLayout_7.addWidget(self.ConflictGuide)
        self.ConsoleWidget = QtWidgets.QWidget(self.canvasSplitter)
        self.ConsoleWidget.setObjectName("ConsoleWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.ConsoleWidget)
        self.verticalLayout_11.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.line_6 = QtWidgets.QFrame(self.ConsoleWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_11.addWidget(self.line_6)
        self.widget = QtWidgets.QWidget(self.ConsoleWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.disconnectConsoleButton = QtWidgets.QPushButton(self.widget)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/disconnect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.disconnectConsoleButton.setIcon(icon14)
        self.disconnectConsoleButton.setObjectName("disconnectConsoleButton")
        self.horizontalLayout_5.addWidget(self.disconnectConsoleButton)
        self.connectConsoleButton = QtWidgets.QPushButton(self.widget)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectConsoleButton.setIcon(icon15)
        self.connectConsoleButton.setObjectName("connectConsoleButton")
        self.horizontalLayout_5.addWidget(self.connectConsoleButton)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.clearConsole = QtWidgets.QPushButton(self.widget)
        self.clearConsole.setObjectName("clearConsole")
        self.horizontalLayout_5.addWidget(self.clearConsole)
        self.closeConsoleButton = QtWidgets.QPushButton(self.widget)
        self.closeConsoleButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.closeConsoleButton.setObjectName("closeConsoleButton")
        self.horizontalLayout_5.addWidget(self.closeConsoleButton)
        self.verticalLayout_11.addWidget(self.widget)
        self.consoleWidgetBrowser = QtWidgets.QTextBrowser(self.ConsoleWidget)
        self.consoleWidgetBrowser.setObjectName("consoleWidgetBrowser")
        self.verticalLayout_11.addWidget(self.consoleWidgetBrowser)
        self.horizontalLayout_2.addWidget(self.canvasSplitter)
        self.verticalLayout_2.addWidget(self.MainSplitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1014, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setStatusTip("")
        self.menuFile.setObjectName("menuFile")
        self.menuExample = QtWidgets.QMenu(self.menuFile)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuExample.setIcon(icon16)
        self.menuExample.setObjectName("menuExample")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuImport = QtWidgets.QMenu(self.menuFile)
        self.menuImport.setObjectName("menuImport")
        self.menu_Draw = QtWidgets.QMenu(self.menuBar)
        self.menu_Draw.setObjectName("menu_Draw")
        self.menu_Options = QtWidgets.QMenu(self.menuBar)
        self.menu_Options.setObjectName("menu_Options")
        self.menu_Help = QtWidgets.QMenu(self.menuBar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_Path = QtWidgets.QMenu(self.menuBar)
        self.menu_Path.setObjectName("menu_Path")
        self.menu_Edit = QtWidgets.QMenu(self.menuBar)
        self.menu_Edit.setObjectName("menu_Edit")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_New_Workbook = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/newfile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_New_Workbook.setIcon(icon17)
        self.action_New_Workbook.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_New_Workbook.setObjectName("action_New_Workbook")
        self.action_New_Point = QtWidgets.QAction(MainWindow)
        self.action_New_Point.setIcon(icon1)
        self.action_New_Point.setObjectName("action_New_Point")
        self.action_New_Line = QtWidgets.QAction(MainWindow)
        self.action_New_Line.setIcon(icon2)
        self.action_New_Line.setObjectName("action_New_Line")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setCheckable(False)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon18)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Get_Help = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/kmol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Get_Help.setIcon(icon19)
        self.action_Get_Help.setObjectName("action_Get_Help")
        self.action_Git_hub_Site = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Git_hub_Site.setIcon(icon20)
        self.action_Git_hub_Site.setObjectName("action_Git_hub_Site")
        self.action_About_Pyslvs = QtWidgets.QAction(MainWindow)
        self.action_About_Pyslvs.setIcon(icon16)
        self.action_About_Pyslvs.setObjectName("action_About_Pyslvs")
        self.action_Minimized = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/minmized.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Minimized.setIcon(icon21)
        self.action_Minimized.setObjectName("action_Minimized")
        self.action_Maxmized = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons/maxmized.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Maxmized.setIcon(icon22)
        self.action_Maxmized.setObjectName("action_Maxmized")
        self.action_Full_Screen = QtWidgets.QAction(MainWindow)
        self.action_Full_Screen.setCheckable(False)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icons/fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Full_Screen.setIcon(icon23)
        self.action_Full_Screen.setObjectName("action_Full_Screen")
        self.action_Normal_sized = QtWidgets.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/icons/normalsized.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Normal_sized.setIcon(icon24)
        self.action_Normal_sized.setObjectName("action_Normal_sized")
        self.action_Output_to_Picture = QtWidgets.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/icons/picture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Output_to_Picture.setIcon(icon25)
        self.action_Output_to_Picture.setObjectName("action_Output_to_Picture")
        self.action_Save = QtWidgets.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/icons/savefile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save.setIcon(icon26)
        self.action_Save.setPriority(QtWidgets.QAction.HighPriority)
        self.action_Save.setObjectName("action_Save")
        self.action_See_Python_Scripts = QtWidgets.QAction(MainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/icons/script.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_See_Python_Scripts.setIcon(icon27)
        self.action_See_Python_Scripts.setObjectName("action_See_Python_Scripts")
        self.action_Delete_Point = QtWidgets.QAction(MainWindow)
        self.action_Delete_Point.setObjectName("action_Delete_Point")
        self.action_Delete_Linkage = QtWidgets.QAction(MainWindow)
        self.action_Delete_Linkage.setObjectName("action_Delete_Linkage")
        self.action_Edit_Point = QtWidgets.QAction(MainWindow)
        self.action_Edit_Point.setObjectName("action_Edit_Point")
        self.action_Edit_Linkage = QtWidgets.QAction(MainWindow)
        self.action_Edit_Linkage.setObjectName("action_Edit_Linkage")
        self.action_Display_Dimensions = QtWidgets.QAction(MainWindow)
        self.action_Display_Dimensions.setCheckable(True)
        self.action_Display_Dimensions.setObjectName("action_Display_Dimensions")
        self.action_Display_Point_Mark = QtWidgets.QAction(MainWindow)
        self.action_Display_Point_Mark.setCheckable(True)
        self.action_Display_Point_Mark.setChecked(True)
        self.action_Display_Point_Mark.setObjectName("action_Display_Point_Mark")
        self.action_Output_to_Solvespace = QtWidgets.QAction(MainWindow)
        self.action_Output_to_Solvespace.setEnabled(False)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/icons/Solvespace.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Output_to_Solvespace.setIcon(icon28)
        self.action_Output_to_Solvespace.setObjectName("action_Output_to_Solvespace")
        self.action_DXF_2D_sketch = QtWidgets.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/icons/dxf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_DXF_2D_sketch.setIcon(icon29)
        self.action_DXF_2D_sketch.setObjectName("action_DXF_2D_sketch")
        self.action_Property = QtWidgets.QAction(MainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/icons/properties.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Property.setIcon(icon30)
        self.action_Property.setObjectName("action_Property")
        self.action_Crank_rocker = QtWidgets.QAction(MainWindow)
        self.action_Crank_rocker.setObjectName("action_Crank_rocker")
        self.action_Multiple_Link = QtWidgets.QAction(MainWindow)
        self.action_Multiple_Link.setObjectName("action_Multiple_Link")
        self.action_Save_as = QtWidgets.QAction(MainWindow)
        self.action_Save_as.setIcon(icon26)
        self.action_Save_as.setObjectName("action_Save_as")
        self.action_Two_Multiple_Link = QtWidgets.QAction(MainWindow)
        self.action_Two_Multiple_Link.setObjectName("action_Two_Multiple_Link")
        self.action_Drag_link = QtWidgets.QAction(MainWindow)
        self.action_Drag_link.setObjectName("action_Drag_link")
        self.action_Double_rocker = QtWidgets.QAction(MainWindow)
        self.action_Double_rocker.setObjectName("action_Double_rocker")
        self.action_Parallelogram_linkage = QtWidgets.QAction(MainWindow)
        self.action_Parallelogram_linkage.setObjectName("action_Parallelogram_linkage")
        self.action_Reverse_Parsing_Rocker = QtWidgets.QAction(MainWindow)
        self.action_Reverse_Parsing_Rocker.setObjectName("action_Reverse_Parsing_Rocker")
        self.action_Batch_moving = QtWidgets.QAction(MainWindow)
        self.action_Batch_moving.setObjectName("action_Batch_moving")
        self.action_Slider_and_Rod = QtWidgets.QAction(MainWindow)
        self.action_Slider_and_Rod.setObjectName("action_Slider_and_Rod")
        self.action_Solvespace_2D_sketch = QtWidgets.QAction(MainWindow)
        self.action_Solvespace_2D_sketch.setIcon(icon28)
        self.action_Solvespace_2D_sketch.setObjectName("action_Solvespace_2D_sketch")
        self.action_DXF_2D_models = QtWidgets.QAction(MainWindow)
        self.action_DXF_2D_models.setIcon(icon29)
        self.action_DXF_2D_models.setObjectName("action_DXF_2D_models")
        self.action_Rock_Slider = QtWidgets.QAction(MainWindow)
        self.action_Rock_Slider.setObjectName("action_Rock_Slider")
        self.action_Lift_Tailgate = QtWidgets.QAction(MainWindow)
        self.action_Lift_Tailgate.setObjectName("action_Lift_Tailgate")
        self.GrashofChainMenuTitle = QtWidgets.QAction(MainWindow)
        self.GrashofChainMenuTitle.setEnabled(False)
        self.GrashofChainMenuTitle.setObjectName("GrashofChainMenuTitle")
        self.LinkagesMenuTitle = QtWidgets.QAction(MainWindow)
        self.LinkagesMenuTitle.setEnabled(False)
        self.LinkagesMenuTitle.setObjectName("LinkagesMenuTitle")
        self.SlidersMenuTitle = QtWidgets.QAction(MainWindow)
        self.SlidersMenuTitle.setEnabled(False)
        self.SlidersMenuTitle.setObjectName("SlidersMenuTitle")
        self.DesignsMenuTitle = QtWidgets.QAction(MainWindow)
        self.DesignsMenuTitle.setEnabled(False)
        self.DesignsMenuTitle.setObjectName("DesignsMenuTitle")
        self.action_Theo_Jansen_s_multi_linkage = QtWidgets.QAction(MainWindow)
        self.action_Theo_Jansen_s_multi_linkage.setObjectName("action_Theo_Jansen_s_multi_linkage")
        self.SolvespaceMenuTitle = QtWidgets.QAction(MainWindow)
        self.SolvespaceMenuTitle.setEnabled(False)
        self.SolvespaceMenuTitle.setObjectName("SolvespaceMenuTitle")
        self.DXFMenuTitle = QtWidgets.QAction(MainWindow)
        self.DXFMenuTitle.setEnabled(False)
        self.DXFMenuTitle.setObjectName("DXFMenuTitle")
        self.OtherFormatMenuTitle = QtWidgets.QAction(MainWindow)
        self.OtherFormatMenuTitle.setEnabled(False)
        self.OtherFormatMenuTitle.setObjectName("OtherFormatMenuTitle")
        self.action_Rock_Slider_Design = QtWidgets.QAction(MainWindow)
        self.action_Rock_Slider_Design.setObjectName("action_Rock_Slider_Design")
        self.action_Import_From_Workbook = QtWidgets.QAction(MainWindow)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/icons/loadfile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Import_From_Workbook.setIcon(icon31)
        self.action_Import_From_Workbook.setObjectName("action_Import_From_Workbook")
        self.action_About_Qt = QtWidgets.QAction(MainWindow)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/icons/Logo_Qt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_About_Qt.setIcon(icon32)
        self.action_About_Qt.setObjectName("action_About_Qt")
        self.action_Four_bar_linkage = QtWidgets.QAction(MainWindow)
        self.action_Four_bar_linkage.setObjectName("action_Four_bar_linkage")
        self.action_Load_Workbook = QtWidgets.QAction(MainWindow)
        self.action_Load_Workbook.setIcon(icon31)
        self.action_Load_Workbook.setObjectName("action_Load_Workbook")
        self.action_Zoom_to_fit = QtWidgets.QAction(MainWindow)
        self.action_Zoom_to_fit.setIcon(icon12)
        self.action_Zoom_to_fit.setObjectName("action_Zoom_to_fit")
        self.action_Path_Track = QtWidgets.QAction(MainWindow)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/icons/PathTrack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Path_Track.setIcon(icon33)
        self.action_Path_Track.setObjectName("action_Path_Track")
        self.action_Path_Clear = QtWidgets.QAction(MainWindow)
        self.action_Path_Clear.setObjectName("action_Path_Clear")
        self.action_Path_coordinate = QtWidgets.QAction(MainWindow)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/icons/data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Path_coordinate.setIcon(icon34)
        self.action_Path_coordinate.setObjectName("action_Path_coordinate")
        self.action_Path_data_show = QtWidgets.QAction(MainWindow)
        self.action_Path_data_show.setCheckable(True)
        self.action_Path_data_show.setChecked(True)
        self.action_Path_data_show.setObjectName("action_Path_data_show")
        self.action_Save_path_only = QtWidgets.QAction(MainWindow)
        self.action_Save_path_only.setIcon(icon26)
        self.action_Save_path_only.setObjectName("action_Save_path_only")
        self.AlgorithmMenuTitle = QtWidgets.QAction(MainWindow)
        self.AlgorithmMenuTitle.setEnabled(False)
        self.AlgorithmMenuTitle.setObjectName("AlgorithmMenuTitle")
        self.action_Three_Algorithm_Result = QtWidgets.QAction(MainWindow)
        self.action_Three_Algorithm_Result.setObjectName("action_Three_Algorithm_Result")
        self.action_Path_style = QtWidgets.QAction(MainWindow)
        self.action_Path_style.setCheckable(True)
        self.action_Path_style.setChecked(True)
        self.action_Path_style.setObjectName("action_Path_style")
        self.action_Pyslvs_com = QtWidgets.QAction(MainWindow)
        self.action_Pyslvs_com.setIcon(icon)
        self.action_Pyslvs_com.setObjectName("action_Pyslvs_com")
        self.action_Show_console = QtWidgets.QAction(MainWindow)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/icons/konsole.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Show_console.setIcon(icon35)
        self.action_Show_console.setObjectName("action_Show_console")
        self.menuExample.addAction(self.GrashofChainMenuTitle)
        self.menuExample.addAction(self.action_Crank_rocker)
        self.menuExample.addAction(self.action_Drag_link)
        self.menuExample.addAction(self.action_Double_rocker)
        self.menuExample.addAction(self.action_Parallelogram_linkage)
        self.menuExample.addSeparator()
        self.menuExample.addAction(self.LinkagesMenuTitle)
        self.menuExample.addAction(self.action_Multiple_Link)
        self.menuExample.addAction(self.action_Two_Multiple_Link)
        self.menuExample.addAction(self.action_Four_bar_linkage)
        self.menuExample.addSeparator()
        self.menuExample.addAction(self.SlidersMenuTitle)
        self.menuExample.addAction(self.action_Slider_and_Rod)
        self.menuExample.addAction(self.action_Rock_Slider)
        self.menuExample.addAction(self.action_Lift_Tailgate)
        self.menuExample.addSeparator()
        self.menuExample.addAction(self.DesignsMenuTitle)
        self.menuExample.addAction(self.action_Theo_Jansen_s_multi_linkage)
        self.menuExample.addAction(self.action_Rock_Slider_Design)
        self.menuExample.addSeparator()
        self.menuExample.addAction(self.AlgorithmMenuTitle)
        self.menuExample.addAction(self.action_Reverse_Parsing_Rocker)
        self.menuExample.addAction(self.action_Three_Algorithm_Result)
        self.menuExport.addAction(self.SolvespaceMenuTitle)
        self.menuExport.addAction(self.action_Output_to_Solvespace)
        self.menuExport.addAction(self.action_Solvespace_2D_sketch)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.DXFMenuTitle)
        self.menuExport.addAction(self.action_DXF_2D_models)
        self.menuExport.addAction(self.action_DXF_2D_sketch)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.OtherFormatMenuTitle)
        self.menuExport.addAction(self.action_Output_to_Picture)
        self.menuImport.addAction(self.action_Import_From_Workbook)
        self.menuFile.addAction(self.action_New_Workbook)
        self.menuFile.addAction(self.action_Load_Workbook)
        self.menuFile.addAction(self.menuExample.menuAction())
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_Save_as)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Minimized)
        self.menuFile.addAction(self.action_Maxmized)
        self.menuFile.addAction(self.action_Normal_sized)
        self.menuFile.addAction(self.action_Full_Screen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Exit)
        self.menu_Draw.addAction(self.action_New_Point)
        self.menu_Draw.addAction(self.action_New_Line)
        self.menu_Draw.addSeparator()
        self.menu_Draw.addAction(self.action_Edit_Point)
        self.menu_Draw.addAction(self.action_Edit_Linkage)
        self.menu_Draw.addSeparator()
        self.menu_Draw.addAction(self.action_Delete_Point)
        self.menu_Draw.addAction(self.action_Delete_Linkage)
        self.menu_Options.addAction(self.action_Show_console)
        self.menu_Options.addSeparator()
        self.menu_Options.addAction(self.action_Zoom_to_fit)
        self.menu_Options.addAction(self.action_Display_Point_Mark)
        self.menu_Options.addAction(self.action_Display_Dimensions)
        self.menu_Options.addSeparator()
        self.menu_Options.addAction(self.action_See_Python_Scripts)
        self.menu_Options.addAction(self.action_Property)
        self.menu_Help.addAction(self.action_Pyslvs_com)
        self.menu_Help.addAction(self.action_Git_hub_Site)
        self.menu_Help.addAction(self.action_Get_Help)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_About_Pyslvs)
        self.menu_Help.addAction(self.action_About_Qt)
        self.menu_Path.addAction(self.action_Path_Track)
        self.menu_Path.addAction(self.action_Path_coordinate)
        self.menu_Path.addAction(self.action_Save_path_only)
        self.menu_Path.addSeparator()
        self.menu_Path.addAction(self.action_Path_data_show)
        self.menu_Path.addAction(self.action_Path_style)
        self.menu_Path.addSeparator()
        self.menu_Path.addAction(self.action_Path_Clear)
        self.menu_Edit.addAction(self.action_Batch_moving)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menu_Edit.menuAction())
        self.menuBar.addAction(self.menu_Draw.menuAction())
        self.menuBar.addAction(self.menu_Path.menuAction())
        self.menuBar.addAction(self.menu_Options.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.ToolPanel.setCurrentIndex(0)
        self.PointTab.setCurrentIndex(0)
        self.Entites_tab.setCurrentIndex(0)
        self.panelWidget.setCurrentIndex(-1)
        self.History_tab.setCurrentIndex(0)
        self.action_Maxmized.triggered.connect(MainWindow.showMaximized)
        self.action_Minimized.triggered.connect(MainWindow.showMinimized)
        self.action_Full_Screen.triggered.connect(MainWindow.showFullScreen)
        self.action_Normal_sized.triggered.connect(MainWindow.showNormal)
        self.action_Exit.triggered.connect(MainWindow.close)
        self.action_Show_console.triggered.connect(self.ConsoleWidget.show)
        self.closeConsoleButton.clicked.connect(self.ConsoleWidget.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pyslvs - [New Workbook]"))
        self.PointTab.setTabText(self.PointTab.indexOf(self.PointsTab), _translate("MainWindow", "Points"))
        self.Entiteis_Link_Widget.setStatusTip(_translate("MainWindow", "All Links in this workbook. Needs two point."))
        self.Entites_tab.setTabText(self.Entites_tab.indexOf(self.LinkTab), _translate("MainWindow", "Link"))
        self.ToolPanel.setTabText(self.ToolPanel.indexOf(self.mechanism_tab), _translate("MainWindow", "Mechanism"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Drivers"))
        self.Drive_shaft.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Drive Shaft</span></p><p><span style=\" font-size:10pt;\">Drive the selected drive shaft.<br/></span><img src=\":/icons/tooltips/DriveShaft.png\"/></p><p><span style=\" font-size:10pt;\">The solving problem occurs when the drive shaft is interfering at some angle.</span></p></body></html>"))
        self.Drive_shaft.setStatusTip(_translate("MainWindow", "Drive the selected drive shaft."))
        self.DimensionalSynthesisGroupBox.setTitle(_translate("MainWindow", "Dimensional synthesis"))
        self.PathSolving.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Path Solving</span></p><p><span style=\" font-size:10pt;\">This generator will design a crank rocker to meet this path requirement.</span></p><p><img src=\":/icons/tooltips/PathSolving.png\"/></p><p><span style=\" font-size:10pt;\">There may be some interference problems in the solution of faster convergence.</span></p></body></html>"))
        self.PathSolving.setStatusTip(_translate("MainWindow", "This generator will design a crank rocker to meet this path requirement."))
        self.TriangleSolver.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Triangle Solver</span></p><p><span style=\" font-size:10pt;\">Use Solver to calculate the reference points of your mechanism.</span><img src=\":/icons/tooltips/TS.png\"/></p><p><span style=\" font-size:10pt;\">You must manually adjust the stacking method.</span></p></body></html>"))
        self.TriangleSolver.setStatusTip(_translate("MainWindow", "Use Solver to calculate the reference points of your mechanism."))
        self.ToolPanel.setTabText(self.ToolPanel.indexOf(self.tools_tab), _translate("MainWindow", "Tools"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>All changes in <span style=\" font-weight:600;\">this edition</span> will show here.</p><p>You can backtracking commands by clicking them below.</p></body></html>"))
        self.History_tab.setTabText(self.History_tab.indexOf(self.undo_and_redo_tab), _translate("MainWindow", "Undo and Redo"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Welcome to the <span style=\" font-weight:600;\">Git version management system</span>, where you can save your changes every time.</p><p>You can pull out the branch from the selected annotation, tag it, or go back to the edit history.</p><p><a href=\"https://en.wikipedia.org/wiki/Git\"><span style=\" text-decoration: underline; color:#2980b9;\">What is Git?</span></a></p></body></html>"))
        self.History_tab.setTabText(self.History_tab.indexOf(self.version_control_tab), _translate("MainWindow", "Version Control"))
        self.ToolPanel.setTabText(self.ToolPanel.indexOf(self.history_tab), _translate("MainWindow", "History"))
        self.CanvasSettingsGroupBox.setTitle(_translate("MainWindow", "Canvas settings"))
        self.label_4.setText(_translate("MainWindow", "Line width"))
        self.label_7.setText(_translate("MainWindow", "Font size"))
        self.label_5.setText(_translate("MainWindow", "Path width"))
        self.label_6.setText(_translate("MainWindow", "Rotate"))
        self.rotateAngle.setSuffix(_translate("MainWindow", "°"))
        self.ToolPanel.setTabText(self.ToolPanel.indexOf(self.settings_tab), _translate("MainWindow", "Settings"))
        self.ZoomBar.setStatusTip(_translate("MainWindow", "Adjust the slider to change demo size."))
        self.ZoomText.setText(_translate("MainWindow", "200%"))
        self.ResetCanvas.setStatusTip(_translate("MainWindow", "Zoom to fit."))
        self.CanvasCapture.setStatusTip(_translate("MainWindow", "Make a canvas capture to the clipboard."))
        self.DOFLable.setText(_translate("MainWindow", "DOF:"))
        self.ConflictGuide.setStatusTip(_translate("MainWindow", "Show Conflict Guide tool tips."))
        self.ConflictGuide.setText(_translate("MainWindow", "<html><head/><body><p><img width=\'30\' src=\":/icons/ConflictGuide.png\"/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img width=\'30\' src=\":/icons/konsole.png\"/></p></body></html>"))
        self.disconnectConsoleButton.setStatusTip(_translate("MainWindow", "Disconnect from GUI console."))
        self.connectConsoleButton.setStatusTip(_translate("MainWindow", "Connect to GUI console."))
        self.clearConsole.setStatusTip(_translate("MainWindow", "Clear GUI console."))
        self.clearConsole.setText(_translate("MainWindow", "Clear"))
        self.closeConsoleButton.setText(_translate("MainWindow", "X"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuExample.setStatusTip(_translate("MainWindow", "Some example of the Linkage mechanism."))
        self.menuExample.setTitle(_translate("MainWindow", "Example"))
        self.menuExport.setStatusTip(_translate("MainWindow", "Export to other format."))
        self.menuExport.setTitle(_translate("MainWindow", "E&xport"))
        self.menuImport.setTitle(_translate("MainWindow", "&Import"))
        self.menu_Draw.setTitle(_translate("MainWindow", "&Mechanism"))
        self.menu_Options.setTitle(_translate("MainWindow", "&Options"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.menu_Path.setTitle(_translate("MainWindow", "&Path"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.action_New_Workbook.setText(_translate("MainWindow", "&New Workbook"))
        self.action_New_Workbook.setStatusTip(_translate("MainWindow", "Reset to a new wrokbook."))
        self.action_New_Workbook.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_New_Point.setText(_translate("MainWindow", "New &point"))
        self.action_New_Point.setStatusTip(_translate("MainWindow", "Add a new point representative of a node on a machine."))
        self.action_New_Point.setShortcut(_translate("MainWindow", "F2"))
        self.action_New_Line.setText(_translate("MainWindow", "New &Linkage"))
        self.action_New_Line.setStatusTip(_translate("MainWindow", "Add  a link between two points."))
        self.action_New_Line.setShortcut(_translate("MainWindow", "F3"))
        self.action_Exit.setText(_translate("MainWindow", "&Quit"))
        self.action_Exit.setStatusTip(_translate("MainWindow", "Exit Pyslvs."))
        self.action_Exit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_Get_Help.setText(_translate("MainWindow", "&MDE.tw"))
        self.action_Get_Help.setStatusTip(_translate("MainWindow", "Goto Kmolab learn about more."))
        self.action_Git_hub_Site.setText(_translate("MainWindow", "Git&hub repository"))
        self.action_Git_hub_Site.setStatusTip(_translate("MainWindow", "Goto Github storage of Pyslvs."))
        self.action_About_Pyslvs.setText(_translate("MainWindow", "&About Pyslvs"))
        self.action_About_Pyslvs.setStatusTip(_translate("MainWindow", "Version and introduction of Pyslvs."))
        self.action_About_Pyslvs.setShortcut(_translate("MainWindow", "F1"))
        self.action_Minimized.setText(_translate("MainWindow", "Minimized"))
        self.action_Minimized.setStatusTip(_translate("MainWindow", "Minimized the window."))
        self.action_Maxmized.setText(_translate("MainWindow", "Maxmized"))
        self.action_Maxmized.setStatusTip(_translate("MainWindow", "Maxmized the window."))
        self.action_Full_Screen.setText(_translate("MainWindow", "Full Screen"))
        self.action_Full_Screen.setStatusTip(_translate("MainWindow", "Let the window truns to full screen."))
        self.action_Full_Screen.setShortcut(_translate("MainWindow", "Shift+F1"))
        self.action_Normal_sized.setText(_translate("MainWindow", "Normal sized"))
        self.action_Normal_sized.setStatusTip(_translate("MainWindow", "Let the window back to normal."))
        self.action_Normal_sized.setShortcut(_translate("MainWindow", "Shift+F2"))
        self.action_Output_to_Picture.setText(_translate("MainWindow", "&Image"))
        self.action_Output_to_Picture.setStatusTip(_translate("MainWindow", "Capture and output to Image format."))
        self.action_Output_to_Picture.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.action_Save.setText(_translate("MainWindow", "&Save"))
        self.action_Save.setToolTip(_translate("MainWindow", "Save"))
        self.action_Save.setStatusTip(_translate("MainWindow", "Save the workbook."))
        self.action_Save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_See_Python_Scripts.setText(_translate("MainWindow", "Python &script"))
        self.action_See_Python_Scripts.setStatusTip(_translate("MainWindow", "Generate a Python scripts from the workbook."))
        self.action_Delete_Point.setText(_translate("MainWindow", "Delet the Point"))
        self.action_Delete_Point.setStatusTip(_translate("MainWindow", "Delete an existing point."))
        self.action_Delete_Linkage.setText(_translate("MainWindow", "Delet the linkage"))
        self.action_Delete_Linkage.setStatusTip(_translate("MainWindow", "Delete an existing linkage."))
        self.action_Edit_Point.setText(_translate("MainWindow", "Edit the point"))
        self.action_Edit_Point.setStatusTip(_translate("MainWindow", "Edit an existing point."))
        self.action_Edit_Linkage.setText(_translate("MainWindow", "Edit the linkage"))
        self.action_Edit_Linkage.setStatusTip(_translate("MainWindow", "Edit an existing linkage."))
        self.action_Display_Dimensions.setText(_translate("MainWindow", "Display &dimensions"))
        self.action_Display_Dimensions.setStatusTip(_translate("MainWindow", "Display dimensions in the canvas."))
        self.action_Display_Dimensions.setShortcut(_translate("MainWindow", "F11"))
        self.action_Display_Point_Mark.setText(_translate("MainWindow", "Display point &mark"))
        self.action_Display_Point_Mark.setStatusTip(_translate("MainWindow", "Display point mark in canvas."))
        self.action_Display_Point_Mark.setShortcut(_translate("MainWindow", "F10"))
        self.action_Output_to_Solvespace.setText(_translate("MainWindow", "&3D models"))
        self.action_Output_to_Solvespace.setToolTip(_translate("MainWindow", "Solvespace 3D models"))
        self.action_Output_to_Solvespace.setStatusTip(_translate("MainWindow", "Output to Solvespace 3D models."))
        self.action_Output_to_Solvespace.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.action_DXF_2D_sketch.setText(_translate("MainWindow", "2D sketch"))
        self.action_DXF_2D_sketch.setStatusTip(_translate("MainWindow", "Output to Drawing Exchange sketch."))
        self.action_DXF_2D_sketch.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.action_Property.setText(_translate("MainWindow", "&Properties"))
        self.action_Property.setStatusTip(_translate("MainWindow", "Properies of this workbook."))
        self.action_Property.setShortcut(_translate("MainWindow", "`"))
        self.action_Crank_rocker.setText(_translate("MainWindow", "Crank rocker"))
        self.action_Crank_rocker.setStatusTip(_translate("MainWindow", "Grashof chain #1"))
        self.action_Multiple_Link.setText(_translate("MainWindow", "Multiple linkage"))
        self.action_Multiple_Link.setStatusTip(_translate("MainWindow", "Linkage #1"))
        self.action_Save_as.setText(_translate("MainWindow", "Save &as..."))
        self.action_Save_as.setStatusTip(_translate("MainWindow", "Save to another workbook."))
        self.action_Save_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.action_Two_Multiple_Link.setText(_translate("MainWindow", "Two pairs multiple linkage"))
        self.action_Two_Multiple_Link.setStatusTip(_translate("MainWindow", "Linkage #2"))
        self.action_Drag_link.setText(_translate("MainWindow", "Drag-link"))
        self.action_Drag_link.setStatusTip(_translate("MainWindow", "Grashof chain #2"))
        self.action_Double_rocker.setText(_translate("MainWindow", "Double rocker"))
        self.action_Double_rocker.setStatusTip(_translate("MainWindow", "Grashof chain #3"))
        self.action_Parallelogram_linkage.setText(_translate("MainWindow", "Parallelogram linkage"))
        self.action_Parallelogram_linkage.setStatusTip(_translate("MainWindow", "Grashof chain #4"))
        self.action_Reverse_Parsing_Rocker.setText(_translate("MainWindow", "Reverse Parsing Rocker"))
        self.action_Reverse_Parsing_Rocker.setStatusTip(_translate("MainWindow", "Algorithm #1"))
        self.action_Batch_moving.setText(_translate("MainWindow", "Batch moving"))
        self.action_Batch_moving.setStatusTip(_translate("MainWindow", "Move some of points."))
        self.action_Batch_moving.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.action_Slider_and_Rod.setText(_translate("MainWindow", "Slider and Rod"))
        self.action_Slider_and_Rod.setStatusTip(_translate("MainWindow", "Silder / Rod #1"))
        self.action_Solvespace_2D_sketch.setText(_translate("MainWindow", "&2D sketch"))
        self.action_Solvespace_2D_sketch.setStatusTip(_translate("MainWindow", "Output to Solvespace 2D sketch."))
        self.action_Solvespace_2D_sketch.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.action_DXF_2D_models.setText(_translate("MainWindow", "2D models"))
        self.action_DXF_2D_models.setStatusTip(_translate("MainWindow", "Output to Drawing Exchange models."))
        self.action_DXF_2D_models.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.action_Rock_Slider.setText(_translate("MainWindow", "Rock Slider"))
        self.action_Rock_Slider.setStatusTip(_translate("MainWindow", "Silder / Rod #2"))
        self.action_Lift_Tailgate.setText(_translate("MainWindow", "Lift Tailgate"))
        self.action_Lift_Tailgate.setStatusTip(_translate("MainWindow", "Silder / Rod #3"))
        self.GrashofChainMenuTitle.setText(_translate("MainWindow", "Grashof chain"))
        self.LinkagesMenuTitle.setText(_translate("MainWindow", "Linkages"))
        self.SlidersMenuTitle.setText(_translate("MainWindow", "Sliders"))
        self.DesignsMenuTitle.setText(_translate("MainWindow", "Design"))
        self.action_Theo_Jansen_s_multi_linkage.setText(_translate("MainWindow", "Theo Jansen\'s multi linkage"))
        self.action_Theo_Jansen_s_multi_linkage.setStatusTip(_translate("MainWindow", "Design #1"))
        self.SolvespaceMenuTitle.setText(_translate("MainWindow", "Solvespace"))
        self.DXFMenuTitle.setText(_translate("MainWindow", "DXF"))
        self.OtherFormatMenuTitle.setText(_translate("MainWindow", "Other Format"))
        self.action_Rock_Slider_Design.setText(_translate("MainWindow", "Rock Slider Design"))
        self.action_Rock_Slider_Design.setStatusTip(_translate("MainWindow", "Design #2"))
        self.action_Import_From_Workbook.setText(_translate("MainWindow", "From Workbook"))
        self.action_Import_From_Workbook.setStatusTip(_translate("MainWindow", "Import from workbook."))
        self.action_About_Qt.setText(_translate("MainWindow", "About Qt"))
        self.action_About_Qt.setStatusTip(_translate("MainWindow", "Show Qt about."))
        self.action_Four_bar_linkage.setText(_translate("MainWindow", "Four bar linkage"))
        self.action_Four_bar_linkage.setStatusTip(_translate("MainWindow", "Linkage #3"))
        self.action_Load_Workbook.setText(_translate("MainWindow", "L&oad Workbook"))
        self.action_Load_Workbook.setStatusTip(_translate("MainWindow", "Load Workbook from xml or csv file."))
        self.action_Load_Workbook.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_Zoom_to_fit.setText(_translate("MainWindow", "Zoom to fit"))
        self.action_Zoom_to_fit.setStatusTip(_translate("MainWindow", "Zoom in as mechanism size."))
        self.action_Zoom_to_fit.setShortcut(_translate("MainWindow", "Space"))
        self.action_Path_Track.setText(_translate("MainWindow", "Path track"))
        self.action_Path_Track.setStatusTip(_translate("MainWindow", "Update all points, then tracking point with the shaft angle."))
        self.action_Path_Clear.setText(_translate("MainWindow", "Clear path"))
        self.action_Path_Clear.setStatusTip(_translate("MainWindow", "Clear current path."))
        self.action_Path_coordinate.setText(_translate("MainWindow", "View path coordinate"))
        self.action_Path_coordinate.setStatusTip(_translate("MainWindow", "View path coordinate."))
        self.action_Path_data_show.setText(_translate("MainWindow", "Show path data"))
        self.action_Path_data_show.setStatusTip(_translate("MainWindow", "Show path data on canvas."))
        self.action_Save_path_only.setText(_translate("MainWindow", "Save path only"))
        self.action_Save_path_only.setStatusTip(_translate("MainWindow", "Save path for merge to another workbook."))
        self.AlgorithmMenuTitle.setText(_translate("MainWindow", "Algorithm"))
        self.action_Three_Algorithm_Result.setText(_translate("MainWindow", "Three Algorithm Result"))
        self.action_Three_Algorithm_Result.setStatusTip(_translate("MainWindow", "Algorithm #2"))
        self.action_Path_style.setText(_translate("MainWindow", "Show in solid path style"))
        self.action_Path_style.setStatusTip(_translate("MainWindow", "Show path in solid line style, otherwise will be isolated dots."))
        self.action_Pyslvs_com.setText(_translate("MainWindow", "&Pyslvs.com"))
        self.action_Pyslvs_com.setStatusTip(_translate("MainWindow", "Goto Pyslvs home page."))
        self.action_Show_console.setText(_translate("MainWindow", "Show GUI console"))

import icons_rc
import preview_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

