# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ahshoe\Desktop\mde1a1\src\core\panel\run_Drive_shaft.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(460, 361)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pathDemoMode = QtWidgets.QLabel(Form)
        self.pathDemoMode.setObjectName("pathDemoMode")
        self.horizontalLayout.addWidget(self.pathDemoMode)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Shaft = QtWidgets.QComboBox(Form)
        self.Shaft.setObjectName("Shaft")
        self.horizontalLayout_2.addWidget(self.Shaft)
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.Degree_text = QtWidgets.QDoubleSpinBox(Form)
        self.Degree_text.setMaximum(360.0)
        self.Degree_text.setSingleStep(10.0)
        self.Degree_text.setObjectName("Degree_text")
        self.horizontalLayout_2.addWidget(self.Degree_text)
        self.playButton = QtWidgets.QPushButton(Form)
        self.playButton.setAutoDefault(True)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_2.addWidget(self.playButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.anglePanel = QtWidgets.QHBoxLayout()
        self.anglePanel.setObjectName("anglePanel")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.a0 = QtWidgets.QPushButton(Form)
        self.a0.setObjectName("a0")
        self.verticalLayout.addWidget(self.a0)
        self.a90 = QtWidgets.QPushButton(Form)
        self.a90.setObjectName("a90")
        self.verticalLayout.addWidget(self.a90)
        self.a180 = QtWidgets.QPushButton(Form)
        self.a180.setObjectName("a180")
        self.verticalLayout.addWidget(self.a180)
        self.a270 = QtWidgets.QPushButton(Form)
        self.a270.setObjectName("a270")
        self.verticalLayout.addWidget(self.a270)
        self.anglePanel.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.a45 = QtWidgets.QPushButton(Form)
        self.a45.setObjectName("a45")
        self.verticalLayout_2.addWidget(self.a45)
        self.a135 = QtWidgets.QPushButton(Form)
        self.a135.setObjectName("a135")
        self.verticalLayout_2.addWidget(self.a135)
        self.a225 = QtWidgets.QPushButton(Form)
        self.a225.setObjectName("a225")
        self.verticalLayout_2.addWidget(self.a225)
        self.a315 = QtWidgets.QPushButton(Form)
        self.a315.setObjectName("a315")
        self.verticalLayout_2.addWidget(self.a315)
        self.anglePanel.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.anglePanel.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.anglePanel)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.line.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p>Drive the shaft to the specified angle.</p></body></html>"))
        self.pathDemoMode.setToolTip(_translate("Form", "Using Path data to present mechanism."))
        self.pathDemoMode.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ff0000;\">Path demo mode (?)</span></p></body></html>"))
        self.label_2.setText(_translate("Form", " in Angle:"))
        self.Degree_text.setSuffix(_translate("Form", "°"))
        self.playButton.setText(_translate("Form", "Play"))
        self.a0.setText(_translate("Form", "0/360°"))
        self.a90.setText(_translate("Form", "90°"))
        self.a180.setText(_translate("Form", "180°"))
        self.a270.setText(_translate("Form", "270°"))
        self.a45.setText(_translate("Form", "45°"))
        self.a135.setText(_translate("Form", "135°"))
        self.a225.setText(_translate("Form", "225°"))
        self.a315.setText(_translate("Form", "315°"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

