# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ahshoe/Desktop/Pyslvs-PyQt5/core/panel/run_Triangle_Solver_edit.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(665, 287)
        Dialog.setMinimumSize(QtCore.QSize(665, 287))
        Dialog.setMaximumSize(QtCore.QSize(665, 287))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/TS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.typePanel = QtWidgets.QWidget(Dialog)
        self.typePanel.setObjectName("typePanel")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.typePanel)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.typePanel)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.type = QtWidgets.QComboBox(self.typePanel)
        self.type.setObjectName("type")
        self.type.addItem("")
        self.type.addItem("")
        self.verticalLayout_3.addWidget(self.type)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.typePanel)
        self.p1Panel = QtWidgets.QWidget(Dialog)
        self.p1Panel.setObjectName("p1Panel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.p1Panel)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.p1Panel)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.p1Exist = QtWidgets.QRadioButton(self.p1Panel)
        self.p1Exist.setObjectName("p1Exist")
        self.verticalLayout_2.addWidget(self.p1Exist)
        self.p1 = QtWidgets.QComboBox(self.p1Panel)
        self.p1.setEnabled(False)
        self.p1.setObjectName("p1")
        self.verticalLayout_2.addWidget(self.p1)
        self.p1Customize = QtWidgets.QRadioButton(self.p1Panel)
        self.p1Customize.setChecked(True)
        self.p1Customize.setObjectName("p1Customize")
        self.verticalLayout_2.addWidget(self.p1Customize)
        self.p1Layout = QtWidgets.QWidget(self.p1Panel)
        self.p1Layout.setObjectName("p1Layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.p1Layout)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.p1Layout)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.x1 = QtWidgets.QDoubleSpinBox(self.p1Layout)
        self.x1.setMinimum(-99.99)
        self.x1.setObjectName("x1")
        self.horizontalLayout.addWidget(self.x1)
        self.label_7 = QtWidgets.QLabel(self.p1Layout)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.y1 = QtWidgets.QDoubleSpinBox(self.p1Layout)
        self.y1.setMinimum(-99.99)
        self.y1.setObjectName("y1")
        self.horizontalLayout.addWidget(self.y1)
        self.verticalLayout_2.addWidget(self.p1Layout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.p1Panel)
        self.p2Panel = QtWidgets.QWidget(Dialog)
        self.p2Panel.setObjectName("p2Panel")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.p2Panel)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.p2Panel)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.p2Exist = QtWidgets.QRadioButton(self.p2Panel)
        self.p2Exist.setObjectName("p2Exist")
        self.verticalLayout_6.addWidget(self.p2Exist)
        self.p2 = QtWidgets.QComboBox(self.p2Panel)
        self.p2.setEnabled(False)
        self.p2.setObjectName("p2")
        self.verticalLayout_6.addWidget(self.p2)
        self.p2Customize = QtWidgets.QRadioButton(self.p2Panel)
        self.p2Customize.setChecked(True)
        self.p2Customize.setObjectName("p2Customize")
        self.verticalLayout_6.addWidget(self.p2Customize)
        self.p2Layout = QtWidgets.QWidget(self.p2Panel)
        self.p2Layout.setObjectName("p2Layout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.p2Layout)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.p2Layout)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.x2 = QtWidgets.QDoubleSpinBox(self.p2Layout)
        self.x2.setMinimum(-99.99)
        self.x2.setObjectName("x2")
        self.horizontalLayout_2.addWidget(self.x2)
        self.label_11 = QtWidgets.QLabel(self.p2Layout)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.y2 = QtWidgets.QDoubleSpinBox(self.p2Layout)
        self.y2.setMinimum(-99.99)
        self.y2.setObjectName("y2")
        self.horizontalLayout_2.addWidget(self.y2)
        self.verticalLayout_6.addWidget(self.p2Layout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_3.addWidget(self.p2Panel)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.len1Panel = QtWidgets.QWidget(Dialog)
        self.len1Panel.setObjectName("len1Panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.len1Panel)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.len1Panel)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.len1 = QtWidgets.QDoubleSpinBox(self.len1Panel)
        self.len1.setMinimum(0.01)
        self.len1.setProperty("value", 10.0)
        self.len1.setObjectName("len1")
        self.verticalLayout.addWidget(self.len1)
        self.verticalLayout_7.addWidget(self.len1Panel)
        self.len2Panel = QtWidgets.QWidget(Dialog)
        self.len2Panel.setEnabled(False)
        self.len2Panel.setObjectName("len2Panel")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.len2Panel)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.len2Panel)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.len2 = QtWidgets.QDoubleSpinBox(self.len2Panel)
        self.len2.setMinimum(0.01)
        self.len2.setProperty("value", 10.0)
        self.len2.setObjectName("len2")
        self.verticalLayout_5.addWidget(self.len2)
        self.verticalLayout_7.addWidget(self.len2Panel)
        self.anglePanel = QtWidgets.QWidget(Dialog)
        self.anglePanel.setObjectName("anglePanel")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.anglePanel)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.anglePanel)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.anglePanel)
        self.doubleSpinBox.setMaximum(360.0)
        self.doubleSpinBox.setProperty("value", 30.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout_4.addWidget(self.doubleSpinBox)
        self.verticalLayout_7.addWidget(self.anglePanel)
        spacerItem3 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        self.p1Customize.toggled['bool'].connect(self.p1Layout.setEnabled)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.p2Customize.toggled['bool'].connect(self.p2Layout.setEnabled)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.p1Exist.toggled['bool'].connect(self.p1.setEnabled)
        self.p2Exist.toggled['bool'].connect(self.p2.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Direction"))
        self.label_8.setText(_translate("Dialog", "Type"))
        self.type.setItemText(0, _translate("Dialog", "PLAP"))
        self.type.setItemText(1, _translate("Dialog", "PLLP"))
        self.label.setText(_translate("Dialog", "Point1"))
        self.p1Exist.setText(_translate("Dialog", "Exist"))
        self.p1Customize.setText(_translate("Dialog", "Customize"))
        self.label_6.setText(_translate("Dialog", "x1:"))
        self.label_7.setText(_translate("Dialog", "y1:"))
        self.label_5.setText(_translate("Dialog", "Point2"))
        self.p2Exist.setText(_translate("Dialog", "Exist"))
        self.p2Customize.setText(_translate("Dialog", "Customize"))
        self.label_10.setText(_translate("Dialog", "x1:"))
        self.label_11.setText(_translate("Dialog", "y1:"))
        self.label_2.setText(_translate("Dialog", "Length1"))
        self.label_9.setText(_translate("Dialog", "Length2"))
        self.label_4.setText(_translate("Dialog", "Angle"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

