# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ahshoe\Desktop\Pyslvs-PyQt5\core\panel\run_Triangle_Solver_template.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(666, 556)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/TS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.templatePanel = QtWidgets.QGroupBox(Dialog)
        self.templatePanel.setObjectName("templatePanel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.templatePanel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.template_2 = QtWidgets.QComboBox(self.templatePanel)
        self.template_2.setMinimumSize(QtCore.QSize(120, 0))
        self.template_2.setObjectName("template_2")
        self.template_2.addItem("")
        self.template_2.addItem("")
        self.verticalLayout_2.addWidget(self.template_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.templatePanel)
        self.Parameters = QtWidgets.QGroupBox(Dialog)
        self.Parameters.setObjectName("Parameters")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Parameters)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.parameterTable = QtWidgets.QTableWidget(self.Parameters)
        self.parameterTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.parameterTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.parameterTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.parameterTable.setObjectName("parameterTable")
        self.parameterTable.setColumnCount(2)
        self.parameterTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.parameterTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameterTable.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.parameterTable)
        self.horizontalLayout.addWidget(self.Parameters)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.templateImage = QtWidgets.QLabel(self.groupBox)
        self.templateImage.setText("")
        self.templateImage.setObjectName("templateImage")
        self.verticalLayout.addWidget(self.templateImage)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_5.addWidget(self.buttonBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Template"))
        self.templatePanel.setTitle(_translate("Dialog", "Template"))
        self.template_2.setItemText(0, _translate("Dialog", "4-bar linkage"))
        self.template_2.setItemText(1, _translate("Dialog", "8-bar linkage"))
        self.Parameters.setTitle(_translate("Dialog", "Parameters"))
        item = self.parameterTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name"))
        item = self.parameterTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Point"))
        self.groupBox.setTitle(_translate("Dialog", "Preview"))
        self.groupBox_2.setTitle(_translate("Dialog", "Triangles"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Type"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Point[1]"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Point[2]"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Point[3]"))

import icons_rc
import preview_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

