# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ahshoe/Desktop/mde1a1/src/core/panel/run_Triangle_Solver.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(488, 322)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.directionsTable = QtWidgets.QTableWidget(Form)
        self.directionsTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.directionsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.directionsTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.directionsTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.directionsTable.setObjectName("directionsTable")
        self.directionsTable.setColumnCount(5)
        self.directionsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/TS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.directionsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.directionsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.directionsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.directionsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.directionsTable.setHorizontalHeaderItem(4, item)
        self.directionsTable.horizontalHeader().setDefaultSectionSize(80)
        self.directionsTable.horizontalHeader().setMinimumSectionSize(80)
        self.horizontalLayout.addWidget(self.directionsTable)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pluse_PLAP = QtWidgets.QPushButton(Form)
        self.pluse_PLAP.setObjectName("pluse_PLAP")
        self.verticalLayout_2.addWidget(self.pluse_PLAP)
        self.pluse_PLLP = QtWidgets.QPushButton(Form)
        self.pluse_PLLP.setObjectName("pluse_PLLP")
        self.verticalLayout_2.addWidget(self.pluse_PLLP)
        self.pluse_PLPP = QtWidgets.QPushButton(Form)
        self.pluse_PLPP.setObjectName("pluse_PLPP")
        self.verticalLayout_2.addWidget(self.pluse_PLPP)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.remove_botton = QtWidgets.QPushButton(Form)
        self.remove_botton.setObjectName("remove_botton")
        self.verticalLayout_2.addWidget(self.remove_botton)
        self.clear_botton = QtWidgets.QPushButton(Form)
        self.clear_botton.setObjectName("clear_botton")
        self.verticalLayout_2.addWidget(self.clear_botton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pluse_PPP = QtWidgets.QPushButton(Form)
        self.pluse_PPP.setObjectName("pluse_PPP")
        self.horizontalLayout_4.addWidget(self.pluse_PPP)
        self.Bar4 = QtWidgets.QPushButton(Form)
        self.Bar4.setObjectName("Bar4")
        self.horizontalLayout_4.addWidget(self.Bar4)
        self.Bar8 = QtWidgets.QPushButton(Form)
        self.Bar8.setObjectName("Bar8")
        self.horizontalLayout_4.addWidget(self.Bar8)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.Solve = QtWidgets.QPushButton(Form)
        self.Solve.setEnabled(False)
        self.Solve.setObjectName("Solve")
        self.horizontalLayout_2.addWidget(self.Solve)
        self.Merge = QtWidgets.QPushButton(Form)
        self.Merge.setEnabled(False)
        self.Merge.setObjectName("Merge")
        self.horizontalLayout_2.addWidget(self.Merge)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.directionsTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Type"))
        item = self.directionsTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Result"))
        item = self.directionsTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "p1"))
        item = self.directionsTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "p2"))
        item = self.directionsTable.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Condition"))
        self.pluse_PLAP.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Point(A), Length(L0), Angle(β), Point(B)</span></p><p><img width=\"450\" src=\":/icons/preview/PLAP.png\"/></p></body></html>"))
        self.pluse_PLAP.setText(_translate("Form", "+[PLAP]"))
        self.pluse_PLLP.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Point(A), Length(L0), Length(R0), Point(B)</span></p><p><img width=\"450\" src=\":/icons/preview/PLLP.png\"/></p></body></html>"))
        self.pluse_PLLP.setText(_translate("Form", "+[PLLP]"))
        self.pluse_PLPP.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Point(A), Length(L0), Point(B), Point(C)</span></p><p><img width=\"450\" src=\":/icons/preview/PLPP.png\"/></p></body></html>"))
        self.pluse_PLPP.setText(_translate("Form", "+[PLPP]"))
        self.remove_botton.setText(_translate("Form", "-"))
        self.clear_botton.setText(_translate("Form", "Clear"))
        self.pluse_PPP.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Point(A), Point(B), Point(C)</span></p><p><span style=\" font-size:12pt; color:#ff0000;\">Return three side length.</span></p><p><span style=\" font-size:12pt; color:#ff0000;\">Use to build 3 points entities.</span></p><p><img src=\":/icons/preview/PPP.png\" width=\"450\"/></p></body></html>"))
        self.pluse_PPP.setText(_translate("Form", "+[PPP]"))
        self.Bar4.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">4 Bar Linkage</span></p><p><span style=\" font-size:12pt; color:#ff0000;\">Need for 5 point.</span></p><p><span style=\" font-size:12pt;\">Generates 3 triangles.</span></p><p><img src=\":/icons/preview/4Bar_triangle.png\" width=\"300\"/></p></body></html>"))
        self.Bar4.setText(_translate("Form", "+4-bar linkage"))
        self.Bar8.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">8 Bar Linkage</span></p><p><span style=\" font-size:12pt; color:#ff0000;\">Need for 8 point.</span></p><p><span style=\" font-size:12pt;\">Generates 6 triangles.</span></p><p><img src=\":/icons/preview/8Bar_triangle.png\" width=\"300\"/></p></body></html>"))
        self.Bar8.setText(_translate("Form", "+8-bar linkage"))
        self.Solve.setText(_translate("Form", "Solve"))
        self.Merge.setText(_translate("Form", "Merge"))

import icons_rc
import preview_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

