# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/widgets/main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from core.QtModules import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882, 849)
        MainWindow.setMouseTracking(True)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central_widget.sizePolicy().hasHeightForWidth())
        self.central_widget.setSizePolicy(sizePolicy)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_splitter = QtWidgets.QSplitter(self.central_widget)
        self.main_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.main_splitter.setObjectName("main_splitter")
        self.left_splitter = QtWidgets.QSplitter(self.main_splitter)
        self.left_splitter.setMinimumSize(QtCore.QSize(450, 0))
        self.left_splitter.setOrientation(QtCore.Qt.Vertical)
        self.left_splitter.setObjectName("left_splitter")
        self.curve_area = QtWidgets.QWidget(self.left_splitter)
        self.curve_area.setObjectName("curve_area")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.curve_area)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.main_panel = QtWidgets.QTabWidget(self.curve_area)
        self.main_panel.setTabPosition(QtWidgets.QTabWidget.West)
        self.main_panel.setObjectName("main_panel")
        self.mechanism_tab = QtWidgets.QWidget()
        self.mechanism_tab.setObjectName("mechanism_tab")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.mechanism_tab)
        self.verticalLayout_27.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.mechanism_panel_splitter = QtWidgets.QSplitter(self.mechanism_tab)
        self.mechanism_panel_splitter.setOrientation(QtCore.Qt.Vertical)
        self.mechanism_panel_splitter.setObjectName("mechanism_panel_splitter")
        self.EntitiesTabWidget = QtWidgets.QWidget(self.mechanism_panel_splitter)
        self.EntitiesTabWidget.setObjectName("EntitiesTabWidget")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.EntitiesTabWidget)
        self.verticalLayout_29.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.entities_tab = QtWidgets.QTabWidget(self.EntitiesTabWidget)
        self.entities_tab.setObjectName("entities_tab")
        self.PointsTab = QtWidgets.QWidget()
        self.PointsTab.setObjectName("PointsTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.PointsTab)
        self.verticalLayout_9.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.entities_point_widget = QtWidgets.QWidget(self.PointsTab)
        self.entities_point_widget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.entities_point_widget.setObjectName("entities_point_widget")
        self.entities_point_layout = QtWidgets.QVBoxLayout(self.entities_point_widget)
        self.entities_point_layout.setContentsMargins(0, 0, 0, 0)
        self.entities_point_layout.setObjectName("entities_point_layout")
        self.verticalLayout_9.addWidget(self.entities_point_widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/bearing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.entities_tab.addTab(self.PointsTab, icon1, "")
        self.LinksTab = QtWidgets.QWidget()
        self.LinksTab.setObjectName("LinksTab")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.LinksTab)
        self.verticalLayout_19.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.entities_link_widget = QtWidgets.QWidget(self.LinksTab)
        self.entities_link_widget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.entities_link_widget.setObjectName("entities_link_widget")
        self.entities_link_layout = QtWidgets.QVBoxLayout(self.entities_link_widget)
        self.entities_link_layout.setContentsMargins(0, 0, 0, 0)
        self.entities_link_layout.setObjectName("entities_link_layout")
        self.verticalLayout_19.addWidget(self.entities_link_widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.entities_tab.addTab(self.LinksTab, icon2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.EntitiesExpr_widget = QtWidgets.QWidget(self.tab)
        self.EntitiesExpr_widget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.EntitiesExpr_widget.setObjectName("EntitiesExpr_widget")
        self.entities_expr_layout = QtWidgets.QVBoxLayout(self.EntitiesExpr_widget)
        self.entities_expr_layout.setContentsMargins(0, 0, 0, 0)
        self.entities_expr_layout.setObjectName("entities_expr_layout")
        self.verticalLayout_8.addWidget(self.EntitiesExpr_widget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/configure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.entities_tab.addTab(self.tab, icon3, "")
        self.verticalLayout_29.addWidget(self.entities_tab)
        self.MechanismsTabWidget = QtWidgets.QWidget(self.mechanism_panel_splitter)
        self.MechanismsTabWidget.setObjectName("MechanismsTabWidget")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.MechanismsTabWidget)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.MechanismPanelSplitterLine = QtWidgets.QFrame(self.MechanismsTabWidget)
        self.MechanismPanelSplitterLine.setLineWidth(3)
        self.MechanismPanelSplitterLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.MechanismPanelSplitterLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MechanismPanelSplitterLine.setObjectName("MechanismPanelSplitterLine")
        self.verticalLayout_21.addWidget(self.MechanismPanelSplitterLine)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.mechanism_storage_name_tag_text = QtWidgets.QLabel(self.MechanismsTabWidget)
        self.mechanism_storage_name_tag_text.setObjectName("mechanism_storage_name_tag_text")
        self.horizontalLayout_11.addWidget(self.mechanism_storage_name_tag_text)
        self.mechanism_storage_name_tag = QtWidgets.QLineEdit(self.MechanismsTabWidget)
        self.mechanism_storage_name_tag.setObjectName("mechanism_storage_name_tag")
        self.horizontalLayout_11.addWidget(self.mechanism_storage_name_tag)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.mechanism_storage = QtWidgets.QListWidget(self.MechanismsTabWidget)
        self.mechanism_storage.setObjectName("mechanism_storage")
        self.verticalLayout_4.addWidget(self.mechanism_storage)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.mechanism_storage_add = QtWidgets.QPushButton(self.MechanismsTabWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mechanism_storage_add.setIcon(icon4)
        self.mechanism_storage_add.setObjectName("mechanism_storage_add")
        self.verticalLayout_20.addWidget(self.mechanism_storage_add)
        self.mechanism_storage_restore = QtWidgets.QPushButton(self.MechanismsTabWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/data_update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mechanism_storage_restore.setIcon(icon5)
        self.mechanism_storage_restore.setObjectName("mechanism_storage_restore")
        self.verticalLayout_20.addWidget(self.mechanism_storage_restore)
        self.line_4 = QtWidgets.QFrame(self.MechanismsTabWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_20.addWidget(self.line_4)
        self.mechanism_storage_copy = QtWidgets.QPushButton(self.MechanismsTabWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mechanism_storage_copy.setIcon(icon6)
        self.mechanism_storage_copy.setObjectName("mechanism_storage_copy")
        self.verticalLayout_20.addWidget(self.mechanism_storage_copy)
        self.mechanism_storage_paste = QtWidgets.QPushButton(self.MechanismsTabWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mechanism_storage_paste.setIcon(icon7)
        self.mechanism_storage_paste.setObjectName("mechanism_storage_paste")
        self.verticalLayout_20.addWidget(self.mechanism_storage_paste)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem)
        self.mechanism_storage_delete = QtWidgets.QPushButton(self.MechanismsTabWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mechanism_storage_delete.setIcon(icon8)
        self.mechanism_storage_delete.setObjectName("mechanism_storage_delete")
        self.verticalLayout_20.addWidget(self.mechanism_storage_delete)
        self.horizontalLayout_9.addLayout(self.verticalLayout_20)
        self.verticalLayout_21.addLayout(self.horizontalLayout_9)
        self.verticalLayout_27.addWidget(self.mechanism_panel_splitter)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/mechanism.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_panel.addTab(self.mechanism_tab, icon9, "")
        self.inputs_tab = QtWidgets.QWidget()
        self.inputs_tab.setObjectName("inputs_tab")
        self.inputs_tab_layout = QtWidgets.QVBoxLayout(self.inputs_tab)
        self.inputs_tab_layout.setObjectName("inputs_tab_layout")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/motor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_panel.addTab(self.inputs_tab, icon10, "")
        self.synthesis_tab = QtWidgets.QWidget()
        self.synthesis_tab.setObjectName("synthesis_tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.synthesis_tab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.synthesis_tab_widget = QtWidgets.QTabWidget(self.synthesis_tab)
        self.synthesis_tab_widget.setObjectName("synthesis_tab_widget")
        self.verticalLayout_10.addWidget(self.synthesis_tab_widget)
        self.synthesis_progress = QtWidgets.QProgressBar(self.synthesis_tab)
        self.synthesis_progress.setStyleSheet("QProgressBar {\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #05B8CC;\n"
"    width: 20px;\n"
"}")
        self.synthesis_progress.setMaximum(3)
        self.synthesis_progress.setTextVisible(False)
        self.synthesis_progress.setObjectName("synthesis_progress")
        self.verticalLayout_10.addWidget(self.synthesis_progress)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/synthesis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_panel.addTab(self.synthesis_tab, icon11, "")
        self.history_tab = QtWidgets.QWidget()
        self.history_tab.setObjectName("history_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.history_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.undo_redo_layout = QtWidgets.QVBoxLayout()
        self.undo_redo_layout.setObjectName("undo_redo_layout")
        self.label_8 = QtWidgets.QLabel(self.history_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.undo_redo_layout.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.undo_redo_layout)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_panel.addTab(self.history_tab, icon12, "")
        self.version_control_tab = QtWidgets.QWidget()
        self.version_control_tab.setObjectName("version_control_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.version_control_tab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.vc_layout = QtWidgets.QVBoxLayout()
        self.vc_layout.setObjectName("vc_layout")
        self.verticalLayout_5.addLayout(self.vc_layout)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/git.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_panel.addTab(self.version_control_tab, icon13, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.settings_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.settings_scrollarea = QtWidgets.QScrollArea(self.settings_tab)
        self.settings_scrollarea.setWidgetResizable(True)
        self.settings_scrollarea.setObjectName("settings_scrollarea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 401, 733))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.settings_ui_groupbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.settings_ui_groupbox.setObjectName("settings_ui_groupbox")
        self.formLayout = QtWidgets.QFormLayout(self.settings_ui_groupbox)
        self.formLayout.setObjectName("formLayout")
        self.linewidth_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.linewidth_label.setObjectName("linewidth_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.linewidth_label)
        self.line_width_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.line_width_option.setMinimum(1)
        self.line_width_option.setMaximum(10)
        self.line_width_option.setDisplayIntegerBase(10)
        self.line_width_option.setObjectName("line_width_option")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_width_option)
        self.fontsize_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.fontsize_label.setObjectName("fontsize_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fontsize_label)
        self.font_size_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.font_size_option.setMinimum(1)
        self.font_size_option.setMaximum(30)
        self.font_size_option.setSingleStep(2)
        self.font_size_option.setObjectName("font_size_option")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.font_size_option)
        self.pathwidth_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.pathwidth_label.setObjectName("pathwidth_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pathwidth_label)
        self.path_width_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.path_width_option.setMinimum(1)
        self.path_width_option.setMaximum(5)
        self.path_width_option.setObjectName("path_width_option")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.path_width_option)
        self.scalefactor_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.scalefactor_label.setObjectName("scalefactor_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.scalefactor_label)
        self.scalefactor_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.scalefactor_option.setMinimum(5)
        self.scalefactor_option.setMaximum(100)
        self.scalefactor_option.setSingleStep(5)
        self.scalefactor_option.setObjectName("scalefactor_option")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.scalefactor_option)
        self.selectionradius_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.selectionradius_label.setObjectName("selectionradius_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.selectionradius_label)
        self.selection_radius_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.selection_radius_option.setMinimum(3)
        self.selection_radius_option.setMaximum(10)
        self.selection_radius_option.setObjectName("selection_radius_option")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.selection_radius_option)
        self.linktransparency_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.linktransparency_label.setObjectName("linktransparency_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.linktransparency_label)
        self.link_trans_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.link_trans_option.setMaximum(80)
        self.link_trans_option.setSingleStep(10)
        self.link_trans_option.setObjectName("link_trans_option")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.link_trans_option)
        self.marginfactor_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.marginfactor_label.setObjectName("marginfactor_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.marginfactor_label)
        self.margin_factor_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.margin_factor_option.setMaximum(30)
        self.margin_factor_option.setSingleStep(5)
        self.margin_factor_option.setObjectName("margin_factor_option")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.margin_factor_option)
        self.jointsize_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.jointsize_label.setObjectName("jointsize_label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.jointsize_label)
        self.joint_size_option = QtWidgets.QSpinBox(self.settings_ui_groupbox)
        self.joint_size_option.setMinimum(1)
        self.joint_size_option.setMaximum(100)
        self.joint_size_option.setObjectName("joint_size_option")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.joint_size_option)
        self.zoomby_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.zoomby_label.setObjectName("zoomby_label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.zoomby_label)
        self.zoom_by_option = QtWidgets.QComboBox(self.settings_ui_groupbox)
        self.zoom_by_option.setObjectName("zoom_by_option")
        self.zoom_by_option.addItem("")
        self.zoom_by_option.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.zoom_by_option)
        self.snap_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.snap_label.setObjectName("snap_label")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.snap_label)
        self.snap_option = QtWidgets.QDoubleSpinBox(self.settings_ui_groupbox)
        self.snap_option.setMaximum(50.0)
        self.snap_option.setObjectName("snap_option")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.snap_option)
        self.background_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.background_label.setObjectName("background_label")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.background_label)
        self.background_layout = QtWidgets.QHBoxLayout()
        self.background_layout.setObjectName("background_layout")
        self.background_option = QtWidgets.QLineEdit(self.settings_ui_groupbox)
        self.background_option.setObjectName("background_option")
        self.background_layout.addWidget(self.background_option)
        self.background_choose_dir = QtWidgets.QToolButton(self.settings_ui_groupbox)
        self.background_choose_dir.setObjectName("background_choose_dir")
        self.background_layout.addWidget(self.background_choose_dir)
        self.formLayout.setLayout(11, QtWidgets.QFormLayout.FieldRole, self.background_layout)
        self.background_opacity_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.background_opacity_label.setObjectName("background_opacity_label")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.background_opacity_label)
        self.background_opacity_option = QtWidgets.QDoubleSpinBox(self.settings_ui_groupbox)
        self.background_opacity_option.setMaximum(1.0)
        self.background_opacity_option.setSingleStep(0.1)
        self.background_opacity_option.setProperty("value", 1.0)
        self.background_opacity_option.setObjectName("background_opacity_option")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.background_opacity_option)
        self.background_scale_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.background_scale_label.setObjectName("background_scale_label")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.background_scale_label)
        self.background_scale_option = QtWidgets.QDoubleSpinBox(self.settings_ui_groupbox)
        self.background_scale_option.setMinimum(0.01)
        self.background_scale_option.setMaximum(10.0)
        self.background_scale_option.setSingleStep(0.02)
        self.background_scale_option.setObjectName("background_scale_option")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.background_scale_option)
        self.background_offset_label = QtWidgets.QLabel(self.settings_ui_groupbox)
        self.background_offset_label.setObjectName("background_offset_label")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.background_offset_label)
        self.background_offset_layout = QtWidgets.QHBoxLayout()
        self.background_offset_layout.setObjectName("background_offset_layout")
        self.background_offset_x_option = QtWidgets.QDoubleSpinBox(self.settings_ui_groupbox)
        self.background_offset_x_option.setMinimum(-999999.0)
        self.background_offset_x_option.setMaximum(999999.0)
        self.background_offset_x_option.setObjectName("background_offset_x_option")
        self.background_offset_layout.addWidget(self.background_offset_x_option)
        self.background_offset_y_option = QtWidgets.QDoubleSpinBox(self.settings_ui_groupbox)
        self.background_offset_y_option.setMinimum(-999999.0)
        self.background_offset_y_option.setMaximum(999999.0)
        self.background_offset_y_option.setObjectName("background_offset_y_option")
        self.background_offset_layout.addWidget(self.background_offset_y_option)
        self.formLayout.setLayout(14, QtWidgets.QFormLayout.FieldRole, self.background_offset_layout)
        self.verticalLayout_3.addWidget(self.settings_ui_groupbox)
        self.settings_history_groupbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.settings_history_groupbox.setObjectName("settings_history_groupbox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.settings_history_groupbox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.UndoLimit_label = QtWidgets.QLabel(self.settings_history_groupbox)
        self.UndoLimit_label.setObjectName("UndoLimit_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.UndoLimit_label)
        self.undo_limit_option = QtWidgets.QSpinBox(self.settings_history_groupbox)
        self.undo_limit_option.setMinimum(5)
        self.undo_limit_option.setObjectName("undo_limit_option")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.undo_limit_option)
        self.verticalLayout_3.addWidget(self.settings_history_groupbox)
        self.settings_kernels_groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.settings_kernels_groupBox.setObjectName("settings_kernels_groupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.settings_kernels_groupBox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.planarsolver_label = QtWidgets.QLabel(self.settings_kernels_groupBox)
        self.planarsolver_label.setObjectName("planarsolver_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.planarsolver_label)
        self.planar_solver_option = QtWidgets.QComboBox(self.settings_kernels_groupBox)
        self.planar_solver_option.setObjectName("planar_solver_option")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.planar_solver_option)
        self.pathpreview_label = QtWidgets.QLabel(self.settings_kernels_groupBox)
        self.pathpreview_label.setObjectName("pathpreview_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pathpreview_label)
        self.path_preview_option = QtWidgets.QComboBox(self.settings_kernels_groupBox)
        self.path_preview_option.setObjectName("path_preview_option")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.path_preview_option)
        self.verticalLayout_3.addWidget(self.settings_kernels_groupBox)
        self.settings_misc_groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.settings_misc_groupBox.setObjectName("settings_misc_groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.settings_misc_groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.title_full_path_option = QtWidgets.QCheckBox(self.settings_misc_groupBox)
        self.title_full_path_option.setObjectName("title_full_path_option")
        self.verticalLayout_7.addWidget(self.title_full_path_option)
        self.console_error_option = QtWidgets.QCheckBox(self.settings_misc_groupBox)
        self.console_error_option.setObjectName("console_error_option")
        self.verticalLayout_7.addWidget(self.console_error_option)
        self.monochrome_option = QtWidgets.QCheckBox(self.settings_misc_groupBox)
        self.monochrome_option.setObjectName("monochrome_option")
        self.verticalLayout_7.addWidget(self.monochrome_option)
        self.verticalLayout_3.addWidget(self.settings_misc_groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 619, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dontsave_option = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.dontsave_option.setObjectName("dontsave_option")
        self.horizontalLayout.addWidget(self.dontsave_option)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.settings_scrollarea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.settings_scrollarea)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.settings_reset = QtWidgets.QPushButton(self.settings_tab)
        self.settings_reset.setObjectName("settings_reset")
        self.horizontalLayout_10.addWidget(self.settings_reset)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.version_label = QtWidgets.QLabel(self.settings_tab)
        self.version_label.setText("")
        self.version_label.setObjectName("version_label")
        self.horizontalLayout_10.addWidget(self.version_label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_panel.addTab(self.settings_tab, icon14, "")
        self.verticalLayout_31.addWidget(self.main_panel)
        self.RightSplitter = QtWidgets.QSplitter(self.main_splitter)
        self.RightSplitter.setOrientation(QtCore.Qt.Vertical)
        self.RightSplitter.setObjectName("RightSplitter")
        self.histogramArea = QtWidgets.QWidget(self.RightSplitter)
        self.histogramArea.setObjectName("histogramArea")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.histogramArea)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line = QtWidgets.QFrame(self.histogramArea)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.canvas_splitter = QtWidgets.QSplitter(self.histogramArea)
        self.canvas_splitter.setOrientation(QtCore.Qt.Vertical)
        self.canvas_splitter.setHandleWidth(3)
        self.canvas_splitter.setObjectName("canvas_splitter")
        self.BrowserWidget = QtWidgets.QWidget(self.canvas_splitter)
        self.BrowserWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.BrowserWidget.setObjectName("BrowserWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.BrowserWidget)
        self.horizontalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.zoom_bar = QtWidgets.QSlider(self.BrowserWidget)
        self.zoom_bar.setMinimum(10)
        self.zoom_bar.setMaximum(2000)
        self.zoom_bar.setSingleStep(50)
        self.zoom_bar.setPageStep(50)
        self.zoom_bar.setProperty("value", 200)
        self.zoom_bar.setSliderPosition(200)
        self.zoom_bar.setOrientation(QtCore.Qt.Horizontal)
        self.zoom_bar.setInvertedControls(False)
        self.zoom_bar.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.zoom_bar.setTickInterval(200)
        self.zoom_bar.setObjectName("zoom_bar")
        self.horizontalLayout_7.addWidget(self.zoom_bar)
        self.zoom_button = QtWidgets.QPushButton(self.BrowserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom_button.sizePolicy().hasHeightForWidth())
        self.zoom_button.setSizePolicy(sizePolicy)
        self.zoom_button.setObjectName("zoom_button")
        self.horizontalLayout_7.addWidget(self.zoom_button)
        self.ResetCanvas = QtWidgets.QPushButton(self.BrowserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResetCanvas.sizePolicy().hasHeightForWidth())
        self.ResetCanvas.setSizePolicy(sizePolicy)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/aim.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ResetCanvas.setIcon(icon15)
        self.ResetCanvas.setIconSize(QtCore.QSize(32, 32))
        self.ResetCanvas.setObjectName("ResetCanvas")
        self.horizontalLayout_7.addWidget(self.ResetCanvas)
        self.free_move_button = QtWidgets.QPushButton(self.BrowserWidget)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/free_move_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.free_move_button.setIcon(icon16)
        self.free_move_button.setIconSize(QtCore.QSize(32, 32))
        self.free_move_button.setObjectName("free_move_button")
        self.horizontalLayout_7.addWidget(self.free_move_button)
        self.line_3 = QtWidgets.QFrame(self.BrowserWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_7.addWidget(self.line_3)
        self.DOFLable = QtWidgets.QLabel(self.BrowserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DOFLable.sizePolicy().hasHeightForWidth())
        self.DOFLable.setSizePolicy(sizePolicy)
        self.DOFLable.setObjectName("DOFLable")
        self.horizontalLayout_7.addWidget(self.DOFLable)
        self.DOFview = QtWidgets.QLabel(self.BrowserWidget)
        self.DOFview.setText("")
        self.DOFview.setObjectName("DOFview")
        self.horizontalLayout_7.addWidget(self.DOFview)
        self.conflict = QtWidgets.QLabel(self.BrowserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conflict.sizePolicy().hasHeightForWidth())
        self.conflict.setSizePolicy(sizePolicy)
        self.conflict.setTextFormat(QtCore.Qt.RichText)
        self.conflict.setObjectName("conflict")
        self.horizontalLayout_7.addWidget(self.conflict)
        self.console_widget = QtWidgets.QWidget(self.canvas_splitter)
        self.console_widget.setObjectName("console_widget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.console_widget)
        self.verticalLayout_11.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.line_6 = QtWidgets.QFrame(self.console_widget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_11.addWidget(self.line_6)
        self.widget = QtWidgets.QWidget(self.console_widget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.console_disconnect_button = QtWidgets.QPushButton(self.widget)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/disconnect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.console_disconnect_button.setIcon(icon17)
        self.console_disconnect_button.setObjectName("console_disconnect_button")
        self.horizontalLayout_5.addWidget(self.console_disconnect_button)
        self.console_connect_button = QtWidgets.QPushButton(self.widget)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.console_connect_button.setIcon(icon18)
        self.console_connect_button.setObjectName("console_connect_button")
        self.horizontalLayout_5.addWidget(self.console_connect_button)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.clearConsole = QtWidgets.QPushButton(self.widget)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/clean.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearConsole.setIcon(icon19)
        self.clearConsole.setObjectName("clearConsole")
        self.horizontalLayout_5.addWidget(self.clearConsole)
        self.verticalLayout_11.addWidget(self.widget)
        self.console_widget_browser = QtWidgets.QTextBrowser(self.console_widget)
        self.console_widget_browser.setObjectName("console_widget_browser")
        self.verticalLayout_11.addWidget(self.console_widget_browser)
        self.horizontalLayout_2.addWidget(self.canvas_splitter)
        self.verticalLayout_2.addWidget(self.main_splitter)
        MainWindow.setCentralWidget(self.central_widget)
        self.menu_bar = QtWidgets.QMenuBar(MainWindow)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 882, 21))
        self.menu_bar.setObjectName("menu_bar")
        self.menu_file = QtWidgets.QMenu(self.menu_bar)
        self.menu_file.setStatusTip("")
        self.menu_file.setObjectName("menu_file")
        self.menu_export = QtWidgets.QMenu(self.menu_file)
        self.menu_export.setObjectName("menu_export")
        self.menu_import = QtWidgets.QMenu(self.menu_file)
        self.menu_import.setObjectName("menu_import")
        self.menu_mechanism = QtWidgets.QMenu(self.menu_bar)
        self.menu_mechanism.setObjectName("menu_mechanism")
        self.menu_options = QtWidgets.QMenu(self.menu_bar)
        self.menu_options.setObjectName("menu_options")
        self.menu_help = QtWidgets.QMenu(self.menu_bar)
        self.menu_help.setObjectName("menu_help")
        self.menu_edit = QtWidgets.QMenu(self.menu_bar)
        self.menu_edit.setObjectName("menu_edit")
        MainWindow.setMenuBar(self.menu_bar)
        self.status_bar = QtWidgets.QStatusBar(MainWindow)
        self.status_bar.setObjectName("status_bar")
        MainWindow.setStatusBar(self.status_bar)
        self.action_new_workbook = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/new_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_new_workbook.setIcon(icon20)
        self.action_new_workbook.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_new_workbook.setObjectName("action_new_workbook")
        self.action_new_point = QtWidgets.QAction(MainWindow)
        self.action_new_point.setIcon(icon1)
        self.action_new_point.setObjectName("action_new_point")
        self.action_new_link = QtWidgets.QAction(MainWindow)
        self.action_new_link.setIcon(icon2)
        self.action_new_link.setObjectName("action_new_link")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setCheckable(False)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exit.setIcon(icon21)
        self.action_exit.setObjectName("action_exit")
        self.action_mde_tw = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons/kmol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_mde_tw.setIcon(icon22)
        self.action_mde_tw.setObjectName("action_mde_tw")
        self.action_github_repository = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icons/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_github_repository.setIcon(icon23)
        self.action_github_repository.setObjectName("action_github_repository")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setIcon(icon)
        self.action_about.setObjectName("action_about")
        self.action_full_screen = QtWidgets.QAction(MainWindow)
        self.action_full_screen.setCheckable(True)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/icons/fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_full_screen.setIcon(icon24)
        self.action_full_screen.setObjectName("action_full_screen")
        self.action_export_image = QtWidgets.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/icons/picture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_export_image.setIcon(icon25)
        self.action_export_image.setObjectName("action_export_image")
        self.action_commit = QtWidgets.QAction(MainWindow)
        self.action_commit.setIcon(icon13)
        self.action_commit.setPriority(QtWidgets.QAction.HighPriority)
        self.action_commit.setObjectName("action_commit")
        self.action_python_script = QtWidgets.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/icons/script.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_python_script.setIcon(icon26)
        self.action_python_script.setObjectName("action_python_script")
        self.action_delete_point = QtWidgets.QAction(MainWindow)
        self.action_delete_point.setObjectName("action_delete_point")
        self.action_delete_link = QtWidgets.QAction(MainWindow)
        self.action_delete_link.setObjectName("action_delete_link")
        self.action_edit_point = QtWidgets.QAction(MainWindow)
        self.action_edit_point.setObjectName("action_edit_point")
        self.action_edit_link = QtWidgets.QAction(MainWindow)
        self.action_edit_link.setObjectName("action_edit_link")
        self.action_show_dimensions = QtWidgets.QAction(MainWindow)
        self.action_show_dimensions.setCheckable(True)
        self.action_show_dimensions.setObjectName("action_show_dimensions")
        self.action_show_point_mark = QtWidgets.QAction(MainWindow)
        self.action_show_point_mark.setCheckable(True)
        self.action_show_point_mark.setChecked(True)
        self.action_show_point_mark.setObjectName("action_show_point_mark")
        self.action_export_dxf = QtWidgets.QAction(MainWindow)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/icons/dxf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_export_dxf.setIcon(icon27)
        self.action_export_dxf.setObjectName("action_export_dxf")
        self.action_commit_as = QtWidgets.QAction(MainWindow)
        self.action_commit_as.setIcon(icon13)
        self.action_commit_as.setObjectName("action_commit_as")
        self.action_export_slvs = QtWidgets.QAction(MainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/icons/solvespace.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_export_slvs.setIcon(icon28)
        self.action_export_slvs.setObjectName("action_export_slvs")
        self.action_title_slvs = QtWidgets.QAction(MainWindow)
        self.action_title_slvs.setEnabled(False)
        self.action_title_slvs.setObjectName("action_title_slvs")
        self.action_title_dxf = QtWidgets.QAction(MainWindow)
        self.action_title_dxf.setEnabled(False)
        self.action_title_dxf.setObjectName("action_title_dxf")
        self.action_title_other = QtWidgets.QAction(MainWindow)
        self.action_title_other.setEnabled(False)
        self.action_title_other.setObjectName("action_title_other")
        self.action_import_database = QtWidgets.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/icons/loadfile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_import_database.setIcon(icon29)
        self.action_import_database.setObjectName("action_import_database")
        self.action_about_qt = QtWidgets.QAction(MainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/icons/qt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about_qt.setIcon(icon30)
        self.action_about_qt.setObjectName("action_about_qt")
        self.action_load_file = QtWidgets.QAction(MainWindow)
        self.action_load_file.setIcon(icon29)
        self.action_load_file.setObjectName("action_load_file")
        self.action_zoom_to_fit = QtWidgets.QAction(MainWindow)
        self.action_zoom_to_fit.setIcon(icon15)
        self.action_zoom_to_fit.setObjectName("action_zoom_to_fit")
        self.action_path_style = QtWidgets.QAction(MainWindow)
        self.action_path_style.setCheckable(True)
        self.action_path_style.setChecked(True)
        self.action_path_style.setObjectName("action_path_style")
        self.action_pyslvs_com = QtWidgets.QAction(MainWindow)
        self.action_pyslvs_com.setIcon(icon)
        self.action_pyslvs_com.setObjectName("action_pyslvs_com")
        self.action_show_console = QtWidgets.QAction(MainWindow)
        self.action_show_console.setCheckable(True)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/icons/konsole.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_show_console.setIcon(icon31)
        self.action_show_console.setObjectName("action_show_console")
        self.action_export_pmks_url = QtWidgets.QAction(MainWindow)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/icons/pmks.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_export_pmks_url.setIcon(icon32)
        self.action_export_pmks_url.setObjectName("action_export_pmks_url")
        self.action_import_pmks_url = QtWidgets.QAction(MainWindow)
        self.action_import_pmks_url.setIcon(icon32)
        self.action_import_pmks_url.setObjectName("action_import_pmks_url")
        self.action_example = QtWidgets.QAction(MainWindow)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/icons/example.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_example.setIcon(icon33)
        self.action_example.setObjectName("action_example")
        self.action_exprsion = QtWidgets.QAction(MainWindow)
        self.action_exprsion.setIcon(icon26)
        self.action_exprsion.setObjectName("action_exprsion")
        self.action_commit_branch = QtWidgets.QAction(MainWindow)
        self.action_commit_branch.setIcon(icon13)
        self.action_commit_branch.setObjectName("action_commit_branch")
        self.action_stash = QtWidgets.QAction(MainWindow)
        self.action_stash.setIcon(icon8)
        self.action_stash.setObjectName("action_stash")
        self.action_import_example = QtWidgets.QAction(MainWindow)
        self.action_import_example.setIcon(icon33)
        self.action_import_example.setObjectName("action_import_example")
        self.action_export_image_clipboard = QtWidgets.QAction(MainWindow)
        self.action_export_image_clipboard.setIcon(icon25)
        self.action_export_image_clipboard.setObjectName("action_export_image_clipboard")
        self.action_check_update = QtWidgets.QAction(MainWindow)
        self.action_check_update.setObjectName("action_check_update")
        self.action_new_window = QtWidgets.QAction(MainWindow)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/icons/new_window.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_new_window.setIcon(icon34)
        self.action_new_window.setObjectName("action_new_window")
        self.action_scale_points = QtWidgets.QAction(MainWindow)
        self.action_scale_points.setObjectName("action_scale_points")
        self.action_save = QtWidgets.QAction(MainWindow)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/icons/yaml.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save.setIcon(icon35)
        self.action_save.setObjectName("action_save")
        self.action_save_as = QtWidgets.QAction(MainWindow)
        self.action_save_as.setIcon(icon35)
        self.action_save_as.setObjectName("action_save_as")
        self.action_documentation = QtWidgets.QAction(MainWindow)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/icons/collections.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_documentation.setIcon(icon36)
        self.action_documentation.setObjectName("action_documentation")
        self.action_set_link_length = QtWidgets.QAction(MainWindow)
        self.action_set_link_length.setObjectName("action_set_link_length")
        self.menu_export.addAction(self.action_export_dxf)
        self.menu_export.addAction(self.action_export_slvs)
        self.menu_export.addAction(self.action_export_pmks_url)
        self.menu_export.addAction(self.action_python_script)
        self.menu_export.addSeparator()
        self.menu_export.addAction(self.action_export_image)
        self.menu_export.addAction(self.action_export_image_clipboard)
        self.menu_import.addAction(self.action_import_pmks_url)
        self.menu_import.addAction(self.action_import_example)
        self.menu_import.addAction(self.action_import_database)
        self.menu_file.addAction(self.action_new_workbook)
        self.menu_file.addAction(self.action_load_file)
        self.menu_file.addAction(self.action_example)
        self.menu_file.addAction(self.menu_import.menuAction())
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_save_as)
        self.menu_file.addAction(self.menu_export.menuAction())
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_commit)
        self.menu_file.addAction(self.action_commit_branch)
        self.menu_file.addAction(self.action_commit_as)
        self.menu_file.addAction(self.action_stash)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_full_screen)
        self.menu_file.addAction(self.action_new_window)
        self.menu_file.addAction(self.action_exit)
        self.menu_mechanism.addAction(self.action_new_point)
        self.menu_mechanism.addAction(self.action_new_link)
        self.menu_mechanism.addSeparator()
        self.menu_mechanism.addAction(self.action_edit_point)
        self.menu_mechanism.addAction(self.action_edit_link)
        self.menu_mechanism.addSeparator()
        self.menu_mechanism.addAction(self.action_delete_point)
        self.menu_mechanism.addAction(self.action_delete_link)
        self.menu_mechanism.addSeparator()
        self.menu_mechanism.addAction(self.action_scale_points)
        self.menu_mechanism.addAction(self.action_set_link_length)
        self.menu_options.addAction(self.action_show_console)
        self.menu_options.addSeparator()
        self.menu_options.addAction(self.action_zoom_to_fit)
        self.menu_options.addAction(self.action_show_point_mark)
        self.menu_options.addAction(self.action_show_dimensions)
        self.menu_options.addAction(self.action_path_style)
        self.menu_options.addSeparator()
        self.menu_options.addAction(self.action_exprsion)
        self.menu_help.addAction(self.action_pyslvs_com)
        self.menu_help.addAction(self.action_github_repository)
        self.menu_help.addAction(self.action_documentation)
        self.menu_help.addAction(self.action_mde_tw)
        self.menu_help.addSeparator()
        self.menu_help.addAction(self.action_check_update)
        self.menu_help.addSeparator()
        self.menu_help.addAction(self.action_about_qt)
        self.menu_help.addAction(self.action_about)
        self.menu_bar.addAction(self.menu_file.menuAction())
        self.menu_bar.addAction(self.menu_edit.menuAction())
        self.menu_bar.addAction(self.menu_mechanism.menuAction())
        self.menu_bar.addAction(self.menu_options.menuAction())
        self.menu_bar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        self.synthesis_tab_widget.setCurrentIndex(-1)
        self.action_exit.triggered.connect(MainWindow.close)
        self.action_show_console.toggled['bool'].connect(self.console_widget.setVisible)
        self.clearConsole.clicked.connect(self.console_widget_browser.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pyslvs - Untitled"))
        self.entities_tab.setTabText(self.entities_tab.indexOf(self.PointsTab), _translate("MainWindow", "Points"))
        self.entities_tab.setTabText(self.entities_tab.indexOf(self.LinksTab), _translate("MainWindow", "Links"))
        self.entities_tab.setTabText(self.entities_tab.indexOf(self.tab), _translate("MainWindow", "Formulas"))
        self.mechanism_storage_name_tag_text.setText(_translate("MainWindow", "Mechanism name:"))
        self.mechanism_storage_name_tag.setPlaceholderText(_translate("MainWindow", "Prototype"))
        self.mechanism_storage.setStatusTip(_translate("MainWindow", "All expressions of this workbook. They will be saving with database."))
        self.mechanism_storage_add.setStatusTip(_translate("MainWindow", "Capture the current expression then save to the list."))
        self.mechanism_storage_add.setText(_translate("MainWindow", "Add"))
        self.mechanism_storage_restore.setStatusTip(_translate("MainWindow", "Restore the selected expression."))
        self.mechanism_storage_restore.setText(_translate("MainWindow", "Restore"))
        self.mechanism_storage_copy.setStatusTip(_translate("MainWindow", "Copy the specified mechanism expression as string format."))
        self.mechanism_storage_copy.setText(_translate("MainWindow", "Copy"))
        self.mechanism_storage_paste.setStatusTip(_translate("MainWindow", "Append a new expression to list by string format."))
        self.mechanism_storage_paste.setText(_translate("MainWindow", "Paste"))
        self.mechanism_storage_delete.setStatusTip(_translate("MainWindow", "Delete the specified mechanism."))
        self.mechanism_storage_delete.setText(_translate("MainWindow", "Delete"))
        self.main_panel.setTabText(self.main_panel.indexOf(self.mechanism_tab), _translate("MainWindow", "Mechanism"))
        self.main_panel.setTabText(self.main_panel.indexOf(self.inputs_tab), _translate("MainWindow", "Inputs"))
        self.main_panel.setTabText(self.main_panel.indexOf(self.synthesis_tab), _translate("MainWindow", "Synthesis"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>This action list will build your mechanism from data base.</p><p>If you want to view the workbook history, please switch to the version control tab.</p><p>You can backtracking commands by clicking them below.</p></body></html>"))
        self.main_panel.setTabText(self.main_panel.indexOf(self.history_tab), _translate("MainWindow", "History"))
        self.main_panel.setTabText(self.main_panel.indexOf(self.version_control_tab), _translate("MainWindow", "Version Control"))
        self.settings_ui_groupbox.setTitle(_translate("MainWindow", "Main canvas"))
        self.linewidth_label.setText(_translate("MainWindow", "Line width"))
        self.fontsize_label.setText(_translate("MainWindow", "Font size"))
        self.pathwidth_label.setText(_translate("MainWindow", "Path width"))
        self.scalefactor_label.setText(_translate("MainWindow", "Scale factor"))
        self.selectionradius_label.setText(_translate("MainWindow", "Selection radius"))
        self.linktransparency_label.setText(_translate("MainWindow", "Link transparency"))
        self.link_trans_option.setSuffix(_translate("MainWindow", " %"))
        self.marginfactor_label.setText(_translate("MainWindow", "Margin of \"zoom to fit\""))
        self.margin_factor_option.setSuffix(_translate("MainWindow", "%"))
        self.jointsize_label.setText(_translate("MainWindow", "Joint annotation size (diameter)"))
        self.zoomby_label.setText(_translate("MainWindow", "Center zooming by"))
        self.zoom_by_option.setItemText(0, _translate("MainWindow", "Cursor"))
        self.zoom_by_option.setItemText(1, _translate("MainWindow", "Cavas center"))
        self.snap_label.setText(_translate("MainWindow", "Snap the mouse when dragging"))
        self.background_label.setText(_translate("MainWindow", "Background"))
        self.background_choose_dir.setText(_translate("MainWindow", "..."))
        self.background_opacity_label.setText(_translate("MainWindow", "Background opacity"))
        self.background_scale_label.setText(_translate("MainWindow", "Background scale"))
        self.background_offset_label.setText(_translate("MainWindow", "Background offset"))
        self.settings_history_groupbox.setTitle(_translate("MainWindow", "History"))
        self.UndoLimit_label.setText(_translate("MainWindow", "Undo limit"))
        self.undo_limit_option.setSuffix(_translate("MainWindow", " times"))
        self.settings_kernels_groupBox.setTitle(_translate("MainWindow", "Kernels"))
        self.planarsolver_label.setText(_translate("MainWindow", "Planar solving:"))
        self.pathpreview_label.setText(_translate("MainWindow", "Path preview:"))
        self.settings_misc_groupBox.setTitle(_translate("MainWindow", "Misc"))
        self.title_full_path_option.setText(_translate("MainWindow", "Show full file path on window title."))
        self.console_error_option.setText(_translate("MainWindow", "Show error messages in the console."))
        self.monochrome_option.setText(_translate("MainWindow", "Monochrome mode for mechanism. (Excluding indicators)"))
        self.dontsave_option.setText(_translate("MainWindow", "Do not save Pyslvs option."))
        self.settings_reset.setText(_translate("MainWindow", "Restore Defaults"))
        self.main_panel.setTabText(self.main_panel.indexOf(self.settings_tab), _translate("MainWindow", "Settings"))
        self.zoom_bar.setStatusTip(_translate("MainWindow", "Adjust the slider to change demo size."))
        self.zoom_button.setText(_translate("MainWindow", "200%"))
        self.ResetCanvas.setStatusTip(_translate("MainWindow", "Zoom to fit."))
        self.free_move_button.setStatusTip(_translate("MainWindow", "Free mode: Allow selected point coordinates to be edited by drag and drop."))
        self.DOFLable.setToolTip(_translate("MainWindow", "Degree of Freedom"))
        self.DOFLable.setText(_translate("MainWindow", "DOF:"))
        self.conflict.setStatusTip(_translate("MainWindow", "Show Conflict Guide tool tips."))
        self.conflict.setText(_translate("MainWindow", "<html><head/><body><p><img width=\'30\' src=\":/icons/conflict.png\"/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img width=\'30\' src=\":/icons/konsole.png\"/></p></body></html>"))
        self.console_disconnect_button.setStatusTip(_translate("MainWindow", "Disconnect from GUI console."))
        self.console_connect_button.setStatusTip(_translate("MainWindow", "Connect to GUI console."))
        self.clearConsole.setStatusTip(_translate("MainWindow", "Clear GUI console."))
        self.menu_file.setTitle(_translate("MainWindow", "&File"))
        self.menu_export.setStatusTip(_translate("MainWindow", "Export to other format."))
        self.menu_export.setTitle(_translate("MainWindow", "E&xport"))
        self.menu_import.setTitle(_translate("MainWindow", "&Import"))
        self.menu_mechanism.setTitle(_translate("MainWindow", "&Mechanism"))
        self.menu_options.setTitle(_translate("MainWindow", "&Options"))
        self.menu_help.setTitle(_translate("MainWindow", "&Help"))
        self.menu_edit.setTitle(_translate("MainWindow", "&Edit"))
        self.action_new_workbook.setText(_translate("MainWindow", "&New Workbook"))
        self.action_new_workbook.setStatusTip(_translate("MainWindow", "Reset to a new wrokbook."))
        self.action_new_workbook.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_new_point.setText(_translate("MainWindow", "New &Point"))
        self.action_new_point.setStatusTip(_translate("MainWindow", "Add a new point representative of a node on a machine."))
        self.action_new_point.setShortcut(_translate("MainWindow", "P"))
        self.action_new_link.setText(_translate("MainWindow", "New &Link"))
        self.action_new_link.setStatusTip(_translate("MainWindow", "Add  a link between two points."))
        self.action_new_link.setShortcut(_translate("MainWindow", "L"))
        self.action_exit.setText(_translate("MainWindow", "&Quit"))
        self.action_exit.setStatusTip(_translate("MainWindow", "Exit Pyslvs."))
        self.action_mde_tw.setText(_translate("MainWindow", "&MDE.tw"))
        self.action_mde_tw.setStatusTip(_translate("MainWindow", "Goto Kmolab learn about more."))
        self.action_github_repository.setText(_translate("MainWindow", "Git&hub Repository"))
        self.action_github_repository.setStatusTip(_translate("MainWindow", "Goto Github storage of Pyslvs."))
        self.action_about.setText(_translate("MainWindow", "&About Pyslvs"))
        self.action_about.setStatusTip(_translate("MainWindow", "Version and introduction of Pyslvs."))
        self.action_about.setShortcut(_translate("MainWindow", "F1"))
        self.action_full_screen.setText(_translate("MainWindow", "Full Screen"))
        self.action_full_screen.setStatusTip(_translate("MainWindow", "Let the window truns to full screen."))
        self.action_full_screen.setShortcut(_translate("MainWindow", "Shift+F1"))
        self.action_export_image.setText(_translate("MainWindow", "&Image"))
        self.action_export_image.setStatusTip(_translate("MainWindow", "Capture and output to image format."))
        self.action_export_image.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.action_commit.setText(_translate("MainWindow", "&Commit"))
        self.action_commit.setToolTip(_translate("MainWindow", "Save"))
        self.action_commit.setStatusTip(_translate("MainWindow", "Save the workbook."))
        self.action_python_script.setText(_translate("MainWindow", "Python &Script"))
        self.action_python_script.setStatusTip(_translate("MainWindow", "Generate a Python scripts from the workbook."))
        self.action_delete_point.setText(_translate("MainWindow", "Delete Point"))
        self.action_delete_point.setStatusTip(_translate("MainWindow", "Delete an existing point."))
        self.action_delete_link.setText(_translate("MainWindow", "Delete Link"))
        self.action_delete_link.setStatusTip(_translate("MainWindow", "Delete an existing link."))
        self.action_edit_point.setText(_translate("MainWindow", "Edit Point"))
        self.action_edit_point.setStatusTip(_translate("MainWindow", "Edit an existing point."))
        self.action_edit_link.setText(_translate("MainWindow", "Edit Link"))
        self.action_edit_link.setStatusTip(_translate("MainWindow", "Edit an existing link."))
        self.action_show_dimensions.setText(_translate("MainWindow", "Display &Dimensions"))
        self.action_show_dimensions.setStatusTip(_translate("MainWindow", "Display dimensions in the canvas."))
        self.action_show_dimensions.setShortcut(_translate("MainWindow", "F11"))
        self.action_show_point_mark.setText(_translate("MainWindow", "Display Point &Mark"))
        self.action_show_point_mark.setStatusTip(_translate("MainWindow", "Display point mark in canvas."))
        self.action_show_point_mark.setShortcut(_translate("MainWindow", "F10"))
        self.action_export_dxf.setText(_translate("MainWindow", "&DXF"))
        self.action_export_dxf.setStatusTip(_translate("MainWindow", "Output to Drawing Exchange sketch."))
        self.action_commit_as.setText(_translate("MainWindow", "Commit As ..."))
        self.action_commit_as.setStatusTip(_translate("MainWindow", "Save to another workbook."))
        self.action_export_slvs.setText(_translate("MainWindow", "Solvespace Parts"))
        self.action_export_slvs.setStatusTip(_translate("MainWindow", "Output to Solvespace 2D sketch."))
        self.action_title_slvs.setText(_translate("MainWindow", "Solvespace"))
        self.action_title_dxf.setText(_translate("MainWindow", "DXF"))
        self.action_title_other.setText(_translate("MainWindow", "Other Format"))
        self.action_import_database.setText(_translate("MainWindow", "From Workbook"))
        self.action_import_database.setStatusTip(_translate("MainWindow", "Import from workbook."))
        self.action_about_qt.setText(_translate("MainWindow", "About Qt"))
        self.action_about_qt.setStatusTip(_translate("MainWindow", "Show Qt about."))
        self.action_load_file.setText(_translate("MainWindow", "L&oad File"))
        self.action_load_file.setStatusTip(_translate("MainWindow", "Load Workbook from *.pyslvs database or *.slvs file."))
        self.action_load_file.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_zoom_to_fit.setText(_translate("MainWindow", "Zoom to Fit"))
        self.action_zoom_to_fit.setStatusTip(_translate("MainWindow", "Zoom in as mechanism size."))
        self.action_zoom_to_fit.setShortcut(_translate("MainWindow", "Home"))
        self.action_path_style.setText(_translate("MainWindow", "Solid Style Path"))
        self.action_path_style.setStatusTip(_translate("MainWindow", "Show path in solid line style, otherwise will be isolated dots."))
        self.action_pyslvs_com.setText(_translate("MainWindow", "&Pyslvs.com"))
        self.action_pyslvs_com.setStatusTip(_translate("MainWindow", "Goto Pyslvs home page."))
        self.action_show_console.setText(_translate("MainWindow", "Show GUI Console"))
        self.action_show_console.setStatusTip(_translate("MainWindow", "Open a widget to show console output."))
        self.action_show_console.setShortcut(_translate("MainWindow", "F12"))
        self.action_export_pmks_url.setText(_translate("MainWindow", "&PMKS URL"))
        self.action_export_pmks_url.setStatusTip(_translate("MainWindow", "Pass your mechanism to PMKS server by generate a URL."))
        self.action_import_pmks_url.setText(_translate("MainWindow", "From PMKS server"))
        self.action_import_pmks_url.setStatusTip(_translate("MainWindow", "Import from PMKS URL."))
        self.action_example.setText(_translate("MainWindow", "Example ..."))
        self.action_example.setStatusTip(_translate("MainWindow", "Load a example."))
        self.action_example.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.action_exprsion.setText(_translate("MainWindow", "Mechanism Expression"))
        self.action_exprsion.setStatusTip(_translate("MainWindow", "Get the Pyslvs expression."))
        self.action_commit_branch.setText(_translate("MainWindow", "Commit with New Branch"))
        self.action_commit_branch.setStatusTip(_translate("MainWindow", "Creat a new branch then save the commit to this branch."))
        self.action_stash.setText(_translate("MainWindow", "Stash"))
        self.action_stash.setStatusTip(_translate("MainWindow", "Abandon all changes of this time, and return to the latest commit."))
        self.action_import_example.setText(_translate("MainWindow", "From Example"))
        self.action_import_example.setStatusTip(_translate("MainWindow", "Import from example"))
        self.action_export_image_clipboard.setText(_translate("MainWindow", "&Capture to Clipboard"))
        self.action_export_image_clipboard.setStatusTip(_translate("MainWindow", "Capture and output to clipboard."))
        self.action_export_image_clipboard.setShortcut(_translate("MainWindow", "Ctrl+Shift+P"))
        self.action_check_update.setText(_translate("MainWindow", "Check for Updates"))
        self.action_check_update.setStatusTip(_translate("MainWindow", "Check the lastest version of Pyslvs from Github."))
        self.action_new_window.setText(_translate("MainWindow", "New Window"))
        self.action_new_window.setStatusTip(_translate("MainWindow", "Open a new Pyslvs window."))
        self.action_scale_points.setText(_translate("MainWindow", "&Scale Mechanism"))
        self.action_scale_points.setStatusTip(_translate("MainWindow", "Scale the mechanism by specified factor."))
        self.action_save.setText(_translate("MainWindow", "Save"))
        self.action_save.setStatusTip(_translate("MainWindow", "Save to a YAML-based format."))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_save_as.setText(_translate("MainWindow", "Save &As ..."))
        self.action_save_as.setStatusTip(_translate("MainWindow", "Save to another YAML file."))
        self.action_save_as.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.action_documentation.setText(_translate("MainWindow", "Documentation"))
        self.action_documentation.setStatusTip(_translate("MainWindow", "See the documentation on Readthedocs."))
        self.action_set_link_length.setText(_translate("MainWindow", "Set Link &Length"))
import icons_rc
