# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ahshoe\Desktop\Pyslvs-PyQt5\core\io\dxfType.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(507, 612)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(507, 612))
        Dialog.setMaximumSize(QtCore.QSize(507, 612))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/bezier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.general = QtWidgets.QWidget()
        self.general.setObjectName("general")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.general)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalWidget = QtWidgets.QWidget(self.general)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.verticalWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.folderPath = QtWidgets.QLabel(self.groupBox)
        self.folderPath.setObjectName("folderPath")
        self.horizontalLayout_2.addWidget(self.folderPath)
        self.setPath = QtWidgets.QToolButton(self.groupBox)
        self.setPath.setObjectName("setPath")
        self.horizontalLayout_2.addWidget(self.setPath)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.pointWarning = QtWidgets.QLabel(self.groupBox)
        self.pointWarning.setObjectName("pointWarning")
        self.verticalLayout_2.addWidget(self.pointWarning)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_4.addWidget(self.verticalWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tabWidget.addTab(self.general, "")
        self.appearance = QtWidgets.QWidget()
        self.appearance.setObjectName("appearance")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.appearance)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalWidget1 = QtWidgets.QWidget(self.appearance)
        self.verticalWidget1.setObjectName("verticalWidget1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalWidget1)
        self.verticalLayout_9.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_10 = QtWidgets.QGroupBox(self.verticalWidget1)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ScaleMolecular = QtWidgets.QSpinBox(self.groupBox_10)
        self.ScaleMolecular.setMinimum(1)
        self.ScaleMolecular.setMaximum(10000)
        self.ScaleMolecular.setProperty("value", 1)
        self.ScaleMolecular.setObjectName("ScaleMolecular")
        self.horizontalLayout_11.addWidget(self.ScaleMolecular)
        self.label_6 = QtWidgets.QLabel(self.groupBox_10)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.ScaleDenominator = QtWidgets.QSpinBox(self.groupBox_10)
        self.ScaleDenominator.setMinimum(1)
        self.ScaleDenominator.setMaximum(10000)
        self.ScaleDenominator.setObjectName("ScaleDenominator")
        self.horizontalLayout_11.addWidget(self.ScaleDenominator)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.label_4 = QtWidgets.QLabel(self.groupBox_10)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.ThicknessVal = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.ThicknessVal.setMinimum(0.01)
        self.ThicknessVal.setProperty("value", 5.0)
        self.ThicknessVal.setObjectName("ThicknessVal")
        self.horizontalLayout_12.addWidget(self.ThicknessVal)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.label_15 = QtWidgets.QLabel(self.groupBox_10)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.DrillingVal = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.DrillingVal.setMinimum(0.01)
        self.DrillingVal.setProperty("value", 6.0)
        self.DrillingVal.setObjectName("DrillingVal")
        self.horizontalLayout_17.addWidget(self.DrillingVal)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.formLayout_3.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.verticalLayout_6.addLayout(self.formLayout_3)
        self.verticalLayout_9.addWidget(self.groupBox_10)
        self.groupBox_7 = QtWidgets.QGroupBox(self.verticalWidget1)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.LinkType = QtWidgets.QComboBox(self.groupBox_7)
        self.LinkType.setObjectName("LinkType")
        self.LinkType.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LinkType)
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.LinkWidthVal = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.LinkWidthVal.setMinimum(0.01)
        self.LinkWidthVal.setProperty("value", 8.0)
        self.LinkWidthVal.setObjectName("LinkWidthVal")
        self.horizontalLayout_13.addWidget(self.LinkWidthVal)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.horizontalLayout_15.addLayout(self.formLayout_4)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_7.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.LinkImage = QtWidgets.QLabel(self.groupBox_11)
        self.LinkImage.setText("")
        self.LinkImage.setObjectName("LinkImage")
        self.verticalLayout_7.addWidget(self.LinkImage)
        self.horizontalLayout_15.addWidget(self.groupBox_11)
        self.verticalLayout_9.addWidget(self.groupBox_7)
        self.groupBox_9 = QtWidgets.QGroupBox(self.verticalWidget1)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_12 = QtWidgets.QLabel(self.groupBox_9)
        self.label_12.setObjectName("label_12")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.ChainType = QtWidgets.QComboBox(self.groupBox_9)
        self.ChainType.setObjectName("ChainType")
        self.ChainType.addItem("")
        self.ChainType.addItem("")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ChainType)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.ChainWidthVal = QtWidgets.QDoubleSpinBox(self.groupBox_9)
        self.ChainWidthVal.setMinimum(0.01)
        self.ChainWidthVal.setProperty("value", 8.0)
        self.ChainWidthVal.setObjectName("ChainWidthVal")
        self.horizontalLayout_14.addWidget(self.ChainWidthVal)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.formLayout_5.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_14)
        self.label_14 = QtWidgets.QLabel(self.groupBox_9)
        self.label_14.setObjectName("label_14")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout_16.addLayout(self.formLayout_5)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_8.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ChainImage = QtWidgets.QLabel(self.groupBox_12)
        self.ChainImage.setText("")
        self.ChainImage.setObjectName("ChainImage")
        self.verticalLayout_8.addWidget(self.ChainImage)
        self.horizontalLayout_16.addWidget(self.groupBox_12)
        self.verticalLayout_9.addWidget(self.groupBox_9)
        spacerItem6 = QtWidgets.QSpacerItem(20, 180, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem6)
        self.verticalLayout_10.addWidget(self.verticalWidget1)
        self.tabWidget.addTab(self.appearance, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.accepted.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "DXF models"))
        self.groupBox.setTitle(_translate("Dialog", "Files"))
        self.label.setText(_translate("Dialog", "File name: "))
        self.folderPath.setText(_translate("Dialog", "path"))
        self.setPath.setText(_translate("Dialog", "..."))
        self.pointWarning.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; color:#ff0000;\">※No-entity-associated points will not be rendered.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general), _translate("Dialog", "General"))
        self.groupBox_10.setTitle(_translate("Dialog", "Entire"))
        self.label_2.setText(_translate("Dialog", "Scale: "))
        self.label_6.setText(_translate("Dialog", " / "))
        self.label_4.setText(_translate("Dialog", "Thickness: "))
        self.label_15.setText(_translate("Dialog", "Drilling size: "))
        self.groupBox_7.setTitle(_translate("Dialog", "Links"))
        self.label_8.setText(_translate("Dialog", "Type: "))
        self.LinkType.setItemText(0, _translate("Dialog", "Round connecting rod"))
        self.label_10.setText(_translate("Dialog", "Fillet diameter: "))
        self.groupBox_11.setTitle(_translate("Dialog", "Preview"))
        self.groupBox_9.setTitle(_translate("Dialog", "Chains"))
        self.label_12.setText(_translate("Dialog", "Type: "))
        self.ChainType.setItemText(0, _translate("Dialog", "Sheet"))
        self.ChainType.setItemText(1, _translate("Dialog", "Frame"))
        self.label_14.setText(_translate("Dialog", "Fillet diameter: "))
        self.groupBox_12.setTitle(_translate("Dialog", "Preview"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.appearance), _translate("Dialog", "Appearance"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

