# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/io/overview.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from core.QtModules import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(442, 544)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(True)
        self.verticalLayout = QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QToolBox(Dialog)
        self.toolBox.setObjectName("toolBox")
        self.page0 = QWidget()
        self.page0.setGeometry(QRect(0, 0, 424, 329))
        self.page0.setObjectName("page0")
        self.verticalLayout_2 = QVBoxLayout(self.page0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.storage_label = QLabel(self.page0)
        self.storage_label.setObjectName("storage_label")
        self.verticalLayout_2.addWidget(self.storage_label)
        self.storage_list = QListWidget(self.page0)
        self.storage_list.setObjectName("storage_list")
        self.verticalLayout_2.addWidget(self.storage_list)
        icon = QIcon()
        icon.addPixmap(QPixmap(":/icons/mechanism.png"), QIcon.Normal, QIcon.Off)
        self.toolBox.addItem(self.page0, icon, "")
        self.page1 = QWidget()
        self.page1.setGeometry(QRect(0, 0, 171, 121))
        self.page1.setObjectName("page1")
        self.horizontalLayout_2 = QHBoxLayout(self.page1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.variables_label = QLabel(self.page1)
        self.variables_label.setObjectName("variables_label")
        self.verticalLayout_3.addWidget(self.variables_label)
        self.variables_list = QListWidget(self.page1)
        self.variables_list.setObjectName("variables_list")
        self.verticalLayout_3.addWidget(self.variables_list)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.records_label = QLabel(self.page1)
        self.records_label.setObjectName("records_label")
        self.verticalLayout_4.addWidget(self.records_label)
        self.records_list = QListWidget(self.page1)
        self.records_list.setObjectName("records_list")
        self.verticalLayout_4.addWidget(self.records_list)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(":/icons/motor.png"), QIcon.Normal, QIcon.Off)
        self.toolBox.addItem(self.page1, icon1, "")
        self.page2 = QWidget()
        self.page2.setGeometry(QRect(0, 0, 259, 121))
        self.page2.setObjectName("page2")
        self.horizontalLayout_3 = QHBoxLayout(self.page2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.structures_label = QLabel(self.page2)
        self.structures_label.setObjectName("structures_label")
        self.verticalLayout_6.addWidget(self.structures_label)
        self.structures_list = QListWidget(self.page2)
        self.structures_list.setObjectName("structures_list")
        self.verticalLayout_6.addWidget(self.structures_list)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.triangular_iteration_label = QLabel(self.page2)
        self.triangular_iteration_label.setObjectName("triangular_iteration_label")
        self.verticalLayout_5.addWidget(self.triangular_iteration_label)
        self.triangular_iteration_list = QListWidget(self.page2)
        self.triangular_iteration_list.setObjectName("triangular_iteration_list")
        self.verticalLayout_5.addWidget(self.triangular_iteration_list)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(":/icons/collections.png"), QIcon.Normal, QIcon.Off)
        self.toolBox.addItem(self.page2, icon2, "")
        self.page3 = QWidget()
        self.page3.setGeometry(QRect(0, 0, 98, 119))
        self.page3.setObjectName("page3")
        self.verticalLayout_7 = QVBoxLayout(self.page3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.results_label = QLabel(self.page3)
        self.results_label.setObjectName("results_label")
        self.verticalLayout_7.addWidget(self.results_label)
        self.results_list = QListWidget(self.page3)
        self.results_list.setObjectName("results_list")
        self.verticalLayout_7.addWidget(self.results_list)
        icon3 = QIcon()
        icon3.addPixmap(QPixmap(":/icons/DimensionalSynthesis.png"), QIcon.Normal, QIcon.Off)
        self.toolBox.addItem(self.page3, icon3, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_box = QDialogButtonBox(Dialog)
        self.button_box.setStandardButtons(QDialogButtonBox.Close)
        self.button_box.setObjectName("button_box")
        self.horizontalLayout.addWidget(self.button_box)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.button_box.rejected.connect(Dialog.reject)
        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QCoreApplication.translate
        self.storage_label.setText(_translate("Dialog", "Storage:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page0), _translate("Dialog", "Mechanism"))
        self.variables_label.setText(_translate("Dialog", "Variables:"))
        self.records_label.setText(_translate("Dialog", "Records:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page1), _translate("Dialog", "Inputs"))
        self.structures_label.setText(_translate("Dialog", "Structures:"))
        self.triangular_iteration_label.setText(_translate("Dialog", "Triangular iteration:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page2), _translate("Dialog", "Collections"))
        self.results_label.setText(_translate("Dialog", "Results:"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page3), _translate("Dialog", "Dimensional Synthesis"))


import icons_rc
