# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ahshoe/Desktop/Pyslvs-PyQt5/core/io/sqltable.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(595, 636)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CommitTable_text = QtWidgets.QLabel(Form)
        self.CommitTable_text.setObjectName("CommitTable_text")
        self.verticalLayout.addWidget(self.CommitTable_text)
        self.CommitTable = QtWidgets.QTableWidget(Form)
        self.CommitTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.CommitTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.CommitTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.CommitTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.CommitTable.setObjectName("CommitTable")
        self.CommitTable.setColumnCount(6)
        self.CommitTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.CommitTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CommitTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CommitTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CommitTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.CommitTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.CommitTable.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.CommitTable)
        self.AuthorList_text = QtWidgets.QLabel(Form)
        self.AuthorList_text.setObjectName("AuthorList_text")
        self.verticalLayout.addWidget(self.AuthorList_text)
        self.AuthorList = QtWidgets.QListWidget(Form)
        self.AuthorList.setObjectName("AuthorList")
        self.verticalLayout.addWidget(self.AuthorList)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FileAuthor_text = QtWidgets.QLabel(Form)
        self.FileAuthor_text.setObjectName("FileAuthor_text")
        self.horizontalLayout.addWidget(self.FileAuthor_text)
        self.FileAuthor = QtWidgets.QLineEdit(Form)
        self.FileAuthor.setObjectName("FileAuthor")
        self.horizontalLayout.addWidget(self.FileAuthor)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.FileDescription_text = QtWidgets.QLabel(Form)
        self.FileDescription_text.setObjectName("FileDescription_text")
        self.verticalLayout.addWidget(self.FileDescription_text)
        self.FileDescription = QtWidgets.QLineEdit(Form)
        self.FileDescription.setObjectName("FileDescription")
        self.verticalLayout.addWidget(self.FileDescription)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.commit_button = QtWidgets.QPushButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/git.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commit_button.setIcon(icon)
        self.commit_button.setObjectName("commit_button")
        self.horizontalLayout_4.addWidget(self.commit_button)
        self.branch_button = QtWidgets.QPushButton(Form)
        self.branch_button.setIcon(icon)
        self.branch_button.setObjectName("branch_button")
        self.horizontalLayout_4.addWidget(self.branch_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.stash_button = QtWidgets.QPushButton(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stash_button.setIcon(icon1)
        self.stash_button.setObjectName("stash_button")
        self.horizontalLayout_4.addWidget(self.stash_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CommitTable_text.setText(_translate("Form", "Commits:"))
        item = self.CommitTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.CommitTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Date"))
        item = self.CommitTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Description"))
        item = self.CommitTable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Author"))
        item = self.CommitTable.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Previous"))
        item = self.CommitTable.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Branch"))
        self.AuthorList_text.setText(_translate("Form", "Author list:"))
        self.FileAuthor_text.setText(_translate("Form", "Author:"))
        self.FileAuthor.setPlaceholderText(_translate("Form", "Anonymous"))
        self.FileDescription_text.setText(_translate("Form", "Description:"))
        self.FileDescription.setPlaceholderText(_translate("Form", "Explain what you have done here (required)."))
        self.commit_button.setText(_translate("Form", "Commit"))
        self.branch_button.setText(_translate("Form", "Branch"))
        self.stash_button.setText(_translate("Form", "Stash"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

