# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ahshoe/Desktop/Pyslvs-PyQt5/core/panel/DimensionalSynthesis/Path_Solving_options.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(409, 492)
        Dialog.setMinimumSize(QtCore.QSize(409, 492))
        Dialog.setMaximumSize(QtCore.QSize(409, 492))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/bezier.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.planarlinkage = QtWidgets.QWidget()
        self.planarlinkage.setObjectName("planarlinkage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.planarlinkage)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settingArea = QtWidgets.QScrollArea(self.planarlinkage)
        self.settingArea.setEnabled(True)
        self.settingArea.setWidgetResizable(True)
        self.settingArea.setObjectName("settingArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 418))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.report = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.report.setMinimum(1)
        self.report.setMaximum(10)
        self.report.setProperty("value", 1)
        self.report.setObjectName("report")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.report)
        self.maxGen = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.maxGen.setMinimum(1000)
        self.maxGen.setMaximum(10000)
        self.maxGen.setSingleStep(100)
        self.maxGen.setProperty("value", 1500)
        self.maxGen.setObjectName("maxGen")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.maxGen)
        self.horizontalLayout_7.addLayout(self.formLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.setDefault = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.setDefault.setObjectName("setDefault")
        self.horizontalLayout_7.addWidget(self.setDefault)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.limitPanel = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.limitPanel.setObjectName("limitPanel")
        self.gridLayout = QtWidgets.QGridLayout(self.limitPanel)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.AyMin = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.AyMin.setMinimum(-999.0)
        self.AyMin.setMaximum(999.0)
        self.AyMin.setProperty("value", -50.0)
        self.AyMin.setObjectName("AyMin")
        self.gridLayout.addWidget(self.AyMin, 2, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.limitPanel)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 1)
        self.DxMin = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.DxMin.setMinimum(-999.0)
        self.DxMin.setMaximum(999.0)
        self.DxMin.setProperty("value", -50.0)
        self.DxMin.setObjectName("DxMin")
        self.gridLayout.addWidget(self.DxMin, 3, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.limitPanel)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.LMin = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.LMin.setMinimum(0.01)
        self.LMin.setMaximum(999.0)
        self.LMin.setProperty("value", 5.0)
        self.LMin.setObjectName("LMin")
        self.gridLayout.addWidget(self.LMin, 6, 2, 1, 1)
        self.DxMax = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.DxMax.setMinimum(-999.0)
        self.DxMax.setMaximum(999.0)
        self.DxMax.setProperty("value", 50.0)
        self.DxMax.setObjectName("DxMax")
        self.gridLayout.addWidget(self.DxMax, 3, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.limitPanel)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.limitPanel)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.limitPanel)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.DyMin = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.DyMin.setMinimum(-999.0)
        self.DyMin.setMaximum(999.0)
        self.DyMin.setProperty("value", -50.0)
        self.DyMin.setObjectName("DyMin")
        self.gridLayout.addWidget(self.DyMin, 4, 2, 1, 1)
        self.LMax = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.LMax.setMinimum(0.01)
        self.LMax.setMaximum(999.0)
        self.LMax.setProperty("value", 50.0)
        self.LMax.setObjectName("LMax")
        self.gridLayout.addWidget(self.LMax, 6, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.limitPanel)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.limitPanel)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 8, 0, 1, 1)
        self.AxMax = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.AxMax.setMinimum(-999.0)
        self.AxMax.setMaximum(999.0)
        self.AxMax.setProperty("value", 50.0)
        self.AxMax.setObjectName("AxMax")
        self.gridLayout.addWidget(self.AxMax, 1, 3, 1, 1)
        self.AMin = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.AMin.setMinimum(0.0)
        self.AMin.setMaximum(359.99)
        self.AMin.setProperty("value", 0.0)
        self.AMin.setObjectName("AMin")
        self.gridLayout.addWidget(self.AMin, 8, 2, 1, 1)
        self.AMax = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.AMax.setMinimum(0.01)
        self.AMax.setMaximum(360.0)
        self.AMax.setProperty("value", 360.0)
        self.AMax.setObjectName("AMax")
        self.gridLayout.addWidget(self.AMax, 8, 3, 1, 1)
        self.AxMin = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.AxMin.setMinimum(-999.0)
        self.AxMin.setMaximum(999.0)
        self.AxMin.setProperty("value", -50.0)
        self.AxMin.setObjectName("AxMin")
        self.gridLayout.addWidget(self.AxMin, 1, 2, 1, 1)
        self.DyMax = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.DyMax.setMinimum(-999.0)
        self.DyMax.setMaximum(999.0)
        self.DyMax.setProperty("value", 50.0)
        self.DyMax.setObjectName("DyMax")
        self.gridLayout.addWidget(self.DyMax, 4, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.limitPanel)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.AyMax = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.AyMax.setMinimum(-999.0)
        self.AyMax.setMaximum(999.0)
        self.AyMax.setProperty("value", 50.0)
        self.AyMax.setObjectName("AyMax")
        self.gridLayout.addWidget(self.AyMax, 2, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.limitPanel)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 5, 0, 1, 1)
        self.IMin = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.IMin.setMinimum(0.01)
        self.IMin.setMaximum(999.0)
        self.IMin.setProperty("value", 5.0)
        self.IMin.setObjectName("IMin")
        self.gridLayout.addWidget(self.IMin, 5, 2, 1, 1)
        self.IMax = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.IMax.setMinimum(0.01)
        self.IMax.setMaximum(999.0)
        self.IMax.setProperty("value", 50.0)
        self.IMax.setObjectName("IMax")
        self.gridLayout.addWidget(self.IMax, 5, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.limitPanel)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 7, 0, 1, 1)
        self.FMin = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.FMin.setMinimum(0.01)
        self.FMin.setMaximum(999.0)
        self.FMin.setProperty("value", 5.0)
        self.FMin.setObjectName("FMin")
        self.gridLayout.addWidget(self.FMin, 7, 2, 1, 1)
        self.FMax = QtWidgets.QDoubleSpinBox(self.limitPanel)
        self.FMax.setMinimum(0.01)
        self.FMax.setMaximum(999.0)
        self.FMax.setProperty("value", 50.0)
        self.FMax.setObjectName("FMax")
        self.gridLayout.addWidget(self.FMax, 7, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.limitPanel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.settingArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.settingArea)
        self.tabWidget.addTab(self.planarlinkage, "")
        self.algorithm = QtWidgets.QWidget()
        self.algorithm.setObjectName("algorithm")
        self.tabWidget.addTab(self.algorithm, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Options"))
        self.label_17.setText(_translate("Dialog", "Report in every: "))
        self.label_16.setText(_translate("Dialog", "Max Generation: "))
        self.report.setSuffix(_translate("Dialog", "%"))
        self.setDefault.setText(_translate("Dialog", "Reset to Default"))
        self.label_12.setText(_translate("Dialog", "Connector: "))
        self.label_10.setText(_translate("Dialog", "Dx: "))
        self.label_11.setText(_translate("Dialog", "Dy: "))
        self.label_13.setText(_translate("Dialog", "Max"))
        self.label_9.setText(_translate("Dialog", "Ay: "))
        self.label_14.setText(_translate("Dialog", "Min"))
        self.label_15.setText(_translate("Dialog", "Angle (degree):"))
        self.label_8.setText(_translate("Dialog", "Ax: "))
        self.label_18.setText(_translate("Dialog", "Input:"))
        self.label_19.setText(_translate("Dialog", "Follower"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.planarlinkage), _translate("Dialog", "Planar Linkage"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.algorithm), _translate("Dialog", "Algorithm"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

