# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ahshoe/Desktop/Pyslvs-PyQt5/core/panel/DimensionalSynthesis/Path_Solving.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(489, 522)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.FourBar = QtWidgets.QRadioButton(Form)
        self.FourBar.setChecked(True)
        self.FourBar.setObjectName("FourBar")
        self.horizontalLayout_8.addWidget(self.FourBar)
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_8.addWidget(self.radioButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.timeShow = QtWidgets.QLabel(Form)
        self.timeShow.setObjectName("timeShow")
        self.horizontalLayout_8.addWidget(self.timeShow)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 469, 430))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_7.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pointNum = QtWidgets.QLabel(self.groupBox)
        self.pointNum.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pointNum.setObjectName("pointNum")
        self.horizontalLayout_2.addWidget(self.pointNum)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.Point_list = QtWidgets.QListWidget(self.groupBox)
        self.Point_list.setObjectName("Point_list")
        self.verticalLayout_2.addWidget(self.Point_list)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.X_coordinate = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.X_coordinate.sizePolicy().hasHeightForWidth())
        self.X_coordinate.setSizePolicy(sizePolicy)
        self.X_coordinate.setMinimum(-9999.99)
        self.X_coordinate.setMaximum(9999.99)
        self.X_coordinate.setObjectName("X_coordinate")
        self.horizontalLayout_3.addWidget(self.X_coordinate)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.Y_coordinate = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Y_coordinate.sizePolicy().hasHeightForWidth())
        self.Y_coordinate.setSizePolicy(sizePolicy)
        self.Y_coordinate.setMinimum(-9999.99)
        self.Y_coordinate.setMaximum(9999.99)
        self.Y_coordinate.setObjectName("Y_coordinate")
        self.horizontalLayout.addWidget(self.Y_coordinate)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.clearAll = QtWidgets.QPushButton(self.groupBox)
        self.clearAll.setAutoDefault(False)
        self.clearAll.setObjectName("clearAll")
        self.verticalLayout_3.addWidget(self.clearAll)
        self.series = QtWidgets.QPushButton(self.groupBox)
        self.series.setAutoDefault(False)
        self.series.setObjectName("series")
        self.verticalLayout_3.addWidget(self.series)
        spacerItem2 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.moveUp = QtWidgets.QPushButton(self.groupBox)
        self.moveUp.setAutoDefault(False)
        self.moveUp.setObjectName("moveUp")
        self.verticalLayout_3.addWidget(self.moveUp)
        self.moveDown = QtWidgets.QPushButton(self.groupBox)
        self.moveDown.setAutoDefault(False)
        self.moveDown.setObjectName("moveDown")
        self.verticalLayout_3.addWidget(self.moveDown)
        spacerItem3 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.remove = QtWidgets.QPushButton(self.groupBox)
        self.remove.setAutoDefault(False)
        self.remove.setObjectName("remove")
        self.verticalLayout_3.addWidget(self.remove)
        self.add = QtWidgets.QPushButton(self.groupBox)
        self.add.setAutoDefault(False)
        self.add.setObjectName("add")
        self.verticalLayout_3.addWidget(self.add)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.verticalGroupBox)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Result_list = QtWidgets.QListWidget(self.verticalGroupBox)
        self.Result_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.Result_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Result_list.setObjectName("Result_list")
        self.horizontalLayout_6.addWidget(self.Result_list)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.getTimeAndFitness = QtWidgets.QPushButton(self.verticalGroupBox)
        self.getTimeAndFitness.setObjectName("getTimeAndFitness")
        self.verticalLayout_6.addWidget(self.getTimeAndFitness)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.deleteButton = QtWidgets.QPushButton(self.verticalGroupBox)
        self.deleteButton.setEnabled(False)
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout_6.addWidget(self.deleteButton)
        self.mergeButton = QtWidgets.QPushButton(self.verticalGroupBox)
        self.mergeButton.setEnabled(False)
        self.mergeButton.setObjectName("mergeButton")
        self.verticalLayout_6.addWidget(self.mergeButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout.addWidget(self.verticalGroupBox)
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.type0 = QtWidgets.QRadioButton(self.verticalGroupBox_2)
        self.type0.setChecked(False)
        self.type0.setObjectName("type0")
        self.verticalLayout_4.addWidget(self.type0)
        self.type1 = QtWidgets.QRadioButton(self.verticalGroupBox_2)
        self.type1.setObjectName("type1")
        self.verticalLayout_4.addWidget(self.type1)
        self.type2 = QtWidgets.QRadioButton(self.verticalGroupBox_2)
        self.type2.setChecked(True)
        self.type2.setObjectName("type2")
        self.verticalLayout_4.addWidget(self.type2)
        self.advanceButton = QtWidgets.QPushButton(self.verticalGroupBox_2)
        self.advanceButton.setObjectName("advanceButton")
        self.verticalLayout_4.addWidget(self.advanceButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.verticalGroupBox_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.timePanel = QtWidgets.QWidget(Form)
        self.timePanel.setObjectName("timePanel")
        self.timePanelLayout = QtWidgets.QHBoxLayout(self.timePanel)
        self.timePanelLayout.setContentsMargins(6, 0, 6, 0)
        self.timePanelLayout.setObjectName("timePanelLayout")
        self.portText = QtWidgets.QLineEdit(self.timePanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portText.sizePolicy().hasHeightForWidth())
        self.portText.setSizePolicy(sizePolicy)
        self.portText.setObjectName("portText")
        self.timePanelLayout.addWidget(self.portText)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.timePanelLayout.addItem(spacerItem6)
        self.GenerateZMQ = QtWidgets.QPushButton(self.timePanel)
        self.GenerateZMQ.setMinimumSize(QtCore.QSize(100, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ZeroMQ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GenerateZMQ.setIcon(icon)
        self.GenerateZMQ.setAutoDefault(True)
        self.GenerateZMQ.setObjectName("GenerateZMQ")
        self.timePanelLayout.addWidget(self.GenerateZMQ)
        self.GenerateLocal = QtWidgets.QPushButton(self.timePanel)
        self.GenerateLocal.setMinimumSize(QtCore.QSize(100, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/local.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GenerateLocal.setIcon(icon1)
        self.GenerateLocal.setAutoDefault(True)
        self.GenerateLocal.setObjectName("GenerateLocal")
        self.timePanelLayout.addWidget(self.GenerateLocal)
        self.horizontalLayout_4.addWidget(self.timePanel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.FourBar.setText(_translate("Form", "Four-Bar"))
        self.radioButton.setText(_translate("Form", "Eight-Bar"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Time spent: </span></p></body></html>"))
        self.timeShow.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt\">[No record]</span></p></body></html>"))
        self.groupBox.setTitle(_translate("Form", "Path"))
        self.pointNum.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aa00;\">0</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aa00;\">Point(s)</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "x: "))
        self.label_4.setText(_translate("Form", "y: "))
        self.clearAll.setText(_translate("Form", "Clear All"))
        self.series.setText(_translate("Form", "Series..."))
        self.moveUp.setText(_translate("Form", "Move up"))
        self.moveDown.setText(_translate("Form", "Move down"))
        self.remove.setText(_translate("Form", "-"))
        self.add.setText(_translate("Form", "+"))
        self.verticalGroupBox.setTitle(_translate("Form", "Results"))
        self.getTimeAndFitness.setText(_translate("Form", "Chart"))
        self.deleteButton.setText(_translate("Form", "Delete"))
        self.mergeButton.setText(_translate("Form", "Merge"))
        self.verticalGroupBox_2.setTitle(_translate("Form", "Options"))
        self.type0.setText(_translate("Form", "Genetic Algorithm"))
        self.type1.setText(_translate("Form", "Firefly Algorithm"))
        self.type2.setText(_translate("Form", "Differential Evolution"))
        self.advanceButton.setText(_translate("Form", "Advance"))
        self.portText.setText(_translate("Form", "tcp://*:8000"))
        self.GenerateZMQ.setText(_translate("Form", "ZeroMQ Generate"))
        self.GenerateLocal.setText(_translate("Form", "Local Generate"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

