# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ahshoe/Desktop/Pyslvs-PyQt5/core/panel/DimensionalSynthesis/Path_Solving.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(553, 473)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_8.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 539, 420))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_7.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pointNum = QtWidgets.QLabel(self.horizontalWidget)
        self.pointNum.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pointNum.setObjectName("pointNum")
        self.horizontalLayout_2.addWidget(self.pointNum)
        self.label_5 = QtWidgets.QLabel(self.horizontalWidget)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.Point_list = QtWidgets.QListWidget(self.horizontalWidget)
        self.Point_list.setObjectName("Point_list")
        self.verticalLayout_2.addWidget(self.Point_list)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.horizontalWidget)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.X_coordinate = QtWidgets.QDoubleSpinBox(self.horizontalWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.X_coordinate.sizePolicy().hasHeightForWidth())
        self.X_coordinate.setSizePolicy(sizePolicy)
        self.X_coordinate.setMaximumSize(QtCore.QSize(60, 16777215))
        self.X_coordinate.setMinimum(-9999.99)
        self.X_coordinate.setMaximum(9999.99)
        self.X_coordinate.setObjectName("X_coordinate")
        self.horizontalLayout_12.addWidget(self.X_coordinate)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.Y_coordinate = QtWidgets.QDoubleSpinBox(self.horizontalWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Y_coordinate.sizePolicy().hasHeightForWidth())
        self.Y_coordinate.setSizePolicy(sizePolicy)
        self.Y_coordinate.setMaximumSize(QtCore.QSize(60, 16777215))
        self.Y_coordinate.setMinimum(-9999.99)
        self.Y_coordinate.setMaximum(9999.99)
        self.Y_coordinate.setObjectName("Y_coordinate")
        self.horizontalLayout_12.addWidget(self.Y_coordinate)
        self.verticalLayout_2.addWidget(self.horizontalWidget_2)
        self.horizontalLayout_13.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.clearAll = QtWidgets.QPushButton(self.horizontalWidget)
        self.clearAll.setAutoDefault(False)
        self.clearAll.setObjectName("clearAll")
        self.verticalLayout_3.addWidget(self.clearAll)
        self.series = QtWidgets.QPushButton(self.horizontalWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/formula.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.series.setIcon(icon)
        self.series.setAutoDefault(False)
        self.series.setObjectName("series")
        self.verticalLayout_3.addWidget(self.series)
        self.importCSV = QtWidgets.QPushButton(self.horizontalWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/CSV.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.importCSV.setIcon(icon1)
        self.importCSV.setObjectName("importCSV")
        self.verticalLayout_3.addWidget(self.importCSV)
        self.importXLSX = QtWidgets.QPushButton(self.horizontalWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/excel_2013.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.importXLSX.setIcon(icon2)
        self.importXLSX.setObjectName("importXLSX")
        self.verticalLayout_3.addWidget(self.importXLSX)
        spacerItem2 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.moveUp = QtWidgets.QPushButton(self.horizontalWidget)
        self.moveUp.setAutoDefault(False)
        self.moveUp.setObjectName("moveUp")
        self.verticalLayout_3.addWidget(self.moveUp)
        self.moveDown = QtWidgets.QPushButton(self.horizontalWidget)
        self.moveDown.setAutoDefault(False)
        self.moveDown.setObjectName("moveDown")
        self.verticalLayout_3.addWidget(self.moveDown)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.add = QtWidgets.QPushButton(self.horizontalWidget)
        self.add.setMaximumSize(QtCore.QSize(40, 16777215))
        self.add.setAutoDefault(False)
        self.add.setObjectName("add")
        self.horizontalLayout_11.addWidget(self.add)
        self.remove = QtWidgets.QPushButton(self.horizontalWidget)
        self.remove.setMaximumSize(QtCore.QSize(40, 16777215))
        self.remove.setAutoDefault(False)
        self.remove.setObjectName("remove")
        self.horizontalLayout_11.addWidget(self.remove)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addWidget(self.horizontalWidget)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_7.addWidget(self.line_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.Ar = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.Ar.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Ar.setMaximum(10000.0)
        self.Ar.setSingleStep(10.0)
        self.Ar.setProperty("value", 100.0)
        self.Ar.setObjectName("Ar")
        self.gridLayout.addWidget(self.Ar, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.Ax = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.Ax.setMaximumSize(QtCore.QSize(60, 16777215))
        self.Ax.setMinimum(-1000000.0)
        self.Ax.setMaximum(1000000.0)
        self.Ax.setSingleStep(10.0)
        self.Ax.setObjectName("Ax")
        self.gridLayout.addWidget(self.Ax, 0, 1, 1, 1)
        self.Ay = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.Ay.setMaximumSize(QtCore.QSize(60, 16777215))
        self.Ay.setMinimum(-1000000.0)
        self.Ay.setMaximum(1000000.0)
        self.Ay.setSingleStep(10.0)
        self.Ay.setObjectName("Ay")
        self.gridLayout.addWidget(self.Ay, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.Dx = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.Dx.setMaximumSize(QtCore.QSize(60, 16777215))
        self.Dx.setMinimum(-1000000.0)
        self.Dx.setMaximum(1000000.0)
        self.Dx.setSingleStep(10.0)
        self.Dx.setObjectName("Dx")
        self.gridLayout.addWidget(self.Dx, 1, 1, 1, 1)
        self.Dy = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.Dy.setMaximumSize(QtCore.QSize(60, 16777215))
        self.Dy.setMinimum(-1000000.0)
        self.Dy.setMaximum(1000000.0)
        self.Dy.setSingleStep(10.0)
        self.Dy.setObjectName("Dy")
        self.gridLayout.addWidget(self.Dy, 1, 2, 1, 1)
        self.Dr = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.Dr.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Dr.setMaximum(10000.0)
        self.Dr.setSingleStep(10.0)
        self.Dr.setProperty("value", 100.0)
        self.Dr.setObjectName("Dr")
        self.gridLayout.addWidget(self.Dr, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.verticalGroupBox)
        self.horizontalLayout_6.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Result_list = QtWidgets.QListWidget(self.verticalGroupBox)
        self.Result_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.Result_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Result_list.setObjectName("Result_list")
        self.horizontalLayout_6.addWidget(self.Result_list)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.getTimeAndFitness = QtWidgets.QPushButton(self.verticalGroupBox)
        self.getTimeAndFitness.setObjectName("getTimeAndFitness")
        self.verticalLayout_6.addWidget(self.getTimeAndFitness)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.deleteButton = QtWidgets.QPushButton(self.verticalGroupBox)
        self.deleteButton.setEnabled(False)
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout_6.addWidget(self.deleteButton)
        self.mergeButton = QtWidgets.QPushButton(self.verticalGroupBox)
        self.mergeButton.setEnabled(False)
        self.mergeButton.setObjectName("mergeButton")
        self.verticalLayout_6.addWidget(self.mergeButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout.addWidget(self.verticalGroupBox)
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Bar = QtWidgets.QWidget(self.verticalGroupBox_2)
        self.Bar.setObjectName("Bar")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.Bar)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.FourBar = QtWidgets.QRadioButton(self.Bar)
        self.FourBar.setChecked(True)
        self.FourBar.setObjectName("FourBar")
        self.horizontalLayout_8.addWidget(self.FourBar)
        self.radioButton = QtWidgets.QRadioButton(self.Bar)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_8.addWidget(self.radioButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_4.addWidget(self.Bar)
        self.line = QtWidgets.QFrame(self.verticalGroupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.verticalWidget = QtWidgets.QWidget(self.verticalGroupBox_2)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.type0 = QtWidgets.QRadioButton(self.verticalWidget)
        self.type0.setChecked(False)
        self.type0.setObjectName("type0")
        self.verticalLayout_5.addWidget(self.type0)
        self.type1 = QtWidgets.QRadioButton(self.verticalWidget)
        self.type1.setObjectName("type1")
        self.verticalLayout_5.addWidget(self.type1)
        self.type2 = QtWidgets.QRadioButton(self.verticalWidget)
        self.type2.setChecked(True)
        self.type2.setObjectName("type2")
        self.verticalLayout_5.addWidget(self.type2)
        self.verticalLayout_4.addWidget(self.verticalWidget)
        self.advanceButton = QtWidgets.QPushButton(self.verticalGroupBox_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/properties.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.advanceButton.setIcon(icon3)
        self.advanceButton.setObjectName("advanceButton")
        self.verticalLayout_4.addWidget(self.advanceButton)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.timeShow = QtWidgets.QLabel(self.verticalGroupBox_2)
        self.timeShow.setObjectName("timeShow")
        self.horizontalLayout_10.addWidget(self.timeShow)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.verticalLayout.addWidget(self.verticalGroupBox_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.timePanel = QtWidgets.QWidget(Form)
        self.timePanel.setObjectName("timePanel")
        self.timePanelLayout = QtWidgets.QHBoxLayout(self.timePanel)
        self.timePanelLayout.setContentsMargins(6, 0, 6, 0)
        self.timePanelLayout.setObjectName("timePanelLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.timePanel)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.portText = QtWidgets.QLineEdit(self.timePanel)
        self.portText.setObjectName("portText")
        self.horizontalLayout_9.addWidget(self.portText)
        self.timePanelLayout.addLayout(self.horizontalLayout_9)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.timePanelLayout.addItem(spacerItem9)
        self.GenerateZMQ = QtWidgets.QPushButton(self.timePanel)
        self.GenerateZMQ.setEnabled(False)
        self.GenerateZMQ.setMinimumSize(QtCore.QSize(100, 0))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/ZeroMQ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GenerateZMQ.setIcon(icon4)
        self.GenerateZMQ.setAutoDefault(True)
        self.GenerateZMQ.setObjectName("GenerateZMQ")
        self.timePanelLayout.addWidget(self.GenerateZMQ)
        self.GenerateLocal = QtWidgets.QPushButton(self.timePanel)
        self.GenerateLocal.setMinimumSize(QtCore.QSize(100, 0))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/local.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GenerateLocal.setIcon(icon5)
        self.GenerateLocal.setAutoDefault(True)
        self.GenerateLocal.setObjectName("GenerateLocal")
        self.timePanelLayout.addWidget(self.GenerateLocal)
        self.horizontalLayout_4.addWidget(self.timePanel)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.scrollArea.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.groupBox.setTitle(_translate("Form", "Path"))
        self.pointNum.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aa00;\">0</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; color:#00aa00;\">Point(s)</span></p></body></html>"))
        self.clearAll.setText(_translate("Form", "Clear All"))
        self.series.setText(_translate("Form", "Formula ..."))
        self.importCSV.setText(_translate("Form", "CSV ..."))
        self.importXLSX.setText(_translate("Form", "Excel ..."))
        self.moveUp.setText(_translate("Form", "Move up"))
        self.moveDown.setText(_translate("Form", "Move down"))
        self.add.setText(_translate("Form", "+"))
        self.remove.setText(_translate("Form", "-"))
        self.Ar.setPrefix(_translate("Form", "±"))
        self.label_2.setText(_translate("Form", "Driver: "))
        self.label_3.setText(_translate("Form", "Follower: "))
        self.Dr.setPrefix(_translate("Form", "±"))
        self.verticalGroupBox.setTitle(_translate("Form", "Results"))
        self.getTimeAndFitness.setText(_translate("Form", "Chart"))
        self.deleteButton.setText(_translate("Form", "Delete"))
        self.mergeButton.setText(_translate("Form", "Merge"))
        self.verticalGroupBox_2.setTitle(_translate("Form", "Options"))
        self.FourBar.setToolTip(_translate("Form", "<html><head/><body><h1>Four Bar</h1><img src=\":/icons/preview/4Bar_triangle.png\"/></body></html>"))
        self.FourBar.setText(_translate("Form", "Four Bar (?)"))
        self.radioButton.setToolTip(_translate("Form", "<html><head/><body><h1>Eight Bar</h1><img src=\":/icons/preview/8Bar_triangle.png\"/></body></html>"))
        self.radioButton.setText(_translate("Form", "Eight Bar (?)"))
        self.type0.setText(_translate("Form", "Genetic Algorithm [RGA]"))
        self.type1.setText(_translate("Form", "Firefly Algorithm [Firefly]"))
        self.type2.setText(_translate("Form", "Differential Evolution [DE]"))
        self.advanceButton.setText(_translate("Form", "Advance ..."))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Time spent: </span></p></body></html>"))
        self.timeShow.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt\">[No record]</span></p></body></html>"))
        self.label.setText(_translate("Form", "ZMQ filter: "))
        self.portText.setText(_translate("Form", "tcp://*:8000"))
        self.GenerateZMQ.setText(_translate("Form", "ZeroMQ Generate"))
        self.GenerateLocal.setText(_translate("Form", "Local Generate"))

import icons_rc
import preview_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

