# -*- coding: utf-8 -*-
from ..QtModules import *
from PyQt5.QtChart import *

class BasicChartDialog(QDialog):
    def __init__(self, Title, data=[0], parent=None):
        super(BasicChartDialog, self).__init__(parent)
        chart = QChart()
        chart.legend().hide()
        chart.setTitle(Title)
        chart.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        axisX = QCategoryAxis()
        axisY = QValueAxis()
        axisX.append('1st',  len(data)*1/4)
        axisX.append('2nd',  len(data)*2/4)
        axisX.append('3rd',  len(data)*3/4)
        axisX.append('4th',  len(data))
        chart.addAxis(axisX, Qt.AlignBottom)
        chart.addAxis(axisY, Qt.AlignLeft)
        series = QSplineSeries()
        for i, e in enumerate(data): series.append(QPointF(i, e))
        chart.addSeries(series)
        series.attachAxis(axisX)
        series.attachAxis(axisY)
        series.setColor(Qt.green)
        axisY.setRange(-10, axisY.max())
        layout = QVBoxLayout(self)
        chartView = QChartView(chart)
        chartView.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        layout.addWidget(chartView)
        self.setWindowTitle("Chart")
        self.setModal(True)
        size = QSize(800, 600)
        self.setMinimumSize(size)
        self.setMaximumSize(size)
