# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ahshoe/Desktop/mde1a1/src/core/dialog/association.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 500)
        Dialog.setMinimumSize(QtCore.QSize(420, 500))
        Dialog.setMaximumSize(QtCore.QSize(420, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(175, 16777215))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineBox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineBox.sizePolicy().hasHeightForWidth())
        self.lineBox.setSizePolicy(sizePolicy)
        self.lineBox.setObjectName("lineBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.lineBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineLable = QtWidgets.QLabel(self.lineBox)
        self.lineLable.setObjectName("lineLable")
        self.verticalLayout_3.addWidget(self.lineLable)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.lineBox)
        self.chainBox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chainBox.sizePolicy().hasHeightForWidth())
        self.chainBox.setSizePolicy(sizePolicy)
        self.chainBox.setObjectName("chainBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.chainBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chainLable = QtWidgets.QLabel(self.chainBox)
        self.chainLable.setObjectName("chainLable")
        self.verticalLayout_4.addWidget(self.chainLable)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.chainBox)
        self.shaftBox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shaftBox.sizePolicy().hasHeightForWidth())
        self.shaftBox.setSizePolicy(sizePolicy)
        self.shaftBox.setObjectName("shaftBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.shaftBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.shaftLable = QtWidgets.QLabel(self.shaftBox)
        self.shaftLable.setObjectName("shaftLable")
        self.verticalLayout_5.addWidget(self.shaftLable)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.shaftBox)
        self.sliderBox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderBox.sizePolicy().hasHeightForWidth())
        self.sliderBox.setSizePolicy(sizePolicy)
        self.sliderBox.setObjectName("sliderBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.sliderBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sliderLable = QtWidgets.QLabel(self.sliderBox)
        self.sliderLable.setObjectName("sliderLable")
        self.verticalLayout_6.addWidget(self.sliderLable)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.sliderBox)
        self.rodBox = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rodBox.sizePolicy().hasHeightForWidth())
        self.rodBox.setSizePolicy(sizePolicy)
        self.rodBox.setObjectName("rodBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.rodBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rodLable = QtWidgets.QLabel(self.rodBox)
        self.rodLable.setObjectName("rodLable")
        self.verticalLayout_7.addWidget(self.rodLable)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.rodBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Points Association"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">Choose a point to see it\'s association.</span></p><p><span style=\" font-size:10pt;\">Each point will </span><span style=\" font-size:10pt; color:#ff0000;\">Remove</span><span style=\" font-size:10pt;\"> their association when it\'s deleted.</span></p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "Origin"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Dialog", "Point0"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.lineBox.setTitle(_translate("Dialog", "Linkage"))
        self.lineLable.setText(_translate("Dialog", "None"))
        self.chainBox.setTitle(_translate("Dialog", "Fixed Chain"))
        self.chainLable.setText(_translate("Dialog", "None"))
        self.shaftBox.setTitle(_translate("Dialog", "Shaft"))
        self.shaftLable.setText(_translate("Dialog", "None"))
        self.sliderBox.setTitle(_translate("Dialog", "Slider"))
        self.sliderLable.setText(_translate("Dialog", "None"))
        self.rodBox.setTitle(_translate("Dialog", "Piston"))
        self.rodLable.setText(_translate("Dialog", "None"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

