# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'core/info/about.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from core.QtModules import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(586, 494)
        icon = QIcon()
        icon.addPixmap(QPixmap(":/icons/main.png"), QIcon.Normal, QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.verticalLayout_7 = QVBoxLayout(Dialog)
        self.verticalLayout_7.setContentsMargins(-1, 6, 6, 6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.iconLabel = QLabel(Dialog)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconLabel.sizePolicy().hasHeightForWidth())
        self.iconLabel.setSizePolicy(sizePolicy)
        self.iconLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.iconLabel.setObjectName("iconLabel")
        self.verticalLayout_2.addWidget(self.iconLabel)
        spacerItem = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Title = QLabel(Dialog)
        self.Title.setText("")
        self.Title.setObjectName("Title")
        self.verticalLayout_3.addWidget(self.Title)
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.AboutTab = QWidget()
        self.AboutTab.setObjectName("AboutTab")
        self.verticalLayout_4 = QVBoxLayout(self.AboutTab)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.description_text = QTextBrowser(self.AboutTab)
        self.description_text.setObjectName("description_text")
        self.verticalLayout_4.addWidget(self.description_text)
        self.tabWidget.addTab(self.AboutTab, "")
        self.LicenseTab = QWidget()
        self.LicenseTab.setObjectName("LicenseTab")
        self.verticalLayout_11 = QVBoxLayout(self.LicenseTab)
        self.verticalLayout_11.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label = QLabel(self.LicenseTab)
        self.label.setTextFormat(Qt.RichText)
        self.label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.label)
        self.tabWidget.addTab(self.LicenseTab, "")
        self.VersionsTab = QWidget()
        self.VersionsTab.setObjectName("VersionsTab")
        self.verticalLayout_6 = QVBoxLayout(self.VersionsTab)
        self.verticalLayout_6.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ver_text = QTextBrowser(self.VersionsTab)
        self.ver_text.setObjectName("ver_text")
        self.verticalLayout_6.addWidget(self.ver_text)
        self.tabWidget.addTab(self.VersionsTab, "")
        self.ArgumentsTab = QWidget()
        self.ArgumentsTab.setObjectName("ArgumentsTab")
        self.verticalLayout_9 = QVBoxLayout(self.ArgumentsTab)
        self.verticalLayout_9.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.args_text = QTextBrowser(self.ArgumentsTab)
        self.args_text.setObjectName("args_text")
        self.verticalLayout_9.addWidget(self.args_text)
        self.tabWidget.addTab(self.ArgumentsTab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.button_box = QDialogButtonBox(Dialog)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_box.sizePolicy().hasHeightForWidth())
        self.button_box.setSizePolicy(sizePolicy)
        self.button_box.setOrientation(Qt.Horizontal)
        self.button_box.setStandardButtons(QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.horizontalLayout_2.addWidget(self.button_box)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.button_box.accepted.connect(Dialog.accept)
        self.button_box.rejected.connect(Dialog.reject)
        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "About Pyslvs"))
        self.iconLabel.setWhatsThis(_translate("Dialog", "Pyslvs Icon!"))
        self.iconLabel.setText(_translate("Dialog", "<html><head/><body><p><img width=\"80\" src=\":/icons/main_big.png\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AboutTab), _translate("Dialog", "About"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">This program is free software; you can redistribute it and/or modify it under the terms of the Affero General Public License (AGPL) as published by Affero, Inc. version 3. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LicenseTab), _translate("Dialog", "LICENSE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.VersionsTab), _translate("Dialog", "Versions"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ArgumentsTab), _translate("Dialog", "Arguments"))
        self.button_box.setWhatsThis(_translate("Dialog", "Click to exit"))


import icons_rc
