# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ahshoe/Desktop/Pyslvs-PyQt5/core/synthesis/NumberAndTypeSynthesis/Collections.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(395, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/collections.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graph_engine_text = QtWidgets.QLabel(Form)
        self.graph_engine_text.setObjectName("graph_engine_text")
        self.horizontalLayout.addWidget(self.graph_engine_text)
        self.graph_engine = QtWidgets.QComboBox(Form)
        self.graph_engine.setObjectName("graph_engine")
        self.horizontalLayout.addWidget(self.graph_engine)
        self.reload_atlas = QtWidgets.QPushButton(Form)
        self.reload_atlas.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/dataupdate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reload_atlas.setIcon(icon1)
        self.reload_atlas.setObjectName("reload_atlas")
        self.horizontalLayout.addWidget(self.reload_atlas)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.graph_link_as_node = QtWidgets.QCheckBox(Form)
        self.graph_link_as_node.setObjectName("graph_link_as_node")
        self.verticalLayout.addWidget(self.graph_link_as_node)
        self.graph_degenerate = QtWidgets.QCheckBox(Form)
        self.graph_degenerate.setObjectName("graph_degenerate")
        self.verticalLayout.addWidget(self.graph_degenerate)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.Collection_list = QtWidgets.QListWidget(Form)
        self.Collection_list.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.Collection_list.setIconSize(QtCore.QSize(200, 200))
        self.Collection_list.setMovement(QtWidgets.QListView.Static)
        self.Collection_list.setResizeMode(QtWidgets.QListView.Adjust)
        self.Collection_list.setViewMode(QtWidgets.QListView.IconMode)
        self.Collection_list.setUniformItemSizes(True)
        self.Collection_list.setObjectName("Collection_list")
        self.verticalLayout_3.addWidget(self.Collection_list)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Preview_window = QtWidgets.QListWidget(Form)
        self.Preview_window.setMinimumSize(QtCore.QSize(205, 205))
        self.Preview_window.setMaximumSize(QtCore.QSize(205, 205))
        self.Preview_window.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.Preview_window.setIconSize(QtCore.QSize(200, 200))
        self.Preview_window.setMovement(QtWidgets.QListView.Static)
        self.Preview_window.setResizeMode(QtWidgets.QListView.Adjust)
        self.Preview_window.setViewMode(QtWidgets.QListView.IconMode)
        self.Preview_window.setUniformItemSizes(True)
        self.Preview_window.setObjectName("Preview_window")
        self.horizontalLayout_2.addWidget(self.Preview_window)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.NL_text = QtWidgets.QLabel(Form)
        self.NL_text.setObjectName("NL_text")
        self.verticalLayout_2.addWidget(self.NL_text)
        self.NL_input = QtWidgets.QSpinBox(Form)
        self.NL_input.setEnabled(False)
        self.NL_input.setObjectName("NL_input")
        self.verticalLayout_2.addWidget(self.NL_input)
        self.NJ_text = QtWidgets.QLabel(Form)
        self.NJ_text.setObjectName("NJ_text")
        self.verticalLayout_2.addWidget(self.NJ_text)
        self.NJ_input = QtWidgets.QSpinBox(Form)
        self.NJ_input.setEnabled(False)
        self.NJ_input.setMaximum(18)
        self.NJ_input.setObjectName("NJ_input")
        self.verticalLayout_2.addWidget(self.NJ_input)
        self.DOF_text = QtWidgets.QLabel(Form)
        self.DOF_text.setObjectName("DOF_text")
        self.verticalLayout_2.addWidget(self.DOF_text)
        self.DOF_input = QtWidgets.QSpinBox(Form)
        self.DOF_input.setEnabled(False)
        self.DOF_input.setObjectName("DOF_input")
        self.verticalLayout_2.addWidget(self.DOF_input)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        self.graph_engine.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.graph_engine_text.setText(_translate("Form", "Engine: "))
        self.graph_link_as_node.setText(_translate("Form", "Linkage as node"))
        self.graph_degenerate.setText(_translate("Form", "Show degenerate chain"))
        self.NL_text.setText(_translate("Form", "Number of links:"))
        self.NL_input.setToolTip(_translate("Form", "≥3"))
        self.NJ_text.setText(_translate("Form", "Number of joints:"))
        self.NJ_input.setToolTip(_translate("Form", "8~18"))
        self.DOF_text.setText(_translate("Form", "Degree of freedom:"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

