# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ahshoe/Desktop/Pyslvs-PyQt5/core/synthesis/NumberAndTypeSynthesis/Permutations.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(442, 558)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/NumberAndTypeSynthesis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Expression_joint_text = QtWidgets.QLabel(Form)
        self.Expression_joint_text.setObjectName("Expression_joint_text")
        self.gridLayout_2.addWidget(self.Expression_joint_text, 0, 0, 1, 1)
        self.Expression_joint = QtWidgets.QLineEdit(Form)
        self.Expression_joint.setObjectName("Expression_joint")
        self.gridLayout_2.addWidget(self.Expression_joint, 1, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.ReloadMechanism = QtWidgets.QPushButton(Form)
        self.ReloadMechanism.setAutoDefault(True)
        self.ReloadMechanism.setDefault(True)
        self.ReloadMechanism.setObjectName("ReloadMechanism")
        self.horizontalLayout_3.addWidget(self.ReloadMechanism)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.NJ_text = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.NJ_text.setObjectName("NJ_text")
        self.gridLayout.addWidget(self.NJ_text, 0, 1, 1, 1)
        self.NL_text = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.NL_text.setObjectName("NL_text")
        self.gridLayout.addWidget(self.NL_text, 0, 0, 1, 1)
        self.NL_input = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.NL_input.setObjectName("NL_input")
        self.gridLayout.addWidget(self.NL_input, 2, 0, 1, 1)
        self.NJ_input = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.NJ_input.setMaximum(18)
        self.NJ_input.setObjectName("NJ_input")
        self.gridLayout.addWidget(self.NJ_input, 2, 1, 1, 1)
        self.DOF_text = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.DOF_text.setObjectName("DOF_text")
        self.gridLayout.addWidget(self.DOF_text, 0, 2, 1, 1)
        self.DOF_input = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.DOF_input.setEnabled(False)
        self.DOF_input.setObjectName("DOF_input")
        self.gridLayout.addWidget(self.DOF_input, 2, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.Combine_number = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Combine_number.setAutoDefault(True)
        self.Combine_number.setObjectName("Combine_number")
        self.verticalLayout_2.addWidget(self.Combine_number)
        self.Expression_number = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.Expression_number.setObjectName("Expression_number")
        self.verticalLayout_2.addWidget(self.Expression_number)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graph_engine_text = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.graph_engine_text.setObjectName("graph_engine_text")
        self.horizontalLayout.addWidget(self.graph_engine_text)
        self.graph_engine = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.graph_engine.setObjectName("graph_engine")
        self.horizontalLayout.addWidget(self.graph_engine)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.Combine_type = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Combine_type.setAutoDefault(True)
        self.Combine_type.setObjectName("Combine_type")
        self.verticalLayout_3.addWidget(self.Combine_type)
        self.Topologic_result = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.Topologic_result.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.Topologic_result.setIconSize(QtCore.QSize(200, 200))
        self.Topologic_result.setMovement(QtWidgets.QListView.Static)
        self.Topologic_result.setResizeMode(QtWidgets.QListView.Adjust)
        self.Topologic_result.setViewMode(QtWidgets.QListView.IconMode)
        self.Topologic_result.setUniformItemSizes(True)
        self.Topologic_result.setObjectName("Topologic_result")
        self.verticalLayout_3.addWidget(self.Topologic_result)
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(Form)
        self.graph_engine.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Expression_joint_text.setText(_translate("Form", "Generalized expression:"))
        self.ReloadMechanism.setText(_translate("Form", "Reload from workbook"))
        self.NJ_text.setText(_translate("Form", "Number of joints:"))
        self.NL_text.setText(_translate("Form", "Number of links:"))
        self.NL_input.setToolTip(_translate("Form", "≥3"))
        self.NJ_input.setToolTip(_translate("Form", "8~18"))
        self.DOF_text.setText(_translate("Form", "Degree of freedom:"))
        self.Combine_number.setText(_translate("Form", "Number Synthesis"))
        self.graph_engine_text.setText(_translate("Form", "Graphviz and NetworkX engine: "))
        self.Combine_type.setText(_translate("Form", "Type Synthesis"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

